### PR TITLE
stub: mark CallStreamObserver stable

### LINKED ISSUE #1788: Tracking Issue for (Call|ServerCall)StreamObserver being Experimental.
Specific usages:
- `CallStreamObserver`
- `ServerCallStreamObserver`

### PR DESCRIPTION
**Pull request by benjaminp**
I believe this was overlooked in #7938's work to fix #1788.

### CODE REVIEW

**Comment by ejona86** [comment]
This class is not intended to be stable. See https://github.com/grpc/grpc-java/issues/1788#issuecomment-453227259 and https://github.com/grpc/grpc-java/pull/7938/files/b1ddff181ac068f805492b1f2a4fa4b64c2311f4#diff-603fa39ffdc9115328b9a77d2a10a27d5f5a75f77a22f3d552bdf2d7ee6bf208, both of which you referenced.

Note: the previous javadoc formatting wasn't wrong and didn't seem unreadable, so it is best left as-is. Different people have different views of "best" for things like that and making changes like that causes unhelpful "style fighting" where the style changes back-and-forth depending on who touched the file last.

While maybe #1788 was closed prematurely and could be reopened, so much of that has been stabilized I think it may be a better idea to open a new issue to track CallStreamObserver.

**Comment by benjaminp** [comment]
> This class is not intended to be stable. See [#1788 (comment)](https://github.com/grpc/grpc-java/issues/1788#issuecomment-453227259) and https://github.com/grpc/grpc-java/pull/7938/files/b1ddff181ac068f805492b1f2a4fa4b64c2311f4#diff-603fa39ffdc9115328b9a77d2a10a27d5f5a75f77a22f3d552bdf2d7ee6bf208, both of which you referenced.

Thanks for pointing me to those. I got confused seeing an unstable base class with its methods overridden by stable subclasses.

> 
> Note: the previous javadoc formatting wasn't wrong and didn't seem unreadable, so it is best left as-is. Different people have different views of "best" for things like that and making changes like that causes unhelpful "style fighting" where the style changes back-and-forth depending on who touched the file last.

Sorry, it was not my intention to start any sort of style war. This is just what `google-java-format` spat out when I touched the annotation.

> 
> While maybe #1788 was closed prematurely and could be reopened, so much of that has been stabilized I think it may be a better idea to open a new issue to track CallStreamObserver.

#8499

**Comment by ejona86** [comment]
> This is just what google-java-format spat out when I touched the annotation.

Makes sense. Auto-code-formatters also cause style wars, potentially at higher scale, even with different versions of themselves. I've been disappointed by the crop of style formatters trying to reproduce gofmt's success. They ignored the one important aspect that made gofmt successful: it didn't throw away the existing formatting and only reformatted what was out-of-style. Oh, well.

> #8499

@benjaminp, would you mind changing the link in the ExperimentalApi annotation of CallStreamObserver to point to your new issue?

**Comment by benjaminp** [comment]
> @benjaminp, would you mind changing the link in the ExperimentalApi annotation of CallStreamObserver to point to your new issue?

Sure, see #8502.

**Pull request closed without merging**
