### PR TITLE
Use Gradle's version catalog

### PR DESCRIPTION
**Pull request by ejona86**
Note that there are two commits here. One makes a preping change.
I've confirmed the poms produced are equivalent.

This moves our depedencies into a plain file that can be read and
updated by tooling. While the current tooling is not particularly better
than just using gradle-versions-plugin, it should put us on better
footing. gradle-versions-plugin is actually pretty nice, but will be
incompatible with Gradle 8, so we need to wait a bit to see what the
future holds.
    
Left libraries as an alias for libs to reduce the commit size and make
it easier to revert if we don't end up liking this approach.
    
We're using Gradle 7.3.3 where it was an incubating fetaure. But in
Gradle 7.4 is became stable.

CC @YifeiZhuang

### CODE REVIEW

**Review by sergiitk — APPROVED** [review]
LGTM! 

1) I've noticed there's also support for [plugins](https://docs.gradle.org/7.3.3/userguide/platforms.html#sec:plugins) - would be great to move them too. Not necessarily in this PR. 
2) At some point, we should also look into [bundles](https://docs.gradle.org/7.3.3/userguide/platforms.html#sec:plugins) - could be useful, but I don't have candidates off the top of my head right now.

**Comment by sergiitk** [comment]
Sidenote: didn't notice any issues with building this with IntelliJ.

**Comment by ejona86** [comment]
Yes, I meant to mention that plugins would be done in the future. I'm honestly pretty happy with how plugins are defined today; I actually wish the same "define the dependency and just leave off the version" approach was available for normal dependencies. With auto-upgrading it could be worthwhile, even if it requires a different syntax at all callsites. Right now I didn't 1) because this is large enough already and 2) we do some funky business with android in settings.gradle and I wanted to wait to see if that confuses any tooling.

Yeah, I saw the bundles but didn't see a need for them yet. If Netty used `runtime` scope instead of `compile` scope for its dependencies, they would probably be more useful to use.

**Comment by ejona86** [comment]
> I actually wish the same "define the dependency and just leave off the version" approach was available for normal dependencies

Another note: this is possible today, but it requires using a platform/version constraints. And those change all transitive dependencies which won't mix well with Maven and honestly not what I want because it can cause downgrades.

**Pull request merged**
