### PR TITLE
netty: increase message quantum

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
This is a minor change setting the size of data frames sent when
interleaving RPCs.  The size was ~1024bytes previously, which
resulted in the `writev` syscalls sending many smaller chunks
before hitting the low water mark.  The end effect is larger calls
to `writev`, as seen with strace.

The effect of this is noticeable when sending a lot of data.  When
sending as many 1MB messages as possible it nearly doubles the
rate.

Before:

```
INFO: single throughput GRPC
50.0%ile Latency (in nanos):		280856575
90.0%ile Latency (in nanos):		349618175
95.0%ile Latency (in nanos):		380444671
99.0%ile Latency (in nanos):		455172095
99.9%ile Latency (in nanos):		537198591
100.0%ile Latency (in nanos):		566886399
QPS:                           346
Count:                         103984
```

After:
```
gRPC
50.0%ile Latency (in nanos):		125948927
90.0%ile Latency (in nanos):		166322175
95.0%ile Latency (in nanos):		177276927
99.0%ile Latency (in nanos):		193840127
99.9%ile Latency (in nanos):		226841599
100.0%ile Latency (in nanos):		256110591
QPS:                           774
Count:                         232340
```

FYI: @louiscryan @Scottmitch @normanmaurer @ejona86

### CODE REVIEW

**Comment by Scottmitch** [comment]
bigger quantum for the win ... did you happen to try the uniform allocator during this evaluation?

**Comment by carl-mastrangelo** [comment]
@Scottmitch 

uniform with default chunk size (1K):
```
INFO: single throughput GRPC 
50.0%ile Latency (in nanos):		266686463
90.0%ile Latency (in nanos):		314001407
95.0%ile Latency (in nanos):		336211967
99.0%ile Latency (in nanos):		386523135
99.9%ile Latency (in nanos):		506990591
100.0%ile Latency (in nanos):		546250751
QPS:                           367
Count:                         110266
```

Uniform with 16 K chunk:
```
50.0%ile Latency (in nanos):		121700351
90.0%ile Latency (in nanos):		146510847
95.0%ile Latency (in nanos):		154373119
99.0%ile Latency (in nanos):		172407807
99.9%ile Latency (in nanos):		188552191
100.0%ile Latency (in nanos):		218884095
QPS:                           811
Count:                         243381
```



Note that each QPS is a ping pong 1MB message.  811 means 811 MB/s in each direction.

**Comment by ejona86** [comment]
CC @lukaszx0

**Comment by lukaszx0** [comment]
Nice!

**Comment by skyao** [comment]
So nice!

**Comment by macalinao** [comment]
Awesome for data science.

**Pull request merged**
