### PR TITLE
xds: import v3 version of aggregate.ClusterConfig proto.

### PR DESCRIPTION
**Pull request by voidzcy**
Just got back from Mark, `envoy/config/cluster/aggregate/v2alpha/cluster.proto` does have a v3 version, which is at `envoy/extensions/clusters/aggregate/v3/cluster.proto`.

--------
Followup for #7551

### CODE REVIEW

**Comment by dapengzhang0** [comment]
Are you going to delete the v2alpha version?

**Comment by voidzcy** [comment]
Yeah, v2alpha version is no longer needed. Deleted now.

**Review by dapengzhang0 — APPROVED** [review]

**Comment by voidzcy** [comment]
Ah... v2alpha actually is the extension for v2. We have to bring it back.

**Comment by sanjaypujare** [comment]
> Ah... v2alpha actually is the extension for v2. We have to bring it back.

Seems wrong terminology. v2alpha should precede v2 and hence v2 should supersede v2alpha right?

**Comment by voidzcy** [comment]
> > Ah... v2alpha actually is the extension for v2. We have to bring it back.
> 
> Seems wrong terminology. v2alpha should precede v2 and hence v2 should supersede v2alpha right?

Oops, you are right. But since v2 has been frozen, they mean the same.

**Pull request merged**
