### PR TITLE
Deprecate OkHttpChannelBuilder#overrideHostForAuthority

### PR DESCRIPTION
**Pull request by zhangkun83**
It is a duplication of overrideAuthority().

@madongfly

### CODE REVIEW

**Comment by madongfly** [comment]
@zhangkun83 LGTM

**Comment by ejona86** [comment]
I know there are lots of users of the current API. I left the existing method to reduce pain/risk for upgrading to the new API

**Comment by zhangkun83** [comment]
The current API will no longer work once we start support NameResolver. Migrating to the new API should be trivial.

**Comment by ejona86** [comment]
It is trivial, assuming you know the port, or assuming you don't care about the port. But it also means upgrading users in the same commit as bringing in the gRPC changes.

**Comment by zhangkun83** [comment]
Fair enough. I can deprecate it at this moment. After the new API is sync'ed in, I will migrate the users and then delete the current API. WDYT?

**Comment by ejona86** [comment]
SGTM

**Comment by zhangkun83** [comment]
@ejona86 PTAL

**Comment by madongfly** [comment]
@zhangkun83 LGTM

**Comment by ejona86** [comment]
@zhangkun83 LGTM

**Comment by zhangkun83** [comment]
@ejona86 we should probably cherry-pick this into the beta branch. WDYT?

**Comment by ejona86** [comment]
@zhangkun83, that sounds fine to me.

**Pull request merged**
