### PR TITLE
Migrate Automatic Exec Groups by adding a toolchain parameter to the affected actions

### PR DESCRIPTION
**Pull request by kotlaja**
This is a step forward for the full migration of Automatic Exec Groups (AEGs). This change will be effective once AEGs are enabled.

Goal of this migration:
* Each toolchain type should have its own execution platform. Before this change, the execution platform was selected on a rule base, not on a toolchain type base. 
* Each action which uses a tool coming from a toolchain should specify the toolchain type inside ctx.action.{run, run_shell} `toolchain` attribute. 

I've added `None` since the executable (`protoc`) seems not to be from a real toolchain. Moreover, the rule itself doesn't register any toolchains.

Ref cl/559113276.

### CODE REVIEW

**Comment by kotlaja** [comment]
I can see that this PR request fails with `no toolchain attribute` error, which is probably since this repo uses Bazel version lower than 6.0, right? `toolchain` param is added from Bazel 6.0.

**Comment by ejona86** [comment]
Yeah, we support the two most recent versions. So we'll drop Bazel 5.x in January.

**Review by ejona86 — APPROVED** [review]

**Review by sergiitk — APPROVED** [review]

**Comment by kotlaja** [comment]
@ejona86  @sergiitk 
Hi one more time! :)

I'm interested in when this change will be inside a new release since it's needed for my further migration of Automatic Exec Groups. Do you maybe know when can this happen approximately?
I see that v1.58.0 release doesn't have these changes, so I need to wait for the next release in order to use it in other projects to not be blocked by the error before this PR. Example of usage is intellij: [link](https://github.com/bazelbuild/intellij/blob/master/ext/proto/BUILD#L18).

**Comment by ejona86** [comment]
@kotlaja, v1.59.0 was scheduled for this past Tuesday. It was delayed because of some conversations with protobuf. It [looks like](https://repo1.maven.org/maven2/io/grpc/grpc-api/1.59.0/) it was released yesterday. Release notes and notification are still in the works, but the release is available.

**Pull request merged**
