### PR TITLE
Migrate off deprecated mockito method

### PR DESCRIPTION
**Pull request by cushon**
See: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/ArgumentMatchers.html#anyListOf-java.lang.Class-

### CODE REVIEW

**Review by sanjaypujare — APPROVED** [review]
LGTM

**Comment by sanjaypujare** [comment]
@cushon can you check why the 2 required CI results are not in yet? If needed you can close/reopen this PR to restart those tests

**Comment by sanjaypujare** [comment]
@cushon do you want me to merge this?

**Comment by cushon** [comment]
@sanjaypujare yes, if you could merge that would be great. I think it's ready to go, and I don't have permission to merge

**Review by ejona86 — COMMENTED** [review]
LGTM

**Pull request merged**
