### PR TITLE
Bumping proto-google-common-protos to 1.0.0

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**
We recently released proto-google-common-protos to 1.0.0.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @garrettjonesgoogle isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by garrettjonesgoogle** [comment]
Reverify me, linuxfoundation!

**Comment by ejona86** [comment]
@garrettjonesgoogle, would this be good to backport to the 1.8 release next week?

**Comment by garrettjonesgoogle** [comment]
It's really just about guarantee of surface stability - there might be some extra protos in there but I'm not sure. I think it really depends if you want to "hand over" this surface stability to users of 1.8; there is very little risk to backporting it.

**Comment by ejona86** [comment]
Okay. We didn't stabilize the API that uses it in 1.8, and we'd still need to figure out Java 6 vs Java 7 bytecode before we could. So I won't bother backporting, since it's not really a bug and there's no need.

**Pull request merged**
