### PR TITLE
Fix gson / opencensus bazel naming mixup

### PR DESCRIPTION
**Pull request by duelinmarkers**
In 72b9ee2 (see also #3328, #3338), gson kept its old name while opencensus got what should have
become gson's new name instead of a fixed opencensus name.

I think this resolves that.

### CODE REVIEW

**Comment by duelinmarkers** [comment]
I signed it!

**Comment by ejona86** [comment]
Okay to test

**Comment by duelinmarkers** [comment]
Could we have 5c902c938489a0f04642f1c7d206555e3b659ffe and 7d0229a1f589c886c1b4088bbb93c62cbd7ad1b6 cherry-picked onto the v1.6.x branch so the first 1.6 release will be useable from bazel projects conveniently? I can submit a PR for this if it would be helpful. Thanks.

**Comment by ejona86** [comment]
@duelinmarkers, yeah, I think it makes sense to backport them. I've added the backport label for us to backport them before the release.

**Comment by pgr0ss** [comment]
Thanks @duelinmarkers for fixing my mistake. Looks I screwed up my scripting for bulk updating.

**Pull request merged**
