### PR TITLE
android-interop-test: add JetifyAndroidManifest.xml

### PR DESCRIPTION
**Pull request by dapengzhang0**
Fix internal tests failure introduced in #8808. It was (manually) fixed internally during the last import but somehow I must have missed the step to upstream the fix first.

### CODE REVIEW

**Review by ejona86 — APPROVED** [review]

**Comment by dapengzhang0** [comment]
Unfortunately this fails in OSS 
https://firebase.corp.google.com/project/grpc-testing/testlab/histories/bh.6e2cfdde264f9eb3/matrices/7098312082707629879/executions/bs.e8b7dbe7820295b

We might need to have two files `AndroidManifest.xml` and `JetifyAndroidManifest.xml` and let internal BUILD refer to `JetifyAndroidManifest.xml`

**Comment by dapengzhang0** [comment]
Now fixed both internally and OSS. PTAL @ejona86

**Review by ejona86 — COMMENTED** [review]
Should this be an internal-only file? It seems it'd also be good to have a comment somewhere saying when it is no longer necessary.

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
If the `android.support.multidex.MultiDexApplication` class name the only difference, we can do that change in the import script (search/replace within a single file is pretty easy IIRC). But this is also expected to be very temporary, so we should just do "what's easy."

**Comment by dapengzhang0** [comment]
I partially revert the lint fix, seems still now breaking internally.

**Comment by dapengzhang0** [comment]
Closing. This file will be added internally only.

**Pull request closed without merging**
