### PR TITLE
netty: update to 4.1.2.Final and tcnative Fork18

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by buchgr** [comment]
seems like I was too fast, while released it's not on maven central yet :)

**Comment by buchgr** [comment]
Throughput is up ~5% with this new Netty release. Guessing at HPACK changes. Thanks @normanmaurer and @Scottmitch! :)

Netty 4.1.1.Final
```
Outstanding RPCs per Channel:   10
Server Payload Size:            0
Client Payload Size:            0
50%ile Latency (in micros):     433
90%ile Latency (in micros):     468
95%ile Latency (in micros):     486
99%ile Latency (in micros):     658
99.9%ile Latency (in micros):   1378
Maximum Latency (in micros):    48927
QPS:                            90211
```

Netty 4.1.1.Final
```
Channels:                       4
Outstanding RPCs per Channel:   10
Server Payload Size:            0
Client Payload Size:            0
50%ile Latency (in micros):     412
90%ile Latency (in micros):     449
95%ile Latency (in micros):     466
99%ile Latency (in micros):     578
99.9%ile Latency (in micros):   1336
Maximum Latency (in micros):    24959
QPS:                            95105
``

**Comment by normanmaurer** [comment]
@buchgr @Scottmitch woot :)

**Comment by nmittler** [comment]
@buchgr awesome! LGTM

@Scottmitch @normanmaurer great job guys! :)

**Comment by Scottmitch** [comment]
yay team! hopefully longer term GC will be less of an impact too

**Comment by ejona86** [comment]
Let's hold off on merging this until the 0.15 release is cut (which should be today, since tests appear to have succeeded internally)

**Comment by carl-mastrangelo** [comment]
@buchgr One thing about this change is that in conjunction with your change in c5733742cea6418bd712646a8fc7f35bb1e2f953

It will always copy the AsciiString, since the array size will be 32 for small headers.

**Comment by buchgr** [comment]
The upgrade to Netty 4.1.2.Final seems to trigger some bug only on Linux. Can always reproduce in a Linux VM. Looking ...

**Comment by normanmaurer** [comment]
@buchgr let me know if you have any more infos or questions.

**Comment by buchgr** [comment]
meehhh ... forgot to update the epoll dependency to 4.1.2 😅 The LoadClient failed with

```
java.lang.NoClassDefFoundError: io/netty/util/internal/MpscLinkedQueueNode
	at java.lang.ClassLoader.defineClass1(Native Method)
        ....
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.channel.epoll.EpollServerSocketChannel.newChildChannel(EpollServerSocketChannel.java:122)
....
```

Works now ....

**Comment by normanmaurer** [comment]
Ha! Thanks for the update

**Comment by Scottmitch** [comment]
> Works now ....

Time to define a common variable :wink:?

**Comment by ejona86** [comment]
It also sounds like Netty should do version-pinning (using square brackets: [4.1.1.Final]). That would have been ignored by gradle anyway, but at least maven users would benefit from it.

**Comment by ejona86** [comment]
@buchgr, do we also want to "back-port" this to the release branch v1.0.x?

**Comment by buchgr** [comment]
@ejona86 I would think so. It contains the hpack fixes and seems to do quite a bit better in benchmarks.

**Comment by ejona86** [comment]
@buchgr, could you go ahead and do so?

**Comment by buchgr** [comment]
of course. sorry 😅

**Comment by buchgr** [comment]
cherry-picked into v1.0.x as a39df84436e

**Pull request merged**
