### PR TITLE
binder/test: Stop running Robolectric tests on APIs < 19.

### PR DESCRIPTION
**Pull request by zhangkun83**
This is a port of internal cl/547560711

### CODE REVIEW

**Comment by ejona86** [comment]
API Level 19 became our advertised minimum version (#8620) after the security policies were added, so this doesn't bother me from a policy standpoint. Deleting "failsForSdkLevelTooLow" is potentially concerning, since this is specifically for security. @markb74, should there be any concerns with removing that test?

**Comment by jdcormie** [comment]
All the code in SecurityPolicies should have unit test coverage so if we want to delete the `failsForSdkLevelTooLow` test, we should first update the system-under-test to actually remove support for SDK<19. I think this means changing SecurityPolicies.isDeviceOwner() to just call the SDK 18+ `isDeviceOwnerApp` API unconditionally. Security-wise this should be OK -- it'll throw NoSuchMethodException on SDK < 18 devices. Even better would be to annotate SecurityPolicies.isDeviceOwner() with @androidx.annotation.RequiresApi(SDK=18)

**Comment by markb74** [comment]
> I think this means changing SecurityPolicies.isDeviceOwner() to just call the SDK 18+ `isDeviceOwnerApp` API unconditionally. 

+1. My first though was that it's fine to leave the implementation unchanged, but this is safer.

Either way it's been >10 years since API 18.

**Comment by larry-safran** [comment]
Note that ServiceProvider.isDeviceOwner() already has:
pkg -> VERSION.SDK_INT >= 18 && devicePolicyManager.isDeviceOwnerApp(pkg)

**Review by jdcormie — APPROVED** [review]

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
