### PR TITLE
xds: go to UNAVAILABLE instead of send NACK for invalid default route

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by voidzcy** [comment]
Do not patch to existing code. The way routes are parsed will be changed in #7031 (and following PRs).

**Comment by dapengzhang0** [comment]
This feature is targeted for v1.30. Is #7031 (and following PRs) that includes this feature be done and well tested before v1.30?

**Comment by voidzcy** [comment]
Hmm... At least changes in XdsClient and data conversions would be done shortly. And I think that's enough for this not NACKing last non-default route change right?

**Comment by dapengzhang0** [comment]
>And I think that's enough for this not NACKing last non-default route change right?

Not NACKing + UNAVAILABLE

**Comment by voidzcy** [comment]
> > And I think that's enough for this not NACKing last non-default route change right?
> 
> Not NACKing + UNAVAILABLE

No problem. That could be done immediate after #7031, which cleans things up.

**Comment by dapengzhang0** [comment]
The latest decision is not to change this behavior for this release.

**Pull request closed without merging**
