### PR TITLE
Bump versions for assorted dependencies

### PR DESCRIPTION
**Pull request by ejona86**
If I didn't upgrade X there is probably a reason, but worst-case the
reason was "I was lazy." I did the easy stuff, so if upgrading caused
problems of any real sort I skipped it and moved on. The main other
reason is there's some stuff we're more conservative about upgrading,
but you can't distinguish one from the other in this commit.

---

I plan to backport this to the release branch.

### CODE REVIEW

**Comment by sergiitk** [comment]
OOM - restarting

**Comment by sergiitk** [comment]
Android had something else:

```
Execution failed for task ':grpc-binder:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/tmpfs/tmp/.gradle/caches/transforms-3/0bd6c8992d7951557fd0d7bdce620ae5/transformed/core-1.8.0/res/values/values.xml:104:5-113:25: AAPT: error: resource android:attr/lStar not found.
```

I'll restart to check if it's a fluke.

**Comment by ejona86** [comment]
That android error is probably legit. I avoided upgrading some other libraries because of stuff like that.

**Comment by ejona86** [comment]
@sergiitk, build is passing now.

**Review by sergiitk — APPROVED** [review]

**Pull request merged**
