### PR TITLE
Minor readability changes

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Since it is easy to make methods and classes non final, and near impossible to go the other way, make them final.  

On a side note: there seems to be a lot of methods in AbstractClientStream, AbstractServerStream, and AbstractStream.  Some method culling would probably be a good thing to do eventually.

### CODE REVIEW

**Comment by ejona86** [comment]
I don't think we should add final everywhere unless it adds some value for that particular instance. In these cases, I think it is useless effort because these APIs are internal and we are free to add final later without real issue. Similarly, making package-private classes final seems to have limited benefit. Going through this process with classes in io.grpc package would make more sense, but not for io.grpc.transport.

**Comment by carl-mastrangelo** [comment]
There are two big benefits to finalizing stuff.  First and foremost is documentation.  The intended use of AbstractStream and AbstractServerStream and other children is not clear.  As someone who is new to this project, the distinguishing feature between  AbstractStream, AbstractServerStream, and NettyServerStream is very difficult to see.  The distinction is even less clear with AbstractStream -> AbstractClientStream -> Http2ClientStream -> NettyClientStream.  I was hoping to make it easy for people who want to contribute code (i.e. me).  Making it obvious what methods can/should be overridden and the responsibilities of a child class is a maintainability win.  

The second is keeping our selves honest about upholding the class contract.  Even if we don't really override methods, and the package is strictly internal, it's still a good idea to enforce expectations.  (As an aside, I wasn't able to find a place in the README or in the transport package where it actually says it is internal.)  There are also other reasons to make things as final as possible list in Effective Java, but these two primary reasons for this change.

In regards to NotThreadSafe, Channel does use @ThreadSafe, so there is at least some precedent.  Additionally, since there is synchronization going on in AbstractStream, a new comer might be tempted to think that Streams are threadsafe.

**Comment by nmittler** [comment]
I'm fine with these changes.

**Comment by ejona86** [comment]
@carl-mastrangelo said:
> Making it obvious what methods can/should be overridden and the responsibilities of a child class is a maintainability win.

> The second is keeping ourselves honest about upholding the class contract.

> it's still a good idea to enforce expectations

When you added the `final`s, did you know which methods can/should be overridden or the class contract or expectations? Blindly adding `final` everywhere in internal classes makes it so that people blindly remove `final` if they need to override the method, because they don't believe the final was there to prevent them doing what they're doing.

`complete()` and `receiveMessage()` seem reasonable to override. If someone wants to override `complete()` should they instead make a new method, or remove the `final`? I think I would prefer them to override `complete()`. If it is "documentation" having the `final` unnecessarily seems like incorrect documentation or documentation you learn to ignore.

The Effective Java reasoning for marking methods final doesn't seem to apply here.

> First and foremost is documentation

This I is something I can get behind, for the particular instances of AbstractStream, AbstractClientStream, and AbstractServerStream. They are a mess of methods, and marking methods final makes it clear something isn't getting overridden. I mainly want to make the change for the right reason, because I don't want "add final to methods" to be a blind pattern.

I do still think `complete()` and `receiveMessage()` are probably better off without `final` though.

**Comment by carl-mastrangelo** [comment]
> Blindly adding final everywhere in internal classes makes it so that people blindly remove final if they need to override the method 

I would be doubtful of this.  The implications of removing final are much more drastic, and force the remover to think about how users would interact with the library.  On the other hand, adding final is effectively just checking to see if it compiles.  Considering that the number of users of this library is small, we are note yet in a good position to determine which methods really should be overrideable.  

As it stands, these classes look like they were an accident, rather than designed with an intent.  Making everything final allows us to safely defer on putting a lot of time into the structure.    

Having these final provides a lot of benefits, even blindly.  Here are some scenarios where it would be beneficial:

* A user of the gprc library see that a method is non final, so they override it.  In the future, when we eventually want to change that method, or add additional behavior, the overrider doesn't get the additional behavior.  If the method had been final, they would have had to ask the mailing list first, or at least a grpc owner.  

* Seeing the word "final" in the classes causes other editors of this class to think about how the methods _they_ add will interact with the rest of the class hierarchy.


There are downsides to adding final everywhere as you mentioned, but there are also huge upsides to it as well, and I would ask that you please consider both of those rather than just the negatives.

I have reverted the final on complete and receiveMessage.  If you don't have any other major qualms, I would like to get this in before it gets too far behind head.

**Comment by carl-mastrangelo** [comment]
Reverting this change too.

**Pull request closed without merging**
