### PR TITLE
gh-4367: actually use of provided executor pool

### PR DESCRIPTION
**Pull request by jpitz**
Issue: https://github.com/grpc/grpc-java/issues/4367

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by carl-mastrangelo** [comment]
@jpitz The executor you modified is slightly different.  The one provided by the application to the ManagedChannelBuilder is for running RPC callbacks.  The channel executor is for running channel related operations that generally do not block for very long.  They have different purposes.

**Comment by jpitz** [comment]
hmm... Can you point to where this is being used in code? I was trying to track it down, but couldn't find it.

**Comment by jpitz** [comment]
I see so in the typical case with Netty, you don't necessarily need to worry about tuning the executor on the client, but rather only the workerEventLoopGroup.

**Comment by ejona86** [comment]
@jpitz, I don't think that's the correct take-a-way. The executor you pass to the builder is used: https://github.com/grpc/grpc-java/blob/v1.11.0/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L528

There's a few other cases that need an executor but we didn't feel comfortable using the application's executor. That's what you found.

**Comment by jpitz** [comment]
I see.

**Pull request closed without merging**
