### PR TITLE
okhttp: revert okhttp: Add restricted AppEngine SSL setup (#2795)

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
This reverts commit b753231590cd81505aa3694ba6c70137b1aa8877.

@kpayson64 FYI this is being reverted since it should have been made to the master branch instead of v1.2.x

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
retest this jenkins

**Comment by kpayson64** [comment]
@carl-mastrangelo @ejona86 
Moving this back to master will mean that the VTK team will have to wait 6+ weeks for gRPC to function correctly on App Engine.  The final Conscrypt bug fix that unblocks from the App Engine side is currently in deployment, so that leaves this as the only blocker.

**Comment by carl-mastrangelo** [comment]
@kpayson64 The feature window was closed March 6th.  VTK will need to wait for the next release.

**Comment by kpayson64** [comment]
@carl-mastrangelo 
Can there at least be a discussion with the stakeholders here?  If 6+ weeks is an acceptable horizon for them, I have no objection.

**Pull request merged**
