### PR TITLE
Fix race condition in Compression Test

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by ejona86** [comment]
What is the race? I would expect the blocking unaryCall to provide enough synchronization between Fzip and the test. anyRead should only be used in one thread, and anyWritten should only be used in another.

**Comment by carl-mastrangelo** [comment]
CompressionTest uses multiple threads?  I don't think theres any synchronization between the junit test?  They aren't synchronizing on the same object?  The race detector detected this.

**Comment by ejona86** [comment]
The race detector is very new, I don't think we should be blindly trusting it. There are likely multiple threads being used, but from everything I see it seems safe given the Java memory model.

**Comment by ejona86** [comment]
The race may be between `beforeTests()` and the server processing the request, since that is triggered by I/O and a race detector wouldn't know there is any causality. The race may also be between the client and server, since they both will use the same `Fzip` instance. Yeah, shared by client and server is most likely it.

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

**Pull request merged**
