### PR TITLE
api: stablize channel state API

### PR DESCRIPTION
**Pull request by YifeiZhuang**

### CODE REVIEW

**Comment by ejona86** [comment]
When was this one approved?  I don't see any discussion saying it was ready. It might be now, but that would have been _very_ recent and definitely after the last time it was discussed.

**Comment by ejona86** [comment]
CC @larry-safran

**Comment by larry-safran** [comment]
We should have updated the issue when we approved it rather than just the spreadsheet.  It was June 7th when it was approved.

**Comment by YifeiZhuang** [comment]
Another API under this experimental issue: https://github.com/grpc/grpc-java/blob/78cf1c39cfdec8850fd215f33a9154e50dcae05c/api/src/main/java/io/grpc/ConnectivityState.java#L25

we decided not to stablize this due to missing cross language agreement about connectivity state and its transitions.

https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md

**Pull request closed without merging**
