### PR TITLE
Fixing typo in SECURITY.md

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
See https://en.wikipedia.org/wiki/Cipher_suite

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @schmidt-sebastian isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by schmidt-sebastian** [comment]
I don't think I will be able to sign the CLA :/

**Comment by ran-su** [comment]
@schmidt-sebastian We can not accept you PR if you don't sign the CLA.
I think you are able to sign this CLA as an employee.

**Comment by dapengzhang0** [comment]
@schmidt-sebastian as @ran-su said, goto/cla and sign as employee.

**Comment by dapengzhang0** [comment]
signcla/ shows that we can accept code from @schmidt-sebastian.

**Comment by ejona86** [comment]
@dapengzhang0, signcla/ and goto/cla is the wrong CLA. That's the Google CLA. We need the CNCF CLA.

@schmidt-sebastian, on the CNCF page you should be able to click the "Sign up to contribute to this project as an employee" and then "Log in with Google" with your `@google.com` account.

**Comment by schmidt-sebastian** [comment]
I signed it.

**Comment by schmidt-sebastian** [comment]
Hm, that was easy. I thought I had already followed the steps on the linuxfoundation website. CLA looks good now :)

**Comment by ejona86** [comment]
I kicked the Windows build. It was hung for some reason. We can merge once it finishes.

@schmidt-sebastian, thank you! Thanks for dealing with the CLA for such a small change. Such fixes do improve the overall quality, so we're happy to have it.

**Pull request merged**
