### PR TITLE
Update Netty dependency to 4.1CR4.

### PR DESCRIPTION
**Pull request by buchgr**
Seems to build fine on my Mac and Linux VM.

### CODE REVIEW

**Comment by buchgr** [comment]
Fixes #1581

**Comment by ejona86** [comment]
Is the bump to Fork15 required? If so, we need to know for the release notes.

LGTM (probably is good to wait for the CIs to finish)

**Comment by buchgr** [comment]
@ejona86 no, also works with Fork14. I just updated it, cause I saw that tcnative was also released. Yep, always wait for CIs :smile:

**Comment by buchgr** [comment]
@ejona86 save to merge? code coverage check seems like it can be ignored?

**Comment by ejona86** [comment]
@buchgr, yeah, safe to merge.

**Comment by buchgr** [comment]
sorry for the delay. was traveling home for easter :-). cherry-picked (88d31748c455e6ebb82df3f5d36b2cfd0da311eb).

**Pull request closed without merging**
