### PR TITLE
[Backport][v1.37.x] Enable CSDS test

### PR DESCRIPTION
**Pull request by lidizheng**
As title.

sponge/a1956f60-14a8-40e9-896d-f08a56caf20f

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc-java/8112)

### CODE REVIEW

**Comment by lidizheng** [comment]
@sergiitk PTAL.

**Review by sergiitk — APPROVED** [review]

**Comment by sergiitk** [comment]
Good catch with the admin interface.

**Comment by lidizheng** [comment]
This is blocked by [cl/369971542](http://cl/369971542).

**Comment by lidizheng** [comment]
Test has passed with a green flag: https://fusion2.corp.google.com/invocations/a1956f60-14a8-40e9-896d-f08a56caf20f/targets

I think this PR should be safe to merge.

**Pull request merged**
