### PR TITLE
Clean up gRPC

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by gnossen** [comment]
https://github.com/kelseyhightower/nocode

**Comment by ejona86** [comment]
Overall, the change looks fine to me. But you need to go through the gRFC process first.

**Comment by ejona86** [comment]
"Thank you for adhering to our style guide."

"Please create a `.gitignore` containing `*`"

**Comment by carl-mastrangelo** [comment]
@ejona86 Wilco, but I'll need to "clean up" the grpc/proposal repo.  Putting this on indefinite hold.

**Comment by ejona86** [comment]
Ideally this would include a test to prevent a regression.

**Comment by vjpai** [comment]
What kind of cleanup PR has a "+1" ?

**Pull request closed without merging**
