### PR TITLE
xds: promote ServerXdsClient

### PR DESCRIPTION
**Pull request by voidzcy**
#7500 is for client side.

### CODE REVIEW

**Review by sanjaypujare — CHANGES_REQUESTED** [review]
Can you make `io.grpc.xds.XdsClientImplTestForListener` pass with `ServerXdsClient` instead of the current `XdsClientImpl2` ? Without that we'll be breaking server side.

**Comment by voidzcy** [comment]
> Can you make `io.grpc.xds.XdsClientImplTestForListener` pass with `ServerXdsClient` instead of the current `XdsClientImpl2` ? Without that we'll be breaking server side.

`XdsClientImplTestForListener` has been ported to `ServerXdsClientTest`. `XdsClientImpl2` and its tests (including `XdsClientImplTestForListener`) would be deleted.

**Comment by sanjaypujare** [comment]
> `XdsClientImplTestForListener` has been ported to `ServerXdsClientTest`. `XdsClientImpl2` and its tests (including `XdsClientImplTestForListener`) would be deleted.

Oh, okay. I didn't notice that. May be the change was in the previous PR which escaped me. This looks good to me then.

**Review by sanjaypujare — APPROVED** [review]
LGTM

**Pull request merged**
