### PR TITLE
Update server to await termination in the main thread

### LINKED ISSUE #967: Update examples in light of daemon threads
At the very least, the hello world server example is broken, because it exits immediately. It needs a call to `server.awaitTerminated()`. This was caused by the swapping to daemon threads in 07a7279.

As [reported on StackOverflow](http://stackoverflow.com/questions/32439576/grpc-java-server-shuts-down-immediately).

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #967

### CODE REVIEW

**Comment by ejona86** [comment]
@carl-mastrangelo, LGTM, but this does not fix #967. Please verify the other examples as well; I know routeguide is also broken.

**Comment by carl-mastrangelo** [comment]
@ejona86  I updated the server, but I am not sure what needs to be done for the async clients in RouteGuideClient.  I *think* they are coming from the main thread, but I am not that familiar with the stubs.  PTAL.

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM. Note that checkstyle fails.

I think the routeguide async clients are fine, because of the `finishFuture.get()` lines. It could be useful to have a comment noting that we use daemon threads, but that can be later (post-beta).

**Comment by carl-mastrangelo** [comment]
I added some comments to the servers.

**Pull request merged**
