### PR TITLE
interop-testing: new stress test client command line options

### PR DESCRIPTION
**Pull request by ericgribkoff**
interop-testing: add command-line flags to stress test client to be consistent with interop client.

https://github.com/grpc/grpc/pull/8437 did this for C++

@makdharma FYI

### CODE REVIEW

**Comment by ericgribkoff** [comment]
This modifies the stress test client to accept the same --use_tls, --use_test_ca, and --server_host_override arguments as the interop client.

**Comment by dapengzhang0** [comment]
Is `--use_tls=true` a prerequisite for `--use_test_ca`?

**Comment by ericgribkoff** [comment]
@dapengzhang0 I'm not sure. It is not a prerequisite as far as `NettyChannelBuilder` is concerned. From a quick look at `NettyChannelBuilder`, it looks like setting the sslContext to use a fake cert will do nothing unless TLS is also enabled - but this is not enforced by any conditions in the code, or checked for by the existing interop client, for that matter.

**Comment by ericgribkoff** [comment]
@dapengzhang0 Letting `--use_test_ca=true` be set without requiring `--use_tls=true`, as is currently allowed, also somewhat simplifies writing integration tests: it's easy to envision an integration test suite that always sets '-use_test_ca=true` while toggling `--use_tls`. 

I think behavior of the stress test client and the interop client should be consistent with respect to these flags. If it makes sense to require `--use_tls=true` as a prerequisite, I suggest we do this change in a separate PR for both clients (and also look at the C++ interop client as well).

**Comment by dapengzhang0** [comment]
It's ok not to enforce `--use_tls=true` for `--use_test_ca`, but it could be nice if we document it in the Usage like `--use_test_ca=true|false       Whether to trust our fake CA. Only works with --use_tls=true`

**Pull request merged**
