### PR TITLE
core: add DoNotMock annotations

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by dapengzhang0** [comment]
@carl-mastrangelo That means if I use custom ClientInterceptor in my test, I can not mock a ClientInterceptor that returns a mock ClientCall?

**Comment by ejona86** [comment]
@dapengzhang0, yes, because that is prone to breaking in the future, since the mock won't pull in the default implementation of any new methods in `ClientCall`.

**Comment by carl-mastrangelo** [comment]
any other comments?

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

**Pull request merged**
