### PR TITLE
Update http to grpc mappings

### LINKED ISSUE #2264: Implement HTTP→gRPC status code mapping
As defined in grpc/grpc#4955. Please wait until PR is in before merging the code changes, although the PR has received general agreement ("but it's not official until it's official").

This is important to return useful gRPC status codes when proxies generate errors.

### PR DESCRIPTION
**Pull request by lukaszx0**
Based on the latest doc: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md

Closes #2264

### CODE REVIEW

**Comment by ejona86** [comment]
Oh, look, something I've forgotten about.

So I actually have this mostly implemented (now at https://github.com/ejona86/grpc-java/commit/84d4165274765ff7a95e11d70a272120e2154a3e), but it isn't as easy as it looks, because of the handling of OK in Http2ClientStream. I was considering whether it was better to just leave 200 == OK, or whether I could wrestle the logic into something sane.

**Comment by lukaszx0** [comment]
Ah sorry for stepping on your toes. I briefly looked at logic in client stream and it seemed okay. Closing then.

**Comment by ejona86** [comment]
@lukaszx0, if you want to take it over, that sounds good to me. The last I touched that commit was 3 weeks ago. It probably only needs an hour of my time, but I've been pressed for time and glad you'd be contributing. But I'm also fine with still doing it. If you're wanting the change, I can also try to get it done tomorrow.

If you just want something to pick up, you may look at issues labeled "bug", like #2270. It'd just be good to write a test.

**Comment by lukaszx0** [comment]
I have no need for it at the moment. Was just going through issues and wanted to quickly fix that. Your commit looks more comprehensive, feel free to finish it up.

**Pull request closed without merging**
