### PR TITLE
Cleanup of NettyClientTransportTest.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 this is a pretty easy one.

**Comment by ejona86** [comment]
How are you able to rename GoAwayClosedStreamException without any other changes?

**Comment by nmittler** [comment]
I'm actually not sure where that change came from ... it's `GoAwayClosedStreamException.java` in my client :/

**Comment by nmittler** [comment]
BTW, I rebased against your latest changes for tls.

**Comment by nmittler** [comment]
@ejona86 sorted out the file rename issue.  PTAL.

**Comment by ejona86** [comment]
@nmittler LGTM

**Comment by nmittler** [comment]
cherry-picked as 9a6ded5

**Pull request closed without merging**
