### PR TITLE
netty,okhttp: handle unresolved proxy addresses (backport to v1.7.x)

### PR DESCRIPTION
**Pull request by ericgribkoff**
Backport of #3789, albeit modified to the pre-ProxyDetector implementation

### CODE REVIEW

**Comment by ejona86** [comment]
Did we decide this was unnecessary?

**Comment by ericgribkoff** [comment]
The channel builder changes are unnecessary (and wrong for Netty); the null check in OkHttpClientTransport still looks useful, as the proxy address can be unresolved and the existing code can throw an NPE. Should I revert the channel builder changes and continue with the backport?

**Comment by ejona86** [comment]
That sounds fine, but revert Netty change as a separate commit (otherwise it'll be far to hard to notice the difference from master)

**Comment by ericgribkoff** [comment]
The incorrect ChannelBuilder changes are reverted. PTAL

**Pull request merged**
