### PR TITLE
Added dependency of googleapis common protos.

### LINKED ISSUE #4356: Increment rest endpoint for health.proto
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Using gRPC 1.9.0

### What did you expect to see?
If it were possible to implement the health.proto service as REST interface too, it would minimize the duplication and generation of protofiles when using together with the repository of gRPC-gateway( https://github.com/grpc-ecosystem/grpc-gateway).

### PR DESCRIPTION
**Pull request by iaguera**
- Added go lang package.
  - http informations on health proto file.

Closes #4356

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @iaguera isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @iaguera isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by iaguera** [comment]
I'll close this PR, i will investigate more about the build fail tests.

**Comment by iaguera** [comment]
@ejona86 Thanks!! will help me a lot!

**Pull request closed without merging**
