### PR TITLE
xds: Build third-party protos in separate build step

### PR DESCRIPTION
**Pull request by ejona86**
This dramatically shortens build time, even for full builds. A full
assemble of xds on my laptop goes from 1m 46s to 33s at least because
errorprone is disabled for the protos.

CC @sergiitk

### CODE REVIEW

**Comment by sergiitk** [comment]
Looks like the build still fails

```
> Task :extractIncludeProto FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':extractIncludeProto'.
> Could not resolve all files for configuration ':compileProtoPath'.
   > Could not find :unspecified:.
     Required by:
         project : > io.grpc:grpc-xds:1.48.0-SNAPSHOT
```

**Comment by ejona86** [comment]
Ugh. This is going to take some more to deal with the dependencies used by thirdparty build but not by xds itself. I could workaround that by using compileOnly dependencies in thirdparty and re-declaring them for xds, but...

Part of this trouble is made worse because the dependencies are sort of wonky to begin with to deal with shadow.

**Comment by ejona86** [comment]
Ugh. OOMing.

**Review by YifeiZhuang — APPROVED** [review]
Thank you for the optimization and simplification, it looks great!

**Pull request merged**
