### PR TITLE
Release v1.64.1

### PR DESCRIPTION
**Pull request by larry-safran**
DO NOT MERGE

### CODE REVIEW

**Review by sergiitk — CHANGES_REQUESTED** [review]
Commit `Rollback PR 11319 so that we have a clean start` shouldn't be in the release PR. Could it be that something went wrong with synchronizing your local branch?

**Comment by larry-safran** [comment]
What went wrong was that I sent you a PR a couple of days ago to update the version numbers which you approved and I merged.  Eric finally pointed out that for patch releases we should completely skip over the branching section where I was trying to make something comparable to what we did for minor releases.

**Review by sergiitk — APPROVED** [review]
Ah. My apologies. You mean #11318 and #11319, right? Was I wrong approving them? Because they should've been broken into separate commits, right? I think I get it now.

**Comment by larry-safran** [comment]
Merged this, so can't release it and switching to 1.64.2

**Pull request merged**
