### PR TITLE
Changed the mutual TLS ServerInterceptor code

### PR DESCRIPTION
**Pull request by isheff**
Changed the mutual TLS ServerInterceptor code so that it actually compiles.
Fixes issue https://github.com/grpc/grpc-java/issues/4905 .

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @isheff isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by isheff** [comment]
@thelinuxfoundation I have just signed the CLA.

**Comment by zpencer** [comment]
It is taking more effort than I thought to get the mutual auth example running with the test certs:  https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/helloworldtls

I'll get this PR merged as a short term fix to correct the docs.

**Comment by ejona86** [comment]
Closing due to inactivity.

**Pull request closed without merging**
