### PR TITLE
examples: Provide Maven and Gradle build files

### LINKED ISSUE #1414: add pom.xml to examples/
Currently there is only gradle build.gralde file.  Add pom.xml please!

### PR DESCRIPTION
**Pull request by ejona86**
The examples are no longer part of the normal build, although they are
built with Travis. The examples now include their own copy of the gradle
wrapper to ease usage from IDEs which can now properly detect the
correct version of gradle to use.

The build files were generated using "gradle init" and "mvn
archetype:generate" and then modified following our README.

Fixes #1414

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
Where did GreeterGrpc go?

**Comment by ejona86** [comment]
It's no longer being checked in, as we would encourage our users to do. The examples are completely separate builds from our main build now, since that's what users would need. If building from master, you would need to `gradle install' grpc before trying to build the example. If building from a release tag, no action is necessary first.

**Comment by ejona86** [comment]
@carl-mastrangelo, friendly ping.

**Comment by carl-mastrangelo** [comment]
LGTM

**Pull request merged**
