### PR TITLE
Bump protobuf-gradle-plugin from 0.8.1 to latest 0.8.3

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
Huh, with this change the InProcessTest fails due to unimplementedService 
 java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<CANCELLED> ... but only on Mac OS X but passes on Linux - how is this possible?

**Comment by carl-mastrangelo** [comment]
retest this please

**Comment by carl-mastrangelo** [comment]
ok to test

**Comment by ejona86** [comment]
@vorburger, the failure was due to a race in in-process transport: #3571.

**Comment by ejona86** [comment]
okay to test

**Comment by ejona86** [comment]
It looks like there's other place that also need the change:
```
$ git grep protobuf-gradle-plugin
README.md:    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.1'
android-interop-testing/build.gradle:        classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.1"
build.gradle:                protobuf_plugin: 'com.google.protobuf:protobuf-gradle-plugin:0.8.1',
examples/android/helloworld/build.gradle:        classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.1"
examples/android/routeguide/build.gradle:        classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.1"
```

**Comment by ejona86** [comment]
I fixed this and the additional locations in #3962.

**Pull request closed without merging**
