### PR TITLE
Make the change on status effective.

### PR DESCRIPTION
**Pull request by madongfly**
@ejona86 Please take a look, thanks!

### CODE REVIEW

**Comment by ejona86** [comment]
@madongfly LGTM. Note that the colon should have been on the next line ("the break comes before the symbol").

**Comment by ejona86** [comment]
@madongfly, could you also backport this to 0.7.x?

**Comment by madongfly** [comment]
@ejona86, backport only this PR or with your PR that adds description for UNKNOWN?

**Comment by ejona86** [comment]
@madongfly, I think both should happen. I was only requesting to do this one. If you wouldn't mind doing both, that would be great.

**Pull request merged**
