### PR TITLE
Use the stable v1 reflection API

### PR DESCRIPTION
**Pull request by Kernald**

### CODE REVIEW

**Comment by Kernald** [comment]
Looks like Gradle still uses the `v1alpha`, but I can't figure out how it pulls it. Doesn't it use https://github.com/grpc/grpc-proto/tree/master/grpc/reflection as well?

**Comment by voidzcy** [comment]
> Looks like Gradle still uses the `v1alpha`, but I can't figure out how it pulls it. Doesn't it use https://github.com/grpc/grpc-proto/tree/master/grpc/reflection as well?

Unfortunately, the proto is not directly pulled from grpc-proto. We made [our own copy](https://github.com/grpc/grpc-java/blob/master/services/src/main/proto/grpc/reflection/v1alpha/reflection.proto) in grpc-services.

Btw, what's the context of making this change? Both C++ and Go are using v1alpha reflection, is there a discussion going on for dropping v1alpha?

**Comment by Kernald** [comment]
> > Looks like Gradle still uses the `v1alpha`, but I can't figure out how it pulls it. Doesn't it use https://github.com/grpc/grpc-proto/tree/master/grpc/reflection as well?
> 
> Unfortunately, the proto is not directly pulled from grpc-proto. We made [our own copy](https://github.com/grpc/grpc-java/blob/master/services/src/main/proto/grpc/reflection/v1alpha/reflection.proto) in grpc-services.

Ha thanks for the pointer, I'll update it if we decide to go forward - see the rest of this comment.

> Btw, what's the context of making this change? Both C++ and Go are using v1alpha reflection, is there a discussion going on for dropping v1alpha?

I assumed this code had been written back when the reflection API wasn't stable, and had never been migrated. The Bazel targets used as a dependency at the moment are [marked as deprecated](https://github.com/grpc/grpc-proto/blob/14b8f3e1181ed6fc484a033d3cbb912e7e7c6750/BUILD.bazel#L161-L167), which results in a warning. Given that the only differences are some comments, without any semantical change, as far as I can tell, it seemed like a safe update.

**Comment by voidzcy** [comment]
> I assumed this code had been written back when the reflection API wasn't stable, and had never been migrated. The Bazel targets used as a dependency at the moment are [marked as deprecated](https://github.com/grpc/grpc-proto/blob/14b8f3e1181ed6fc484a033d3cbb912e7e7c6750/BUILD.bazel#L161-L167), which results in a warning. Given that the only differences are some comments, without any semantical change as far as I can tell, it seemed like a safe update.

Yeah, this is something we should have cleaned up long ago, but never bubbled up to the top of the priority list. We could doo it, but if we doo, we should do it in all languages. Otherwise, it breaks interoperability. We'd need to figure out a backward compatibility plan here, client like grpc_cli depend on it. 

/cc @ejona86

**Comment by ejona86** [comment]
> Unfortunately, the proto is not directly pulled from grpc-proto

We use a copy for Gradle using [sync-protos.sh](https://github.com/grpc/grpc-java/blob/master/buildscripts/sync-protos.sh), but Bazel build does use the grpc-proto repo directly. https://github.com/grpc/grpc-java/blob/134e9cbc422e7f47bda777c30cfd91e79d5a64d1/repositories.bzl#L127-L132

Yeah. I think we'll need to support both versions at the same time. I expect it to be quite painful to get languages on v1 cross-language, as several others are probably also exposing the v1alpha gRPC service from non-v1alpha-labeled language-specific APIs.

**Comment by Kernald** [comment]
I just found this: https://github.com/grpc/proposal/blob/master/A15-promote-reflection.md which describes a plan to go forward with this. I definitely not have the bandwidth to follow that through, I didn't realise the implications here.

**Pull request closed without merging**
