### PR TITLE
Release v1.66.0

### PR DESCRIPTION
**Pull request by kannanjgithub**

### CODE REVIEW

**Comment by kannanjgithub** [comment]
I had 2 commits in my fork's master when I raised [this PR](https://github.com/grpc/grpc-java/compare/master...kannanjgithub:grpc-java:master). They are showing up as conflicts. Hopefully we can Accept all from the release branch's changes.

**Comment by ejona86** [comment]
What is this? The history is mangled and you say "release 1.66.0" but one of the versions is 1.67.0, and it has random unreviewed changes like "If TlsContext specifies to use System root certs, don't set the trust". You say "this PR" but I don't know how to interpret the link.

**Comment by ejona86** [comment]
I don't understand the objective, because 1.66.0 is scheduled for next week.

**Comment by kannanjgithub** [comment]
I realized when following https://github.com/grpc/grpc-java/blob/master/RELEASING.md#tagging-the-release by skipped step 5 and raised the PR after step 4, so the -SNAPSHOT that got dropped from the version files did not get re-added in the version files MODULE.bazel etc.

The other random changes were actually committed in my other branch [https://github.com/grpc/grpc-java/compare/master...kannanjgithub:grpc-java:xdsusesystemroot, I'm surprised how they appear in ](https://github.com/grpc/grpc-java/commit/5433ebb797f9afaa81a54654cbaef1e42550546b) I'm not sure how they ended up in my newly created branch release-1.66.x.

Will fix both tomorrow.

**Comment by kannanjgithub** [comment]
In the [steps for tagging the release](https://github.com/grpc/grpc-java/blob/master/RELEASING.md#tagging-the-release) starting from upstream v1.66.0 ([MODULE.bazel](https://github.com/grpc/grpc-java/blob/v1.66.x/MODULE.bazel)) we have 
`version = "1.67.0-SNAPSHOT",  # CURRENT_GRPC_VERSION`
in that file done when branching the release.

Now in step 4 in Tagging the release we remove -SNAPSHOT, so it becomes
`version = "1.67.0", # CURRENT_GRPC_VERSION`

but after step 5 it becomes 
`version = "1.66.1-SNAPSHOT",  # CURRENT_GRPC_VERSION`

because it just replaces the pattern [0-9]\+\.[0-9]\+\.[0-9] and doesn't use the matched groups in the replacement text, but just uses $MAJOR.$MINOR.$((PATCH+1)) 
Is this intentional?

**Comment by ejona86** [comment]
> Now in step 4 in Tagging the release we remove -SNAPSHOT

That happens in the release branch, which still has 1.66.0-SNAPSHOT... but I see the release branch does have the 1.67.0 commit in it. That was a mistake. We need to revert that commit on the release branch.

**Comment by kannanjgithub** [comment]
> > Now in step 4 in Tagging the release we remove -SNAPSHOT
> 
> That happens in the release branch, which still has 1.66.0-SNAPSHOT... but I see the release branch does have the 1.67.0 commit in it. That was a mistake. We need to revert that commit on the release branch.

I have just raised a [revert commit](https://github.com/grpc/grpc-java/pull/11428) for v1.66.0. A related question - In v1.65.0 I [see version = "0"](https://github.com/grpc/grpc-java/blob/v1.65.x/MODULE.bazel#L5) . Do we not do that anymore?

I also observe now that in the Branching the Release [step 4](https://github.com/grpc/grpc-java/blob/master/RELEASING.md#branching-the-release) the ^ in the regex for Start development cycle seems to be a problem because there are leading whitespaces in the git log and the git log command with the grep returns empty.

I will drop this release-v1.66.0 branch and start from new.

**Comment by kannanjgithub** [comment]
> > > Now in step 4 in Tagging the release we remove -SNAPSHOT
> > 
> > 
> > That happens in the release branch, which still has 1.66.0-SNAPSHOT... but I see the release branch does have the 1.67.0 commit in it. That was a mistake. We need to revert that commit on the release branch.
> 
> I have just raised a [revert commit](https://github.com/grpc/grpc-java/pull/11428) for v1.66.0. A related question - In v1.65.0 I [see version = "0"](https://github.com/grpc/grpc-java/blob/v1.65.x/MODULE.bazel#L5) . Do we not do that anymore?
> 
> I also observe now that in the Branching the Release [step 4](https://github.com/grpc/grpc-java/blob/master/RELEASING.md#branching-the-release) the $ in the regex for Start development cycle seems to be a problem because there is some text following: Start 1.67.0 development cycle (#11416) and git log returns empty.
> 
> I will drop this release-v1.66.0 branch and start from new.

@ejona86 Not sure if you saw this reply because I deleted the PR, so tagging you here. Could the regex be the reason the commit hash for 1.67 not used when creating the release branch, rather than it getting created too soon?

**Comment by ejona86** [comment]
> In v1.65.0 I [see version = "0"](https://github.com/grpc/grpc-java/blob/v1.65.x/MODULE.bazel#L5) . Do we not do that anymore?

"anymore"? I don't understand the question. You're talking about an older version and asking if we stopped doing something that we had never done before? We have _started_ setting the version in 1.66. See https://github.com/grpc/grpc-java/commit/36e687f9d9da447c5f94dd95c149fd462c3fb7f1

**Pull request closed without merging**
