### PR TITLE
deps: update protobuf to 3.15.8

### PR DESCRIPTION
**Pull request by elharo**
@ejona86

### CODE REVIEW

**Review by ejona86 — COMMENTED** [review]
There's still a lot of references in `examples/`. I'll note that it is correct _not_ to change README.md, as we change that as part of the release process.

**Comment by voidzcy** [comment]
Can we wait and upgrade to 3.16 directly, which includes the recent change for [non-copy read of immutable buffers](https://github.com/protocolbuffers/protobuf/blob/76188afb94c985c859823b6a64ff88bed3be667b/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L3529-L3542)?

Well, I am still fine to just upgrade to 3.15.8. Since the zeroo-copy marshaller will be implemented by the application, it can still pull in protobuf-3.16.

**Comment by ejona86** [comment]
> Can we wait and upgrade to 3.16 directly, which includes the recent change for non-copy read of immutable buffers?

I'd prefer that we just update twice, just because it reduces risk in further delaying _any_ upgrade and risk that we discover an issue when upgrading. And as you also mention, it isn't essential that _grpc_ upgrades to the newer protobuf immediately; our users are free to use a newer version of protobuf the day it is released.

**Comment by elharo** [comment]
It is likely that this is the version of protobuf that the LTS version of Beam will depend on. In any case, we should upgrade at least this far. We can go to 3.16 when it's available.

**Pull request closed without merging**
