### PR TITLE
Set arbitrary NameResolver attributes via ManagedChannelBuilder

### PR DESCRIPTION
**Pull request by elandau**
It is currently not possible to pass in any custom parameters to a NameResolver. This change adds the ability to specify NameResolver parameters on the base ManagedChannelBuilder.

Note that the current API delegates the responsibility for setting such parameters to the concrete ManagedChannelBuilder (such as NettyChannelBuilder). This is not ideal as it assumes a NameResolver's configuration is dependent on the Channel type. For backwards compatibility I kept the existing AbstractManagedChannelImplBuilder#getNameResolverParams() and added a new ManagedChannelBuilder#nameResolverParams() method for setting NameResolver parameters. Parameters from both mechanisms are merged when build() is called with parameters passed to nameResolverParams() taking precedence. This is probably not an ideal solution either as the override behavior isn't always clear but this is a good starting point for a discussion.

### CODE REVIEW

**Comment by ejona86** [comment]
okay to test

**Comment by zhangkun83** [comment]
The NameResolver params is intended to be a way for channel builder controlling the behavior of NameResolver. For now it's only used for default ports. The user can decide whether the transport enables TLS or not, then the channel builder would derive the default port  (443 or 80) out of this decision and communicate it to NameResolver. If we didn't have such mechanism, the user would have to configure the default port by him/herself, which isn't very friendly.

IIUC, you are going to use pass the core affinity to your LoadBalancer. I would instead just let user to configure it through the LoadBalancer directly.

**Comment by elandau** [comment]
We've actually switched to passing in any affinity to the NameResolver through the query parameters of targetUri.  However, there still remains the issue of passing in a typed default affinity (per #1512) to the LoadBalancer itself.  Passing parameters to the LoadBalancer.Factory is not possible through the existing API.  It can be done by creating a separate LoadBalancer.Factory, as you describe, for each channel but that seems contrary to the intent of having a LoadBalancer.Factory that can be shared among multiple channels.  Would it make sense to overload ManagedChannelBuilder#loadBalancerFactory with a variant that includes an Attributes object to be passed into LoadBalancer.Factory#newLoadBalancer?

```java   
public abstract class ManagedChannelBuilder<T extends ManagedChannelBuilder<T>> {
  public abstract T loadBalancerFactory(LoadBalancer.Factory loadBalancerFactory, Attributes attributes); 
}
```

LoadBalancer.Factory would be changed to,

```java
public abstract static class Factory {
   public abstract <T> LoadBalancer<T> newLoadBalancer(String serviceName, Attributes attributes, TransportManager<T> tm);
}
```

**Comment by zhangkun83** [comment]
It makes sense. I would go with the style you use in this PR, that we add a `loadBalancerParams()` method on `ManagedChannelBuilder`, so that the load balancer and its params can be set independently.

I wonder if it makes sense to just define one `Attributes` params used by both `NameResolver` and `LoadBalancer`, instead of two separate params. It will work like `Context`, where we put everything in a big map, and every party looks for the contents it is interested in. It would useful for cases where multiple parties are interested in the same param. However, going down that route, I can't resist the idea of putting other options from `ManagedChannelBuilder`, e.g., `usePlaintext()` on this big params container. @nmittler @ejona86 any thoughts?

**Comment by elandau** [comment]
+1  I really like the idea of having a single place for all configuration for the specific reasons you mention.

While on the topic of configuration in general have you given any thought to allowing configuration to update dynamically after the channel has been created.  I don't want to conflate the discussion here so let me know if you'd like me to expand here or open up a separate issue.

**Comment by zhangkun83** [comment]
No, we haven't seen any demand for changing configurations on the fly. Feel free to open a separate issue.

**Comment by elandau** [comment]
I updated the PR to include LoadBalancer parameters as well.

**Comment by zhangkun83** [comment]
I had a conversation with @ejona86. He had different opinions and I agreed with him.

 He doesn't think it's necessary to pass params from `ManagedChannelBuilder` to `LoadBalancyer.Factory`. He prefers constructing separate factories with different configurations. This means the factories will no longer be singletons, but it doesn't seem to be a problem.

As for `NameResolver`, he envisioned that any necessary params could be passed as URI parameters in the target string.

So this means there would be no change to the API. We can still make changes when we have to, but it sounds that your requirements can be met without changes. @elandau does it sound reasonable to you?

**Comment by elandau** [comment]
Works for me.  We already moved on to using URI parameters so I suppose we don't need this.  Thanks for reviewing the PR.

**Pull request closed without merging**
