### PR TITLE
Don't include test files in main sources

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @swankjesse isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by ericgribkoff** [comment]
@swankjesse Are you able to sign the new CLA? We can't accept the PR without it. Thanks!

**Comment by ejona86** [comment]
@swankjesse, friendly ping for CLA

**Comment by ejona86** [comment]
Closing in favor of #4794. Thanks for noticing!

**Pull request closed without merging**
