### PR TITLE
Moving a few common utilities to GrpcUtil.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by madongfly** [comment]
Fixes #736

**Comment by madongfly** [comment]
LGTM.

But I see in some of the files the constants are static imported, in other files are referenced as GrpcUtil.XXX, should we keep a consistent style?

**Comment by carl-mastrangelo** [comment]
Static imports makes call sites cleaner, it should be preferred.  Since neither style is wrong, I didn't comment on it in the PR.

**Comment by nmittler** [comment]
Yeah, I agree with @carl-mastrangelo.  It's harmless and improves readability.

Cherry-picked as e2f88fa

**Pull request closed without merging**
