### PR TITLE
netty: update to 4.1.3.Final

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by buchgr** [comment]
oh wait. that release contains the thread factory changes already.

**Comment by buchgr** [comment]
Fixes https://github.com/grpc/grpc-java/issues/2041, https://github.com/grpc/grpc-java/issues/2015, https://github.com/grpc/grpc-java/issues/2014

**Comment by ejona86** [comment]
No changes are necessary for thread group. The default is still to use the sticky thread group.

**Comment by ejona86** [comment]
@buchgr LGTM, assuming changes to Utils.java are undone.

**Comment by buchgr** [comment]
@ejona86 I assume this should also be backported?

**Comment by ejona86** [comment]
Yes, please.

**Comment by buchgr** [comment]
cherry-picked into v1.0.x as 30c2b0eda023e05e431d7bc2cb977c958dab958e

**Pull request merged**
