### PR TITLE
Rename Call to ClientCall

### LINKED ISSUE #23: Figure out what names we want for Client Foos vs Server Foos
We have Call on both Client and Server. When adding the server, we chose ServerCall as the name of the server-side Call, and discussed renaming the client-side to ClientCall. ClientInterceptor was named based on this idea. However, the rename hasn't happened yet and now some have suggested having the Client names simply lack "Client" (so it would remain "Call"). It seems it has simply been too long since the original discussion for us to remember what was decided.

We need to decide to either prefix Client with Client and Server with Server or only prefix Server with Server. After the decision, whatever needs fixing needs to be fixed.

Note that in the transport we must have ClientStream prefixed with Client, since Stream is a shared interface between Client and Server.

### PR DESCRIPTION
**Pull request by zhangkun83**
Resolves #23 

Other classes are already following the convention that ``ClientFoo`` for
client-side, and ``ServerFoo`` for server-side. ``Call`` has been the black
sheep of the family.

- ``Call`` -> ``ClientCall``
- ``Calls`` -> ``ClientCalls``
- ``ForwardingCall*`` -> ``ForwardingClientCall*``

@ejona86 @nmittler

### CODE REVIEW

**Comment by nmittler** [comment]
@zhangkun83 @ejona86 I'm wondering if we should hold off on this until the dust settles from Wolfgang's API work ... I suspect some of this might change again as a result.  WDYT?

**Comment by wrwg** [comment]
I opened #510 to illustrate what @nmittler means. For certain, if we move
away from Call, the nice match Call/Callable wouldn't work anymore. As
Callable would be quite present in the programming style I've in mind,
ClientCallable as a substitute would really not be nice. On the other hand,
there is some concern about using Callable as name anyway, because it
conflicts with the same in java.util.concurrent.

Independent of that, I feel renaming this to "ClientCall" might be wrong.
The primary "orientation" of the name Call already seems to be client side.
Client usage of a service is typically 20x more than server usage, so
making the name for server side long and keeping it short and intuitive on
client side may be justified. So instead of promoting Call to ClientCall,
what about removing the Client prefix elsewhere, and get it consistent this
way?

-- 
*W*olf*g*an*g*

**Comment by zhangkun83** [comment]
> Independent of that, I feel renaming this to "ClientCall" might be wrong.
The primary "orientation" of the name Call already seems to be client side.
Client usage of a service is typically 20x more than server usage, so
making the name for server side long and keeping it short and intuitive on
client side may be justified. So instead of promoting Call to ClientCall,
what about removing the Client prefix elsewhere, and get it consistent this
way?

I don't feel it right to rename "ClientInterceptor" to "Interceptor", and "ClientStream" to "Stream" either, because "interceptor" and "stream" don't have the natural orientation that "call" does. On the other hand,
although "call" as a verb has outward orientation, when you use as a noun to refer to the activity on both sides, you usually decorate it, e.g., "outgoing call" and "incoming call". If we want to emphasize the out-going aspect of "Call" and introduce "Callable", maybe we should rename "ServerCall" to something like "Work" because out-going "Call" is not compatible with "Server".

**Comment by ejona86** [comment]
@zhangkun83, what is the plan for MethodDescriptor?

**Comment by zhangkun83** [comment]
> what is the plan for MethodDescriptor?

Since we are going to treat ``MethodDescriptor`` as a static representation of the method definition from IDL, I would keep it as-is, change ``ServerMethodDefinition`` to contain a ``MethodDescriptor``, and delete ``Method``.

**Comment by ejona86** [comment]
@zhangkun83, concerning `MethodDescriptor`, that sounds like a great direction. That is best done later, but I did want to know which way things were going.

**Comment by ejona86** [comment]
@zhangkun83 LGTM

**Comment by nmittler** [comment]
@ejona86 @zhangkun83 so should we hold off on this pending further discussion in #510?  Is there a pressing need for this change?

**Comment by ejona86** [comment]
I think @zhangkun83 provided the main argument I would have: simply omitting "Client" doesn't really work because there are multiple classes that need the specificity. I'm also not sold on the name `Callable` given its frequent use from j.u.concurrent. I also don't see any problem with calling it ClientCallable, again, for the reason highlighted by @zhangkun83; we are definitely using Call as a noun and definitely using it on both client-side and server-side.

**Comment by ejona86** [comment]
I'd also like to mention that every API change is pressing, since the more time goes by the harder it is to make the change and the less time we have to discuss the change. To have any hope of being semi-API-stable next quarter things like this need to be resolved sooner than later.

**Comment by nmittler** [comment]
Right, so I think that's why we should have a broader discussion about the API changes now and get agreement on which way to proceed. I'd rather just change the API once if possible.

**Comment by zhangkun83** [comment]
The name collision with ``java.util.concurrent.Callable`` sounds a deal breaker to me. IMO we need a different name for @wrwg 's new callable class, and this would reduce, if not eliminate, the demand for ``Call``.

**Comment by nmittler** [comment]
Let's carry the discussion over to #510

**Comment by ejona86** [comment]
@nmittler, I think both @zhangkun83 and I don't think @wrwg's API impacts this PR. I wouldn't know what to discuss in #510. Moving the discussion to #23 could work, but it doesn't seem to be much better than just discussing here.

**Comment by wrwg** [comment]
Thanks @nmittler. I'm fine if you move forward with this PR, for the sake
of decoupling this discussion. We can have it again once we are looking at
a PR for Callable.

-- 
*W*olf*g*an*g*

**Pull request merged**
