### PR TITLE
Version bumps for v0.12.0

### PR DESCRIPTION
**Pull request by ejona86**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
Update examples/android/app/build.gradle ?

**Comment by ejona86** [comment]
@carl-mastrangelo, yes. Done. And rebased.

**Comment by carl-mastrangelo** [comment]
@ejona86 I might be mistaken, but I think you need to rebase both commits, otherwise the android examples in the deployed jar won't have the change, right?

**Comment by ejona86** [comment]
@carl-mastrangelo, I think I did. I made two commits and 'fixup'd them into the two pre-existing commits. Double check?

**Comment by carl-mastrangelo** [comment]
LGTM

**Pull request merged**
