### PR TITLE
servlet: Remove unused dependency on grpc-util in tests

### PR DESCRIPTION
**Pull request by ejona86**
Also convert to testFixtures, like we did elsewhere.

### CODE REVIEW

**Comment by sanjaypujare** [comment]
I see failures in the CI

```
> 
/grpc-java/servlet/src/jettyTest/java/io/grpc/servlet/GrpcServletSmokeTest.java:19: error: package com.google.common.truth does not exist
import static com.google.common.truth.Truth.assertThat;
                                     ^
/grpc-java/servlet/src/jettyTest/java/io/grpc/servlet/GrpcServletSmokeTest.java:19: error: static import only from classes and interfaces
import static com.google.common.truth.Truth.assertThat;
^
> Task :grpc-servlet:compileJettyTestJava
/grpc-java/servlet/src/jettyTest/java/io/grpc/servlet/GrpcServletSmokeTest.java:22: error: package com.google.protobuf does not exist
import com.google.protobuf.ByteString;
                          ^
/grpc-java/servlet/src/jettyTest/java/io/grpc/servlet/GrpcServletSmokeTest.java:26: error: package io.grpc.testing does not exist
import io.grpc.testing.GrpcCleanupRule;
                      ^
/grpc-java/servlet/src/jettyTest/java/io/grpc/servlet/GrpcServletSmokeTest.java:55: error: cannot find symbol
  public final GrpcCleanupRule cleanupRule = new GrpcCleanupRule();
               ^
  symbol:   class GrpcCleanupRule
  location: class GrpcServletSmokeTest
```

**Comment by ejona86** [comment]
I didn't see it locally because it only builds on Java 11 and I'm on Java 8. It took me a pretty long time to notice the missing comma that prevented grpc-testing from being a dependency.

**Review by sanjaypujare — APPROVED** [review]
Lgtm

**Comment by sanjaypujare** [comment]
> I didn't see it locally because it only builds on Java 11 and I'm on Java 8. It took me a pretty long time to notice the missing comma that prevented grpc-testing from being a dependency.

yeah, that’s what I was wondering… didn’t realize the java8 vs java11 difference

**Pull request merged**
