### PR TITLE
NameResolver now emits a List<EquivalentAddressGroup> instead of List<ResolvedServerInfo>

### PR DESCRIPTION
**Pull request by jhspaybar**

### CODE REVIEW

**Comment by jhspaybar** [comment]
This is part 1 of what was discussed in part here https://github.com/grpc/grpc-java/pull/1803 .  Based on some concerns raised by @zhangkun83 I actually ended up emitting a `List<EquivalentAddressGroup>`, but I have the `DnsNameResolver` emit just a single `EquivalentAddressGroup` for all endpoints returned from the DNS query.  This may be enough to alleviate concerns around pick first behavior weirdness.  If not, I've also changed the `SimpleLoadBalancer` to concatenate all `EquivalentAddressGroup` into a single `EquivalentAddressGroup`.  My hope actually with the way I've implemented this is that we can rely on the `DnsNameResolver` to emit a single `EquivalentAddressGroup` and then make the `SimpleLoadBalancer` use a round robin load balancing strategy.  This will at least maintain current behavior for people using defaults(dns+simple lb).  This may not be desirable though if there are other things expecting a pick first lb and not using a name resolver that only emits a single `EquivalentAddressGroup`.  There's definitely still more discussion to happen here, but I'm hoping this is closer to a point where the `NameResolver` best knows what addresses are truly equivalent, and can decide if this means they're equivalent on a per resolution basis, or on a per server basis inside resolution(as we prefer with our EurekaNameResolver).

**Comment by jhspaybar** [comment]
Whoops, I'll fix the broken tests in the grpclb package shortly.

**Comment by jhspaybar** [comment]
After having looked a bit at the c language load balancing, I guess it does make sense to leave behind the `SimpleLoadBalancer` possibly renamed as `PickFirstLoadBalancer` and then make a `RoundRobinLoadBalancer` as well.  Lets stay focused here I guess on the `List<EquivalentAddressGroup>` change and see if that makes sense by itself.

**Comment by jhspaybar** [comment]
After more digging on the tests, the root issue is that `EquivalentAddressGroup` in this new change looks at the `List<ResolvedServerInfo>` and `ResolvedServerInfo` has an equals method that just does reference equality.  Changing that would require adding equals to `ResolvedServerInfo` and Attributes which may not be desirable.  Another option is just not to have a `List<ResolvedServerInfo>` in the `EquivalentAddressGroup` and just keep the `List<SocketAddress>` as it was.  The downside of this is that there is no longer the possibility to have `Attributes` on each `ResolvedServerInfo` in the `Listener.onUpdate(...)` method, however you still do get 1 set of `Attributes` passed as the second argument of `Listener.onUpdate(...)`.  Long story short, I'd love to hear some feedback and find out how you think I should progress here.

**Comment by zhangkun83** [comment]
The attributes are only useful for the `LoadBalancer`, thus they should only be passed on the `NameResolver->LoadBalancer` path, but not on the `LoadBalancer->TransportManager` path. 

`EquivalentAddressGroup` should remain unchanged because it's on the latter path.

For the former path, we probably need a different type. `List<List<ResolvedServerInfo>>` should work. Although it doesn't look as nice as `List<EquivalentAddressGroup>`, I think it's acceptable. We needed `EquivalentAddressGroup` instead of `List<SocketAddress>` because it's used in multiple places in channel implementation thus it's better to have a dedicated type on which we can define its semantics. It's not the case of `List<ResolvedServerInfo>` as it only appears on `NameResolver.Listener.onUpdate()` and we can simply define the semantics on this method.

@ejona86 WDYT?

**Comment by carl-mastrangelo** [comment]
@jhspaybar  Would you mind updating the commit message to match the format of other recent commits?   Something like:

core: emit equivalence groups instead of server info during name resolution.

**Comment by jhspaybar** [comment]
@zhangkun83 a `List<List<ResolvedServerInfo>>` sounds like a good idea in the `NameResolver`.  Is documenting that the internal Lists should be considered equivalent from the perspective of the `NameResolver` but that a load balancer could choose to ignore the suggestion enough and recombine enough?

@carl-mastrangelo will do!  I'll have to force push some changes and squash my commits anyways, so I'll tweak the message.

**Comment by zhangkun83** [comment]
>  a `List<List<ResolvedServerInfo>>` sounds like a good idea in the NameResolver. Is documenting that the internal Lists should be considered equivalent from the perspective of the NameResolver but that a load balancer could choose to ignore the suggestion enough and recombine enough?

Yes, exactly.

**Comment by jhspaybar** [comment]
I'm going to continue this over here https://github.com/grpc/grpc-java/pull/1890 .  It was quicked to just make a new branch and start from fresh again.

**Pull request closed without merging**
