### PR TITLE
census: update opencensus library to 0.28.1

### LINKED ISSUE #6928: OpenCensus 0.26.0 update
Can we update OpenCensus to 0.26.0 from the current 0.24.0? 

if not, what needs to be fixed before we can proceed?

### PR DESCRIPTION
**Pull request by gfelbing**
# Update OpenCensus to 0.28.1

## Problem

The most recent update of OpenCensus contains a breaking change, namely making ContextUtils package private: https://github.com/census-instrumentation/opencensus-java/commit/f8ea9bb4107eddb34324d9baf74737da470f4294#diff-3e846235e5a45651f4f79c6c7b4a325fe1b33a8e75ace3c188dd6104bd3e6dfa

Our project depends on opencensus as well as on grpc-java. 
Unfortunately, we cannot update opencensus in our build as it would update the transitive dependency causing runtime errors due to that breaking change.

## Solution

Updating OpenCensus to recent version, fixing the issue with the breaking change.

The call to ContextUtils.getValue can be replaced by `Tracing.getTracer().getCurrentSpan()`, as it calls `ContextUtils.getValue(Context.current());` under the hood yielding the same behavior

Fixes 

- #6928 
- https://github.com/census-instrumentation/opencensus-java/issues/2069

### CODE REVIEW

**Comment by gfelbing** [comment]
@jsuereth removes the breaking change in https://github.com/census-instrumentation/opencensus-java/pull/2072. 
Still, the ContextUtils will remain deprecated, suggesting to use the ContextHandleUtils.

**Comment by ejona86** [comment]
I'd have to dig a bit to confirm this change will work even if the gRPC context is not being used. But upgrading now to 0.28.1 will further propagate that broken Census release. I think we'll want to wait for a fixed release and then fix the API call. (But we can have this ready for once the Census release is available.)

**Comment by ejona86** [comment]
CC @voidzcy

**Comment by voidzcy** [comment]
Shouldn't this just be a no-op migration from `ContextUtils` to `ContextHandleUtils`?

**Comment by ejona86** [comment]
CC @ericgribkoff

**Comment by larry-safran** [comment]
This has become irrelevant since grpc is now using version 0.31.0

**Pull request closed without merging**
