### PR TITLE
Upgrade Netty to 4.1.100.Final

### PR DESCRIPTION
**Pull request by ozooxo**
Upgrade Netty to `4.1.100.Final` to fix the recent `io.netty:netty-codec-http2` DoS vulnerability -- https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-5953332

`io.netty:netty-codec-http2` is a dependency of `io.grpc:grpc-netty`.
```
$ gradle dependencies

+--- io.grpc:grpc-netty:1.58.0
|    +--- io.netty:netty-codec-http2:4.1.93.Final -> 4.1.97.Final (*)
```

I reported the issue in https://github.com/grpc/grpc-java/issues/10617 as well.

### CODE REVIEW

**Comment by hs-ye** [comment]
Just bumping this as this is also coming up in our security scans as a vulnerability, sooner we can get this in the better!

**Comment by ejona86** [comment]
A few other files need to be adjusted. For an example: https://github.com/grpc/grpc-java/commit/88b3484a602336b6688ca943d29b033c127dc533

For the table, say it'll be in 1.60.x. If I backport this, I'll update it to include the proper patch release.

**Comment by ejona86** [comment]
(The delay was me running some internal tests.)

**Comment by rgugliel-da** [comment]
Do you have an estimate about the delivery date of the next version that will include this fix?
Thanks!

**Comment by raihans8379** [comment]
Hello! Just adding onto the queue of folks wondering about the ETA on this.
Thank you!

**Comment by ejona86** [comment]
This is neither here nor there for Rapid Reset. See https://github.com/grpc/grpc-java/issues/10617#issuecomment-1781998806 .

**Comment by ejona86** [comment]
I've created #10648 which has the other necessary changes.

**Pull request closed without merging**
