### PR TITLE
#9179 - allow selecting jakarta/javax Generated annotation

### PR DESCRIPTION
**Pull request by alexanderankin**

### CODE REVIEW

**Comment by alexanderankin** [comment]
Dear Maintainers and gRPC/java communities

"At least 1 approving review is required by reviewers with write access. " (sad_trombone.wav)

cc: #9179 - this is a green checkmark addressing a concern in that issue.

**Comment by alexanderankin** [comment]
I see based on https://github.com/grpc/grpc-java/issues/1621#issuecomment-1399049068 that this project is not terminally averse to jakarta api's, but only in this instance, so maybe this increases the chances something like this will be accepted to lessen the pain while deliberation seems to continue in the linked issue.

**Comment by ejona86** [comment]
We really don't want the jakarta annotation. Based on https://github.com/grpc/grpc-java/issues/9179#issuecomment-1948805063 , you could have an option `javax=false` that just removes the annotation without replacing it with anything. In the future, if that causes problem, we can add a `io.grpc.stub.annotations.Generated` as the javax replacement.

**Comment by alexanderankin** [comment]
closing in favor of #10927 and hopefully a future one to add jakarta back on there

**Pull request closed without merging**
