### PR TITLE
Remove Dummy LB, use RoundRobin by default

### PR DESCRIPTION
**Pull request by lukaszx0**
Now, that we have RoundRobin implementation I think we can get rid of dummy version?

### CODE REVIEW

**Comment by zhangkun83** [comment]
Dummy is still useful for cases where NameResolver returns more than one address group, but you don't want load-balancing.

**Comment by lukaszx0** [comment]
That's true, however by default, the `NameResolver` implementation will be DNS based which always returns one address group so if somebody will be providing custom impl of it, I think it's fair to assume and expect that they'll also either provide a custom LB impl or be fully aware of how the default RoundRobin implementation behaves.

I personally don't think there's much value in keeping it but I can see the potential use case you mentioned. I do think though, that if we want to keep it, it shouldn't be the default one or at least we should rename it to `PickFirstLoadBalancer`.

**Comment by zhangkun83** [comment]
PickFirstLoadBalancer sounds fine, while I am not convinced RR should be promoted to be default. Pick-first is a safer default, compared with RR which has a potential of creating multiple connections. Also pick-first is desirable in mobile.

**Comment by lukaszx0** [comment]
Fair enough. Closing this one in favour of https://github.com/grpc/grpc-java/pull/2191

**Pull request closed without merging**
