### PR TITLE
netty: bump to 4.1.24-Final

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
@ejona86  didn't realize 24 was out.  updating

**Comment by ejona86** [comment]
Is this a time to update netty_tcnative as well?

**Comment by carl-mastrangelo** [comment]
Thanks @ejona86 I'll merge once the internal import works.

**Comment by carl-mastrangelo** [comment]
also added netty_tcnative

**Pull request merged**
