### PR TITLE
Renaming AUTH_README to SECURITY_README

### PR DESCRIPTION
**Pull request by nmittler**
The doc discusses TLS as well as auth, so "AUTH" doesn't seem quite right.

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
Maybe just "SECURITY.md"?

**Comment by nmittler** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
@nmittler LGTM. Don't forget to change the commit message, now that the filename is different.

**Comment by nmittler** [comment]
cherry-picked as 2483009

**Pull request closed without merging**
