### PR TITLE
core: fix a race in InProcessTransport

### LINKED ISSUE #3571: InProcessTest is flaky
https://travis-ci.org/grpc/grpc-java/jobs/286166891
```
:grpc-interop-testing:checkstyleTest
:grpc-interop-testing:test
io.grpc.testing.integration.InProcessTest > statusCodeAndMessage FAILED
    java.lang.AssertionError: expected:<UNKNOWN> but was:<CANCELLED>
```

Also on: https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4421/console
```
:grpc-interop-testing:test
io.grpc.testing.integration.InProcessTest > unimplementedService FAILED
    java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<CANCELLED>
```

### PR DESCRIPTION
**Pull request by dapengzhang0**
Resolves #3571 

In `InProcessTransport.InProcessStream.InProcessServerStream#close(Status status, Metadata trailers)`:
`clientStream.serverClosed` must happen before `clientStreamListener.closed`, otherwise `clientStreamListener.closed` can trigger `clientStream.cancel` (see code in `ClientCalls.blockingUnaryCall`), which may race with `clientStream.serverClosed` as both are calling `internalCancel()`.

### CODE REVIEW

**Comment by dapengzhang0** [comment]
Jenkins, retest this please

**Comment by ejona86** [comment]
Everything in the description of this PR should be in the commit message.

**Comment by ejona86** [comment]
Err... I guess since there's a comment in the code, only the "resolves" should also be included in the commit message.

**Comment by dapengzhang0** [comment]
Jenkins, retest this please

**Comment by ejona86** [comment]
Why is the test in AbstractInteropTest? If it's not a inprocess-specific test, then it would seem like a AbstractTransportTest test.

**Comment by dapengzhang0** [comment]
@ejona86 It is a twist of  `statusCodeAndMessage` which is in `AbstractInteropTest`, and it is checking whether _`ServerStatsTrace`_ is as expected. `AbstractTransportTest` seems more emphasize on the _client_ transport.

**Comment by ejona86** [comment]
`statusCodeAndMessage` is in `AbstractInteropTest` because it is [defined as an interop test](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#status_code_and_message). That is, it is testing that a client and a server are compatible. I've spoken to Kun about removing most of the `assertStatsTrace()`s from the interop tests because it is abusive and `AbstractTransportTest` already has checks for most such cases. We'd just leave 1-2 tests as integration with Census tests, and we would have them be independent of any cross-language interop test (such as `statusCodeAndMessage`).

Since this is a local-only issue it doesn't really belong as an interop test unless it is convenient for other reasons (like we need Census). We have the [same check](https://github.com/grpc/grpc-java/blob/8edead0/testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java#L774) (or maybe [this other test](https://github.com/grpc/grpc-java/blob/8edead0/testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java#L942)) in `AbstractTransportTest`. Also, with AbstractInteropTest I'd expect that we wouldn't need any latches since we can run on the transport's thread.

**Comment by dapengzhang0** [comment]
I'm not sure how with `AbstractInteropTest` we wouldn't need any latches. The test I was writing is testing RPC, it must go through `ClientCallImpl.ClientStreamListenerImpl`, whereas most of the tests in `AbstractInteropTest` use a fake `ClientStreamListener` (either `AbstractInteropTest.ClientStreamListenerBase` or a mock). Actually what I'm testing is the interaction between `ClientCallImpl.ClientStreamListenerImpl` (which shouldn't be faked) and transport.

**Pull request merged**
