### PR TITLE
Adding s390x support to grpc-java

### PR DESCRIPTION
**Pull request by Nayana-ibm**
Adding support for s390x .
Please review

### CODE REVIEW

**Comment by dapengzhang0** [comment]
@ejona86 Why CLA checker isn't showing up?

**Comment by ejona86** [comment]
@dapengzhang0, good question... I had hoped closing and reopening would fix it, but it didn't. Since it is a service I also can't see if the webhooks are being delivered. I'm pinging some people.

**Comment by dankohn** [comment]
We're checking on the status. Cc @jpalmerLinuxFoundation

**Comment by jpalmerLinuxFoundation** [comment]
> @ejona86 Why CLA checker isn't showing up?

Can I get access to review the settings on the integrations tab?  @ejona86

**Comment by dealako** [comment]
We identified the issue with the EasyCLA application processing this specific PR request.  We are working on a solution.

**Comment by ejona86** [comment]
A bug has apparently been fixed in EasyCLA, but I think we will need to wait until Wednesday for a new release to be deployed.

**Comment by Nayana-ibm** [comment]
@ejona86 Please let me know when this PR gets merged

**Comment by jpalmerLinuxFoundation** [comment]
Fix not yet deployed to production

**Comment by dealako** [comment]
User `snalkar` doesn't appear to be a valid GitHub user. Was this user removed/deleted after the commit and PR were submitted? EasyCLA was unable to lookup this user ID within GitHub.

**Comment by ejona86** [comment]
@dealako  `snalkar` isn't the github user. `Nayana-ibm` is the github user.

**Comment by dealako** [comment]
@ejona86 well, from the GitHub commit, it says `snalkar`:

**Comment by Nayana-ibm** [comment]
@ejona86 Github commit also needs to be done by github user Nayana-ibm?

**Comment by dealako** [comment]
Regardless, I'm going to introduce a workaround in EasyCLA as we were relying on GitHub to acquire the user's GH id.

**Comment by ejona86** [comment]
@dealako, the commit uses an email address. My commits use `ejona@google.com` for example, but my github id is `ejona86`. And that works fine. This would be the case ~100% of the time.

**Comment by ejona86** [comment]
@dealako, I think you are barking up the wrong tree. For example, consider my PR #6224 

```
$ curl -s -XGET https://api.github.com/repos/grpc/grpc-java/git/commits/c5c7755d3fe9d84ec2d87e277a49ea15a3e9cba6
...
  "author": {
    "name": "Eric Anderson",
    "email": "ejona@google.com",
    "date": "2019-10-01T16:03:43Z"
  },
  "committer": {
    "name": "Eric Anderson",
    "email": "ejona@google.com",
    "date": "2019-10-01T19:57:08Z"
  },
...
```

And yet the easycla status was correct on the PR. That author and committer name is the "name" of the author in normal email form. In the commit it has "Eric Anderson <ejona@google.com>".

**Comment by dealako** [comment]
@ejona86 thanks for the helpful feedback - I'm working on the logic that matches the commit author details, what we can additionally lookup/match from GitHub, and what matches the EasyCLA signature records.  We did have an issue when looking up a GitHub user by grabbing the commit author name, using the resulting GitHub numeric ID from their profile details, and using that for our initial EasyCLA search.

**Comment by ejona86** [comment]
> grabbing the commit author name

The commit author name is useless for easycla. It is an arbitrary string. It can be helpful to humans reading it, but it is useless for a machine.

**Comment by jpalmerLinuxFoundation** [comment]
It looks like the check ran, thanks @dealako

**Comment by ejona86** [comment]
@Nayana-ibm, the CLA bot is now working. Go ahead and go through the process.

**Comment by Nayana-ibm** [comment]
Raised  https://github.com/grpc/grpc-java/pull/6241 with correct commit user

**Pull request closed without merging**
