### PR TITLE
Changing license to Apache v2.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Implements #2745.

### CODE REVIEW

**Comment by ejona86** [comment]
Why were the various `gradle-wrapper.properties` files changed? That breaks the build.

**Comment by ejona86** [comment]
There's a lot of suspicious modifications. TODO comments removed from java_generator.cpp and checkstyle.xml modified mid-comment. benchmarks/README.md has paragraph deleted. All of them include `//`, so I think something is broken with the rewriting script.

**Comment by carl-mastrangelo** [comment]
@nicolasnoble Would you mind changing the commit message to match the project style?  Something like:

"all: change licence to Apache 2"

**Comment by carl-mastrangelo** [comment]
Closing in favor of #3047

**Pull request closed without merging**
