### PR TITLE
Commit ReconnectServiceGrpc.java generated by current codegen.

### LINKED ISSUE #849: Travis fails due to un-run codegen
https://travis-ci.org/grpc/grpc-java/builds/76536465
```
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
#
no changes added to commit (use "git add" and/or "git commit -a")
Error Working directory is not clean. Forget to commit generated files?
```

The issue seems caused by an incomplete rebase with #826. The modified code-generated file just needs to be committed.

### PR DESCRIPTION
**Pull request by zhangkun83**
Resolves #849

### CODE REVIEW

**Comment by madongfly** [comment]
Hmm how can grpc-protobuf:test be failed by this PR?

**Comment by zhangkun83** [comment]
It can't be caused by this PR. I cannot reproduce it locally. @ejona86 can we add ``--stacktrace`` to the gradle command line in travis?

**Comment by madongfly** [comment]
@zhangkun83, Seems it failed pretty frequently, I filed #859 for it.

LGTM

**Comment by ejona86** [comment]
@zhangkun83 LGTM

**Comment by ejona86** [comment]
@zhangkun83, we could add `--stacktrace`, but it wouldn't help in this case. The process is getting killed; there is no exception. Also, `--stacktrace` only helps from gradle-related exceptions; it wouldn't help with a junit exception.

**Comment by madongfly** [comment]
Can this be checked in now? thanks!

**Comment by zhangkun83** [comment]
It's already included in 9f7cb80108861694b35d5afb7ac5bbbf93a2d15e

**Pull request closed without merging**
