### PR TITLE
Release 1.51.2

### PR DESCRIPTION
**Pull request by YifeiZhuang**

### CODE REVIEW

**Review by ejona86 — COMMENTED** [review]
Looks like there is a mix of versions: 1.51.2 and 1.51.3

**Review by ejona86 — COMMENTED** [review]
Maybe the branch was already busted? This sort of thing is the thing that is confusing me:
```
-    version = "1.51.1" // CURRENT_GRPC_VERSION
+    version = "1.51.3-SNAPSHOT" // CURRENT_GRPC_VERSION
```

**Comment by YifeiZhuang** [comment]
> Maybe the branch was already busted? This sort of thing is the thing that is confusing me:
> 
> ```
> -    version = "1.51.1" // CURRENT_GRPC_VERSION
> +    version = "1.51.3-SNAPSHOT" // CURRENT_GRPC_VERSION
> ```

looks previous release readme is incorrect #9753

**Comment by ejona86** [comment]
The README looks fine to me, but the build files never saw the bump to the SNAPSHOT version. And it does look wrong in that PR. So I think this one does look appropriate then.

CC @larry-safran

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
This release turned out to be busted, because the `build.gradle` still had 1.51.1 at the tag.

**Pull request merged**
