### PR TITLE
Add a Builder to Call Options

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Call Options is likely going to be gaining 2 or 3 more options very soon, all of which are optional.  In order to handle this upcoming complexity, I have made Call Options use the builder pattern for construction and lock down constructor access.

Minor benefits include all CallOptions fields will be final, no need to change the constructor signature, and withFoo style cloning still works right.  This also provides a single place to do checking on parameter construction. (such as if we want to throw on a negative deadline).

Also, equals and hashCode have been added for convenience.

### CODE REVIEW

**Comment by ejona86** [comment]
NACK, we explicitly decided not to do a builder, because it was more annoying for a user, especially since we expect very few call options to be mutated on a per-call basis per call-site.

**Comment by ejona86** [comment]
> Call Options is likely going to be gaining 2 or 3 more options very soon, all of which are optional. In order to handle this upcoming complexity

What complexity is that? Each additional option should only require adding a getter (1 line of method body), a with (3 lines of method body), and 1 line in the copy constructor.

> I have made Call Options use the builder pattern for construction and lock down constructor access.

The constructors look equally locked-down. They were private before and are still private.

> This also provides a single place to do checking on parameter construction. (such as if we want to throw on a negative deadline).

Why couldn't that have been done in the with method before?

**Comment by carl-mastrangelo** [comment]
@nmittler @zhangkun83 @madongfly 

Could I get a second opinion?  Setters are an extremely common pattern in Google3, and are well understood.

**Comment by zhangkun83** [comment]
I agree with @ejona86. I am in fact the one who removed the builder from `AbstractStub` in favor of the `withFoo()` pattern (#660).

Builder pattern has a benefit in terms of memory allocation when multiple options (>2) are set at a time, which doesn't seem likely at this moment. Even if we do usually set >2 options at the same time, I wouldn't say 2 or 3 extra more object allocations per call would make an observable difference.

The con of the builder pattern is more obvious -- two more extra method calls is a direct usability impact; more complexity in the interface and implementation of, not only `CallOptions`, but also `AbstractStub` (they'd better be consistent).

**Comment by nmittler** [comment]
@carl-mastrangelo I would think we would either use a builder or have `withFoo()` methods, but not both. I personally don't have a strong opinion as to which is better ... both have their pros and cons.  @ejona86 and @zhangkun83 have already gone the route of using `withFoo()` and I'm not sure it's worth the effort of changing it at this point ... unless you're prepared for a very long discussion :).

**Pull request closed without merging**
