### PR TITLE
add 'oraclejdk10' to Travis build matrix

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @sullis isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by sullis** [comment]
I submitted my CLA (via email) last night.

**Comment by carl-mastrangelo** [comment]
@sullis merged, Thanks!

**Comment by ejona86** [comment]
We just discovered this was still running with Java 8, because we had a jdk_switcher line elsewhere in the .travis.yml. That is getting cleaned up in #4652, but is uncovering problems with both Java 9 and Java 10. Java 9 looks pretty easy to fix. But we may need to remove the Java 10 line until we have time to make it work.

**Pull request merged**
