### PR TITLE
all: fix build with errorprone 2.18

### PR DESCRIPTION
**Pull request by benjaminp**
errorprone cannot be updated past 2.10 because later versions do not support Java 8.

Fixes https://github.com/grpc/grpc-java/issues/9916.

### CODE REVIEW

**Comment by temawi** [comment]
Unfortunately we can't upgrade errorprone as grpc-java still needs to support Java 8, which newer errorprone versions do not support. You can see the build failure complain about class file versions...

**Comment by benjaminp** [comment]
Can I change the the PR to simply include the errorprone fixes rather than the upgrade? It's very helpful if grpc-java is included in a project using a recent errorprone version.

(Maybe it would make sense to only run errorprone on Java 11?)

**Comment by ejona86** [comment]
> Can I change the the PR to simply include the errorprone fixes rather than the upgrade?

Yeah, that'd be fine.

We regularly run on Java 8 (not because it is good, but because it is supported), so I'd probably want it still to work on Java 11. I guess it wouldn't be that hard to choose which version to use based on the Java version that Gradle is running with. That'd obviously have benefits to you, but it isn't mandatory.

**Review by temawi — APPROVED** [review]

**Comment by temawi** [comment]
@benjaminp - thank you!

**Pull request merged**
