### PR TITLE
Keep our certs used for testing the same with their internal version

### PR DESCRIPTION
**Pull request by madongfly**
@ejona86, please take a look, thanks!

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
The certs for this have problems interacting with the Go Interop test.  Can you try running the entire grpc interop suite before submitting this?  It should be as simple as:

tools/run_tests/run_interop_tests.py -s all -l all --http2_interop --use_docker

**Comment by madongfly** [comment]
@carl-mastrangelo, the story is that Julien updated a bunch of files internally, but he only changed the server1.pem in grpc-java githu, which I believe is the cert used to test with Go.

But our MOE configuration is actually syncing all of files in this directory, so we need to port all of the internal changes here to make MOE happy.

I'm willing to run the test, but do you know how to specify it run the teat with this PR?

**Comment by carl-mastrangelo** [comment]
If you checkout grpc at the same level as grpc-java and run the tests from
that directory, it will use the correct branch.

**Comment by madongfly** [comment]
@carl-mastrangelo, the test failed by other language issues when `-l all` was specified, so I ended up with runging `tools/run_tests/run_interop_tests.py -s go -l java --http2_interop --use_docker` and the test passed:
```
simonma@simonma-linux:~/github/grpc$ tools/run_tests/run_interop_tests.py -s go -l java --http2_interop --use_docker
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_go [time=31.6sec; retries=0;0]
PASSED: build_docker_http2 [time=42.0sec; retries=0;0]
PASSED: build_docker_java [time=43.2sec; retries=0;0]
SUCCESS: All docker images built successfully.
START: interop_server_go
PASSED: cloud_to_cloud:java:go_server:large_unary [time=3.7sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:empty_unary [time=4.1sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:empty_stream [time=5.0sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:ping_pong [time=5.4sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:server_streaming [time=5.5sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:cancel_after_begin [time=5.6sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:client_streaming [time=5.7sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:cancel_after_first_response [time=5.8sec; retries=0;0]
PASSED: cloud_to_cloud:java:go_server:timeout_on_sleeping_server [time=6.2sec; retries=0;0]
SUCCESS: All tests passed
Mako template is not installed. Skipping HTML report generation.
Removing docker image grpc_interop_go:9b4305ed-c088-473b-96ac-8e67da92d390
Removing docker image grpc_interop_java:441d3fc7-dc45-46f2-a4c4-3fb722030f23
Removing docker image grpc_interop_http2:b35bed3d-5ea5-4e25-ad9a-820f10ef9731
```

**Comment by carl-mastrangelo** [comment]
@madongfly LGTM

**Pull request merged**
