### PR TITLE
Make checkstyle failures fatal, and fix last issues

### LINKED ISSUE #211: Fix checkstyle warnings for examples
Making example methods private would be easiest, but them being public seemed to be useful in http://www.useopen.net/blog/2015/rpc-performance.html .

getFeature() is also overloaded, and doesn't look like it should be, given that the two methods have different semantics.

### PR DESCRIPTION
**Pull request by ejona86**
Resolves #211

### CODE REVIEW

**Comment by ejona86** [comment]
How do we feel about checkstyles being fatal? I think some may find it annoying, but I also wonder how well people will notice warnings.

**Comment by buchgr** [comment]
+1, since we don't want commits with checkstyle issues I don't see an issue with making them fatal.

**Comment by justinsb** [comment]
As someone external working on a PR, I am fine with them being errors.

I had a list of violations, which I had overlooked, so having the build fail would be helpful.

That said, this will slow down initial development, so if we can have this only be an error in Travis (and have Travis reporting status on all PRs), that might be best.

**Comment by ejona86** [comment]
PTAL. People who want it to fail while developing can set checkstyle.ignoreFailure=false in their ~/.gradle/gradle.properties. I've set it for myself. If many of us are setting it to be a build failure, we can change the default to false and people who are annoyed can set it to true in their gradle.properties. Travis is set up with ignoreFailures=false, so it should fail the CI build if someone failed to notice the warning.

**Comment by nmittler** [comment]
LGTM

**Comment by justinsb** [comment]
This works wonderfully - thanks!  LGTM

**Pull request merged**
