### PR TITLE
Documentation - bump versions

### PR DESCRIPTION
**Pull request by eripe970**
Update versions from 1.13.1 to 1.13.2.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @eripe970 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by eripe970** [comment]
CLA fixed

**Comment by eripe970** [comment]
😀

**Comment by carl-mastrangelo** [comment]
@eripe970 Thanks, merged!

**Pull request merged**
