### PR TITLE
stub: improve error message for Client/ServerCalls 

### PR DESCRIPTION
**Pull request by creamsoup**
when StreamObserver.onNext is called after the stream is terminated.
resolves #5656

### CODE REVIEW

**Comment by creamsoup** [comment]
fyi. the force push is just rebase of current master for travis to pick up the java8 fix.

**Comment by ejona86** [comment]
FYI: Travis builds from a merge commit of this PR to master. So just going to travis and hitting the "rebuild" button should have been enough.

**Comment by creamsoup** [comment]
i actually tried the rebuild couple times, but it didn't work (config from the ui looked staled). i'll try again next time.

**Comment by ejona86** [comment]
Okay. That's fine. I'm not bothered by the rebase to address this, I was just noting it shouldn't be necessary since that would be easier in the future.

**Pull request merged**
