### PR TITLE
Update readme to specify 1.24.1

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by creamsoup** [comment]
@elharo  thanks for doing this. i forget to update this (I should have cherry-picked [this commit](https://github.com/grpc/grpc-java/commit/36a7527a2e124a462200c0df134977c874d866b1))

can you also update `cronet/README.md` and `documentation/android-channel-builder.md`?

**Comment by creamsoup** [comment]
@elharo , the PR is not mergable, can you fix this? 
it would be nice if we can merge this before the 1.25.x release (possibly today)

**Comment by elharo** [comment]
I can't see any conflicts in my local client or on Github. I'm not sure why it's complaining.

**Comment by elharo** [comment]
OK, git still confuses me but pushing from a different machine seems to have resolved the merge issues.

**Pull request merged**
