### PR TITLE
netty,okhttp: CONNECT proxy support

### LINKED ISSUE #2193: Support forward proxies with CONNECT
Is there a way to specify a proxy connection when specifying the host and port with the NettyChannelBuilder? 

``` java
originChannel = NettyChannelBuilder.forAddress(host, port)
                          .sslContext(GrpcSslContexts.forClient().build())
                          .build();
```

### PR DESCRIPTION
**Pull request by ejona86**
In Netty, the closeFuture() closes too early to be helpful, which is
very unfortunate. We'll just need to rely on the handlers to report the
shutdown without any back-up. The handlers error handling has matured,
so maybe this is okay.

WORKING: two tests fail; both are flaky

This is being sent out now because a backport will be based on it.

Fixes #2193

CC: @lukaszx0

### CODE REVIEW

**Comment by lukaszx0** [comment]
Hey @googlebot, it's cool. He can merge my commit ;)

**Comment by chandradeepak** [comment]
any update on when this pull request will be available ?

**Comment by ejona86** [comment]
@chandradeepak, a simplified form is in v1.0.3. This one is going to take longer to stabilize. I'm thinking I won't try to push it into 1.1.

**Comment by chandradeepak** [comment]
thank you . we will try that version .

**Comment by ejona86** [comment]
Most of this has made it into master via other PRs. The main thing remaining is fixing error handling during negotiators to fix the unhelpful "Connection broken while performing protocol negotiation" and similar. Rebasing this branch of master had zero merge conflicts and just left a "netty: Handle shutdown and failures during negotiator". Work was still ongoing with fixing tests there, although it seems like the problematic tests are now passing.

All that is to say, I'm going to close this PR but not delete my branch yet. Once the test issues are resolved I'll open an new PR.

**Pull request closed without merging**
