### PR TITLE
Default client connection window to 1MiB.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by ejona86** [comment]
The documentation in the builder says that it defaults to Http2CodecUtil#DEFAULT_WINDOW_SIZE. That should be updated.

LGTM

**Comment by nmittler** [comment]
Cherry-picked into master.

**Comment by a11r** [comment]
Not sure we need to change the default right away. There is some benefit in staying with the HTTP/2 defaults. As long as there are hooks to configure these window sizes, apps that need larger windows can still get them.

**Comment by ejona86** [comment]
Using 1MB is the current behavior of the C core:
https://github.com/grpc/grpc/blob/f70259f74f7784013338eee9bdefaef341a757f7/src/core/transport/chttp2_transport.c#L60

**Comment by a11r** [comment]
Sorry missed that. Thanks for the ptr. {Please ignore my objection.

**Comment by iamqizhao** [comment]
What is the reason to change the default?

**Comment by ejona86** [comment]
We are trying to improve throughput issues on high-bandwidth, high-latency links (high bandwidth-delay product).

**Pull request closed without merging**
