### PR TITLE
changed the netty-codec-http2 depdendency to released version

### PR DESCRIPTION
**Pull request by marky-mark**
* 4.1.0.Beta5
* available on maven central http://search.maven.org/#artifactdetails%7Cio.netty%7Cnetty-codec-http2%7C4.1.0.Beta5%7Cjar

### CODE REVIEW

**Comment by marky-mark** [comment]
I signed it!

**Comment by ejona86** [comment]
Could you also update the lib/netty submodule to the netty-4.1.0.Beta5 tag at the same time?

```
$ cd lib/netty
$ git fetch
$ git checkout netty-4.1.0.Beta5
$ cd ../..
$ git commit
```

**Comment by marky-mark** [comment]
Sure thing. Done.

**Comment by ejona86** [comment]
Cherry-picked as 589afef. Thanks!

**Pull request closed without merging**
