### PR TITLE
interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.39.x backport)

### PR DESCRIPTION
**Pull request by lidizheng**
Backports #8400 #8573 #8534 #8340 #8344 #8429 https://github.com/grpc/grpc-java/pull/8534 https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.

* [xds](http://sponge/b9dcd2d3-4db7-4d59-b4d6-4e776ca622d8)
* [xds_v3](http://sponge/eaf73ba6-1da5-4449-971c-ad30c7e50525)
* [xds_k8s_lb](http://sponge/0fee1bfa-eaeb-4951-a6f9-a44c86f80ae7)
* [xds_url_map](http://sponge/e2ec35cd-f220-4e92-8fbe-b1cd2eae3aac)

### CODE REVIEW

**Comment by lidizheng** [comment]
Retry test cases in xds-url-map failed because Retry is only supported after v1.39.x: https://github.com/grpc/grpc/blob/master/doc/grpc_xds_features.md

The Retry test cases require >v1.40.x for C++, Python, Java, and >v1.41.x for Go: https://github.com/grpc/grpc/blob/master/tools/run_tests/xds_k8s_test_driver/tests/url_map/retry_test.py#L69

This is expected. Ideally, we want to trigger the test in v1.39.x branch, which looks like `grpc/java/v1.39.x/branch/xds_url_map`. However, this job doesn't exist and depend on this PR to be merged.

**Comment by lidizheng** [comment]
Test re-triggered:

* [xds](http://sponge/daf51ffd-34a6-4571-906d-e78170ffae15)
* [xds_v3](http://sponge/3da51666-e807-4322-91a9-e95d87654f42)
* [xds_k8s_lb](http://sponge/c35e0423-fa42-4168-97e3-7f1af1286d9a)
* [xds_url_map](http://sponge/bc4dd7d1-1b12-409d-bcae-887bd7e74cea)

**Comment by ejona86** [comment]
https://github.com/grpc/grpc-java/pull/9202/commits/d068588b31f97358d801e18d34a72eba52acdd84 looks busted, as it doesn't resemble the master commit https://github.com/grpc/grpc-java/commit/8ac9a4e7bd651f1492d4376f4fc78643613bf8aa at all.

**Review by ejona86 — APPROVED** [review]

**Comment by lidizheng** [comment]
There is non-zero code changes, so re-triggering the xDS tests:

* [xds](http://sponge/9b623e40-7047-48a6-bd38-69373dbf42a5)
* [xds_v3](http://sponge/10db7007-8fbc-4dfe-ba54-063ffcc56225)
* [xds_k8s_lb](http://sponge/85189a5e-742a-4041-bf64-9259a51d90c5)
* [xds_url_map](http://sponge/7bae5997-c934-49ab-9eb9-4f5b9eb58071)

**Pull request merged**
