### PR TITLE
Upgrade to protobuf-3.0.0-beta-2 and protobuf-nano-3.0.0-alpha-5

### PR DESCRIPTION
**Pull request by zhangkun83**

### CODE REVIEW

**Comment by ejona86** [comment]
@zhangkun83 LGTM.

It looks like the windows build had some trouble :(

**Comment by ejona86** [comment]
https://github.com/google/protobuf/commit/673d32e0930bd87536da71b3bf1d0c6c3d098833

**Comment by zhangkun83** [comment]
Windows build is now passing. Travis is broken due to certificate issue with github when trying to download the protobuf release.
```
wget: /tmp/openssl-1.0.2d/lib/libcrypto.so.1.0.0: no version information available (required by wget)
wget: /tmp/openssl-1.0.2d/lib/libssl.so.1.0.0: no version information available (required by wget)
--2016-01-27 19:08:40--  https://github.com/google/protobuf/archive/v3.0.0-beta-2.tar.gz
Resolving github.com (github.com)... 192.30.252.129
Connecting to github.com (github.com)|192.30.252.129|:443... connected.
ERROR: cannot verify github.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA':
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
```

@ejona86 can you take a look?

**Comment by ejona86** [comment]
@zhangkun83, I know what is going wrong (and I think why we haven't seen it earlier). I'll investigate for a fix.

**Pull request closed without merging**
