### PR TITLE
Generate interface for each rpc method.

### PR DESCRIPTION
**Pull request by daicoden**
Makes class per rpc style implementations easier for the developer.

Issue #2446

### CODE REVIEW

**Comment by ejona86** [comment]
okay to test

**Comment by daicoden** [comment]
To use these interfaces in the stub class, MethodHandler would implement these methods instead of the the different ServerCall interfaces. I don't think *ImplBase can manage invoke based on how it's structured right now.

The reason I chose to do it this way was to have the MethodType information available in annotation processors. You can only read constants in annotation processors, and I can see that an interface extends ServerCalls.UnaryCall, but I can't get access to the MethodDescriptor instance to ask it the type.

However, I can live without that. I can change this PR to generate implementations for *ImplBase instead if you think that better.

The main motivation for this PR is to have some API for implementing per-class RPCs without having to use ServerCalls.X<ReqT,RespT>.

**Comment by ejona86** [comment]
It seems these changes would work well in a separate code generator. The interfaces are useless without an annotation system, and although other annotation systems could theoretically benefit from them as well it's unclear whether any actually will benefit. The interfaces also don't use the existing generated code nor does the existing generated code depend on the interfaces.

So I don't think we're likely to accept this at this point because it seems better served by a separate code generator. It seems like writing a generator for this case would be fairly straight-forward.

**Comment by daicoden** [comment]
Alright, thanks for the consideration :).

Is the vision for extending GRPC to be through protoc extensions? I got everything working by forking and modifying, but it felt nasty, but maybe I can look at chaining generators.

I would put a plug in for supporting GRPC extension through annotation processors, more meta information is required in the generated code to make it a reality. Reason being there's a ton to wrap your head around without adding another language layer, there's no java poet for writing the java classes, you have to switch how you do tests/ set up different harness. Just a lot of infra to bring in to maintain it.

**Comment by ejona86** [comment]
At present the gRPC plugin does not provide extension points. This is because: 1) in OSS there needs to be a canonical version of the proto; any extension points _must not_ be used in OSS, 2) we've not seen a strong case for them in gRPC; the cases we've seen for them work fine as a separate class.

I'd instead just write a plugin that assumes the grpc-java plugin has already run. Yes, it produces yet _another_ class, but such is life.

I'm not sure what you'd have to do to swap how you do tests. Unless you are talking about testing the generated code. For tests we've had good success with generating code as part of the test build process.

Yes, maintaining your own protoc plugin requires more infrastructure. You may consider writing the plugin [in Java](https://github.com/salesforce/grpc-java-contrib/tree/master/jprotoc) for easier maintenance. Unfortunately, writing it in Java does make some things harder, like learning the generated message name for a Protobuf message.

**Pull request closed without merging**
