### PR TITLE
buildscripts: add android-interop-test build (without runing test) in kokoro android

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by dapengzhang0** [comment]
Android Kokoro task is expected to fail before #5523 is fixed.

**Comment by dapengzhang0** [comment]
Android Kokoro (interop-test) build did fail as expected.

**Comment by dapengzhang0** [comment]
@TimvdLippe, Mockito 2 and Android plugin 3.3 still seem to have problem. With 'com.android.tools.build:gradle:3.3.0' or 'com.android.tools.build:gradle:3.3.2', and mockito 2.25.1, the build command 
```
gradlew app:transformClassesAndResourcesWithProguardForRelease
```

 fails with following warings:

```
Reading program jar [/usr/local/google/home/zdapeng/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.9.7/8fea78fea6449e1738b675cb155ce8422661e237/byte-buddy-1.9.7.jar] (filtered)
Warning: class [META-INF/versions/9/module-info.class] unexpectedly contains class [module-info]
Reading program jar [/usr/local/google/home/zdapeng/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.9.7/8e7d1b599f4943851ffea125fd9780e572727fc0/byte-buddy-agent-1.9.7.jar] (filtered)
Warning: class [META-INF/versions/9/module-info.class] unexpectedly contains class [module-info]
...
Warning: there were 2 classes in incorrectly named files.
         You should make sure all file names correspond to their class names.
         The directory hierarchies must correspond to the package hierarchies.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unexpectedclass)
         If you don't mind the mentioned classes not being written out,
         you could try your luck using the '-ignorewarnings' option.
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_2): destruction

> Task :app:transformClassesAndResourcesWithProguardForRelease FAILED

```

This seems a bug. Adding `-dontwarn module-info` and run the build command again, the above issue is passed but then it fails with
```
Warning: net.bytebuddy.agent.builder.ResettableClassFileTransformer: can't find superclass or interface java.lang.instrument.ClassFileTransformer
Warning: net.bytebuddy.dynamic.ClassFileLocator$AgentBased$ExtractionClassFileTransformer: can't find superclass or interface java.lang.instrument.ClassFileTransformer
Warning: net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Strategy$ClassRedefinitionTransformer: can't find superclass or interface java.lang.instrument.ClassFileTransformer
...
[A lot of Warnings]
...
Warning: there were 668 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
```

This still seems a bug. I have to apply the workaround https://github.com/mockito/mockito/issues/1511#issuecomment-449478456 to downgrade net.bytebuddy explicitly, and then the build could pass.

**Comment by TimvdLippe** [comment]
That is a Proguard bug (https://github.com/mockito/mockito/issues/1511#issuecomment-475673168): https://sourceforge.net/p/proguard/bugs/671/

I have heard from other teams that R8 has been working as intended: https://r8.googlesource.com/r8

**Comment by dapengzhang0** [comment]
@TimvdLippe Thanks a lot for your notice. Then what would be the best workaround now? Apply mockito/mockito#1511 (comment) ?

**Comment by TimvdLippe** [comment]
I would advise adopting R8 in favor of the (barely maintained) Proguard project.

**Pull request merged**
