### PR TITLE
Fix bugs and improvements found by static analyser

### PR DESCRIPTION
**Pull request by ejona86**
@carl-mastrangelo, FYI, this fixes a bug in my authority change

### CODE REVIEW

**Comment by ejona86** [comment]
@carl-mastrangelo, now with a test.

**Comment by carl-mastrangelo** [comment]
@ejona86 LGTM.

**Comment by adriancole** [comment]
not important, but which static analyzer did you use?

**Comment by ejona86** [comment]
@adriancole, these were caught by a google-internal one when syncing the code internally.

**Comment by adriancole** [comment]
ah ok. carry on :)

**Pull request merged**
