### PR TITLE
Stop using native maven_jar rule in grpc

### PR DESCRIPTION
**Pull request by dkelmer**
See https://github.com/bazelbuild/bazel/issues/6799 for more information

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @dkelmer isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by dkelmer** [comment]
Does Google have a corporate CLA for linuxfoundation or should I join as an individual?

**Comment by dkelmer** [comment]
I mailed this internally, so I'm closing the PR

**Comment by dkelmer** [comment]
Reopened and joined the google github org for the CLS

**Comment by dapengzhang0** [comment]
ping CLA

**Comment by ejona86** [comment]
Google has a corporate CLA.

@dkelmer, how was this generated? To get the licenses right it seems there was some tool.

**Comment by dkelmer** [comment]
I must admit that I manually googled the jars individually and copied the license information from maven central to the bzl file

**Comment by ejona86** [comment]
@dkelmer, oh, in that case that you for all the effort.

Have you gone through the process for the CLA? I think you need github to know associate your `@google.com` email address with your account and then use the "Sign up to contribute to this project as an employee" link at the CLA page. I don't think being part of the Google org on Github has anything to do with it.

**Comment by dkelmer** [comment]
ping CLA

**Comment by dkelmer** [comment]
> @dkelmer, oh, in that case thank you for all the effort.
You're welcome :) 

> Have you gone through the process for the CLA? I think you need github to know associate your `@google.com` email address with your account and then use the "Sign up to contribute to this project as an employee" link at the CLA page. I don't think being part of the Google org on Github has anything to do with it.
I think I just did it

**Comment by ejona86** [comment]
Yay! The CLA is happy. I forgot to trigger the Kokoro builds earlier. After they finish I'll merge.

**Comment by dkelmer** [comment]
Seems like kokoro passed :)

**Comment by ejona86** [comment]
@dkelmer, thank you!

**Pull request merged**
