### PR TITLE
Update opencensus to 0.11.0 and remove extra dependencies.

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @bogdandrutu isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @bogdandrutu isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by bogdandrutu** [comment]
I signed

**Comment by bogdandrutu** [comment]
I signed

**Comment by ejona86** [comment]
Thank you for this, and dealing with the exclusions and Blaze as well!

**Pull request merged**
