### PR TITLE
fixed typo in round robin factory name const

### PR DESCRIPTION
**Pull request by marcoferrer**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @marcoferrer isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by marcoferrer** [comment]
completed cla form

**Comment by carl-mastrangelo** [comment]
Fixes: #4598

**Comment by dapengzhang0** [comment]
LGTM

**Comment by dapengzhang0** [comment]
@marcoferrer, thank you for the fix!

**Pull request merged**
