### PR TITLE
all: add parameter name to checkNotNull

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
After debugging #2153, it would have been nice to know what the exact
parameter was that was null.  This change adds a name for each
checkNotNull (and tries to normalized on static imports in order to
shorten lines)

### CODE REVIEW

**Comment by ejona86** [comment]
:-/ Non-static usage is much higher than the static usage.

**Comment by zhangkun83** [comment]
LGTM

**Comment by carl-mastrangelo** [comment]
@ejona86, yeah, but java is super verbose already.  I like less code in general.

**Comment by ejona86** [comment]
Changing to the static is a personal preference, and you're actually changing the preference against what it predominantly is (and it used to be even stronger in favor of non-static, but you've already been changing things to static). You can argue that you like less verbosity and thus we should only use static import, but that seems like a weak argument when the code obviously disagrees with you, both internally and externally (as we've discussed in the past).

**Comment by pgrosu** [comment]
Though I also prefer non-static imports, the style guide seems to allow it:

https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing

**Comment by ejona86** [comment]
Static imports are fine. Non-static imports are fine. The style guide does not mandate either direction. And that is why I was saying it is a personal preference and so it seems strange to change all the code.

**Comment by pgrosu** [comment]
That's a fair point, though it's probably just for consistency across the code-base.  Refactoring if it can help will probably complete this task fairly quickly.

**Comment by carl-mastrangelo** [comment]
Static is my personal pref, but the reason I changed them is because I prefer uniformity.  If it would be okay, I would change all the Preconditions in the affected classes.  @ejona86 would that be okay?

**Comment by ejona86** [comment]
The code will never be fully uniform. The style guide helps code be uniform, but there will always be differences. This effectively makes using the static part of the style guide. I don't think it needs to be and trying to get agreement for things that don't matter is a waste of time. I'm willing to spend some time for quick agreement, but this is more beating a dead horse.

Carl, before your first commit there were a mere 9 usages of the static vs 107 of non-static, and you have slowly changed existing code to your preference. I feel like if you actually cared about uniformity you would have swapped to non-static, especially since non-static is still winning substantially.

**Comment by carl-mastrangelo** [comment]
Inside Google it is not so one sided.  I think there is a clear benefit here (less code on the page) so unless there is a strong reason not to, I am going to go forward.  Once the pattern is 100% consistent across gRPC java, I believe it will be self sustaining.

**Comment by pgrosu** [comment]
Carl, yes please go forward :)

**Comment by carl-mastrangelo** [comment]
@ejona86 I backed out the static imports, but I still think they should be preferred for Preconditions.

**Pull request merged**
