### PR TITLE
remove deprecated usage of usePlainText(boolean)

### PR DESCRIPTION
**Pull request by jorgheymans**

### CODE REVIEW

**Comment by jyane** [comment]
Deprecated are still remaining?

```
$ git grep 'usePlaintext(true)'
android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java:      channelBuilder.usePlaintext(true);
core/src/main/java/io/grpc/ManagedChannelBuilder.java:    return usePlaintext(true);
examples/android/clientcache/app/src/main/java/io/grpc/clientcacheexample/ClientCacheExampleActivity.java:        channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();
examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java:        channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();
examples/android/routeguide/app/src/main/java/io/grpc/routeguideexample/RouteGuideActivity.java:    channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();
examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java:        .usePlaintext(true)
examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java:        ManagedChannelBuilder.forAddress("localhost", server.getPort()).usePlaintext(true).build();
examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java:        ManagedChannelBuilder.forAddress("localhost", server.getPort()).usePlaintext(true).build();
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java:        .usePlaintext(true)
examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java:        .usePlaintext(true)
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java:        .usePlaintext(true)
examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java:        .usePlaintext(true)
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java:    this(ManagedChannelBuilder.forAddress(host, port).usePlaintext(true));
```

**Comment by jorgheymans** [comment]
Indeed i only looked in examples as that is where I found the first ones.
Happy to change all of them, let me know :)

**Comment by zpencer** [comment]
This clean up looks good to me, but it looks like the usages in `android` and `android-interop-testing` should be cleaned up too:
```
spencerfang@spencerfang-glaptop0:~/git/grpc-java$ ag 'useplaintext\(true\)'
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java
46:        .usePlaintext(true)

examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java
41:        .usePlaintext(true)

examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
40:        .usePlaintext(true)

examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java
66:        ManagedChannelBuilder.forAddress("localhost", server.getPort()).usePlaintext(true).build();

examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java
86:        ManagedChannelBuilder.forAddress("localhost", server.getPort()).usePlaintext(true).build();

examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java
47:        .usePlaintext(true)

examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
52:    this(ManagedChannelBuilder.forAddress(host, port).usePlaintext(true));

examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java
55:        .usePlaintext(true)

examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java
87:        channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();

examples/android/routeguide/app/src/main/java/io/grpc/routeguideexample/RouteGuideActivity.java
82:    channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();

examples/android/clientcache/app/src/main/java/io/grpc/clientcacheexample/ClientCacheExampleActivity.java
113:        channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();

core/src/main/java/io/grpc/ManagedChannelBuilder.java
185:    return usePlaintext(true);

android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java
67:      channelBuilder.usePlaintext(true);
```

**Comment by ejona86** [comment]
Let's not worry about `android-interop-testing` unless @jorgheymans just feels like updating it as well. Fixing `examples/android` would be good though, since that's also an example. @jorgheymans, if you don't have an android environment, just make the change ("blindly") and our CI will make sure it still compiles.

**Comment by jorgheymans** [comment]
"blindly" removed from both android-interop-testing and examples/android :-)

**Comment by zpencer** [comment]
@jorgheymans thank you for your contribution!

**Pull request merged**
