### PR TITLE
Simplifying usage of native transports.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
I'm not really wild about this change. I wouldn't want people to be using these APIs, which are now public.

**Comment by nmittler** [comment]
Err ... why not? Don't we want to encourage this on linux? Or is it because you want to hold off until Netty releases beta6?

**Comment by ejona86** [comment]
I don't like the API, and I'm not convinced it is necessary. It seems users of these classes should just depend on them if they need them.

**Comment by nmittler** [comment]
Could you be more specific about what you don't like?

**Comment by ejona86** [comment]
Basically the premise of needing the utilities. I'm working on a counter-PR that I think would make it more obvious.

**Comment by ejona86** [comment]
Take a look at #472.

**Comment by nmittler** [comment]
@ejona86 #472 looks good!  I'll abandon this PR. Thanks!

**Pull request closed without merging**
