### PR TITLE
Allow a listener to be passed to Contexts.interceptCall(...)

### PR DESCRIPTION
**Pull request by jhspaybar**

### CODE REVIEW

**Comment by jhspaybar** [comment]
I'm attempting to bridge a legacy request context object into the gRPC system, the way I'm accomplishing this is to grab a header, parse it and turn it into a "RequestContext", this RequestContext is then set on the Context.current() object.  The last part of this step is to be able to call CurrentRequest.set(RequestContext) on all the inbound listeners like onMessage, etc..  In the current setup I'd have to either wrap the ServerCallHandler, or create a second interceptor downstream of the interceptor that changes the context so that I have access to the proper thread for the listener.  This will allow me to create my own listener in a single intercept and then pass it into the Contexts forwarding stuff.

**Comment by ejona86** [comment]
Why can't you wrap the Listener returned by interceptCall?

**Comment by jhspaybar** [comment]
My understanding of the order is that the listener returned by the next.startCall will have the context set by the Contexts.interceptCall class, but that by wrapping the listener returned by intercept call, I'm already back outside the context.

**Comment by ejona86** [comment]
But you have the Context, because it was passed to interceptCall. Couldn't you remember it (with `final`) and use the saved one versus the not-yet-thread-local one?

But I guess it does make sense to have a method that just wraps a provided listener. We may want the Context to be implicit in that case, because when you call `next.startCall(method, call, headers)` you should have already attached the Context. I'll have to think about those sorts of cases/what the name should be.

**Comment by jhspaybar** [comment]
Ooooh, to your first paragraph...yes indeed.  At first I'd written it to pull the legacy RequestContext off the Context in the listener, but then I did change it to just reference the final reference...and yes, I don't need this.  But, if you think it could be useful merge it :)  Otherwise, just reject it as your suggestion should work fine.

**Comment by jhspaybar** [comment]
I'm actually going to close this. There is a better alternative, and you rightfully pointed out that this no longer binds properly before startCall

**Pull request closed without merging**
