### PR TITLE
xds: fix wrong json key balancerName

### PR DESCRIPTION
**Pull request by dapengzhang0**
The protobuf key balancer_name is corresponding to balancerName in json.

### CODE REVIEW

**Comment by sanjaypujare** [comment]
Can you fix XdsNamResolverTest.java  to XdsNameResolverTest.java ?

**Comment by dapengzhang0** [comment]
>Fix typo XdsNamResolverTest

Done.

**Comment by dapengzhang0** [comment]
@sanjaypujare, can you unblock merging?

**Comment by sanjaypujare** [comment]
> @sanjaypujare, can you unblock merging?

dismissed review

**Pull request merged**
