### PR TITLE
all: update to gradle 2.14.1

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by ejona86** [comment]
Jenkins retest this please

**Comment by carl-mastrangelo** [comment]
Android plugin `com.android.application` seems to balk at versions above 2.

**Comment by dapengzhang0** [comment]
LGTM

**Comment by ejona86** [comment]
For 3.1 compatibility, you just need to bump com.android.tools.build:gradle to 2.2.0

**Comment by ejona86** [comment]
@carl-mastrangelo, has this not been merged yet because you hope to update to 3.1? I had been fine with merging this as-is.

Aaaand 3.2 was released today.

**Comment by carl-mastrangelo** [comment]
PTAL

Thrift build from the examples still fails.

```
~/git/grpc-java/examples
Wed Nov 16 03:32:41$ ./gradlew build
Parallel execution is an incubating feature.
:extractIncludeProto
:thrift:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':thrift:compileClasspath'.
> Could not find io.grpc:grpc-thrift:1.1.0-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.0-SNAPSHOT/grpc-thrift-1.1.0-SNAPSHOT.pom
  Required by:
      project :thrift
```

**Comment by carl-mastrangelo** [comment]
It appears this is broken on head.  I agree with this error message, there is no grpc-thrift project on Maven Central.

I'm going to submit this and file a bug to fix the thrift specific build error.

**Comment by carl-mastrangelo** [comment]
Jenkins, retest this please

**Comment by dapengzhang0** [comment]
@carl-mastrangelo with the new version gradle, did the `cd examples/..; ./gradlew install` command successfully install the grpc-thrift-1.1.0-SNAPSHOT JAR file in your local maven repo?

I would suggest remove the line `include 'thrift'` from the `examples/settings.gradle` file. Because it tends to cause build failure and depress people, and most people don't need thrift at all when they first learn the examples.

**Comment by carl-mastrangelo** [comment]
For some mysterious reason, the JUnit output text is not being printed when run on Jenkins, so the tests don't pass there.  I need to figure that out before submitting.

**Comment by ejona86** [comment]
Jenkins, retest this please

**Pull request merged**
