### PR TITLE
Start 1.15.0 development cycle

### PR DESCRIPTION
**Pull request by zpencer**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
I had made this PR but noticed that none of the generated code was updated.  Did something not run?

**Comment by zpencer** [comment]
So you're saying on your PR, the git porcelain check failed because generated code was not updated?

**Comment by ejona86** [comment]
Do you have skipCodegen=true in your gradle.properties?

**Comment by carl-mastrangelo** [comment]
I don't but I guess it seems dropping the version was intended behavior, added in #2010.  WAI.

**Comment by ejona86** [comment]
Oh, I see what you're saying. Yeah, our generated code doesn't have the version in it any more. Only the golden files still have the version.

**Pull request merged**
