### PR TITLE
Don't let server start if already shutting down

### LINKED ISSUE #999: Possible race condition ServerImpl between start() and shutdown()
I believe it may be possible if start and stop are called concurrently that the shared executor may not get released.  I'm not sure if this is an actual problem, but it does go against the @ ThreadSafe annotation.

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #999

### CODE REVIEW

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

**Comment by madongfly** [comment]
@carl-mastrangelo LGTM

**Comment by ejona86** [comment]
This looks like something good to backport to v0.9.0

**Comment by carl-mastrangelo** [comment]
Cherry picked into 0.9.x

**Pull request merged**
