### PR TITLE
release: tagging release

### PR DESCRIPTION
**Pull request by YifeiZhuang**

### CODE REVIEW

**Comment by ejona86** [comment]
This will need to wait a few weeks.

**Comment by YifeiZhuang** [comment]
Hi Penn @dapengzhang0, can we start merging this PR? We are still going to release next Tuesday, right?

**Comment by ejona86** [comment]
This should happen the day before the release/the day of the actual release build, as the tag is determined before you create this PR.

**Comment by YifeiZhuang** [comment]
@dapengzhang0 shall we merge this PR? I am planning start the release build for the release tmr, or do we further postpone the release date?

**Review by ejona86 — APPROVED** [review]
Since this was generated earlier than normal, we'll need to rebase and merge this instead of the normal process.

**Review by ejona86 — APPROVED** [review]

**Review by dapengzhang0 — APPROVED** [review]

**Pull request merged**
