### PR TITLE
netty: fix server keepalive unexpected ping ack (backport v1.6.x) 

### LINKED ISSUE #3684: WARNING: Received unexpected ping ack. No ping outstanding
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8.0_141-b15

### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you see instead?
I see lots of these lines:
> Nov 07, 2017 11:52:01 PM io.grpc.netty.NettyServerHandler$FrameListener onPingAckRead
> WARNING: Received unexpected ping ack. No ping outstanding

Looks like just a warning, but I wanted to know if this could be some network issue.

### PR DESCRIPTION
**Pull request by dapengzhang0**
Resolves #3684

### CODE REVIEW

**Comment by mfirry** [comment]
Should I expect a new 1.6.x release with this fix?

**Comment by dapengzhang0** [comment]
@mfirry Normally bug fixes will be included in the latest release, and we patch on the branch that is one version earlier. So it is shipped in v.1.8.0, probably will be in patch v1.7.1. If we make a patch for the 1.6.x branch, then the fix will be in v1.6.2, but we don't have a plan to do it. If you can not upgrade to v1.8.0 and strongly demand a patch for 1.6 branch, please let us know.

**Comment by mfirry** [comment]
Thanks so much! I’ve asked on the google group, but I’ll ask here as well... any issue I should consider when planning on upgrading from 1.6 to 1.8? Can I just safely upgrade the dependency and ship it? Thanks!

**Comment by dapengzhang0** [comment]
You can check the release notes https://github.com/grpc/grpc-java/releases/tag/v1.7.0 and https://github.com/grpc/grpc-java/releases/tag/v1.8.0 to see the dependency changes and breaking APIs.

**Comment by mfirry** [comment]
Will do. Thanks a lot.

**Pull request merged**
