### PR TITLE
gcp-observability: update logging schema and configuration for public preview (1.50.x backport)

### PR DESCRIPTION
**Pull request by sergiitk**
Backport #9608, #9622.

CC @DNVindhya

### CODE REVIEW

**Comment by sanjaypujare** [comment]
@DNVindhya are there any other commits needed? Also typically we backport 1 PR at a time. This kind of 2 PRs combined into a single backport PR is something I have not seen but I see no problem

**Comment by sergiitk** [comment]
@sanjaypujare I've done this before. I'll apply rebase-merge strategy - so we could rollback individual commits if we choose to.

**Comment by DNVindhya** [comment]
I verified the changes in the PR it includes changes done for specifically for observability public preview after the branch was cut.

**Review by sanjaypujare — APPROVED** [review]
LGTM

**Pull request merged**
