### PR TITLE
okhttp: Don't allow server half-closes before client's half-close.

### LINKED ISSUE #300: Reset stream if receive server's halfClose before client sends halfClose.
This was exposed by the discussion on #279.

### PR DESCRIPTION
**Pull request by madongfly**
Resolves #300

### CODE REVIEW

**Comment by madongfly** [comment]
@ejona86 Please take a look, thanks!

**Comment by ejona86** [comment]
@madongfly, this PR is taking the wrong view of the issue. Server half-close _is allowed_ before client half close. This would commonly happen in error cases, but is also permitted for Status.OK. Nothing really changes, semantically. The only thing that needs to happen is we send a RST_STREAM (probably with CANCEL as code).

**Comment by nathanielmanistaatgoogle** [comment]
I thought this smelled interesting... ;-)

**Comment by madongfly** [comment]
@ejona86 Ok, seems I got a misunderstanding, I thought we talked about the same rule that Stubby4 obeys: no server-side half close comes before client-side half close.

But I didn't get your comment, are you saying in such case we just send a reset to the server and do nothing else? then what's the point of this reset?

**Comment by ejona86** [comment]
@madongfly, we had discussed Stubby's behavior a while back, but that was in deciding whether OK should be allowed before the client half-closed. In one of the large gRPC meetings we all decided not to add an extra restriction to OK. Error codes have always been allowed to occur before client half-closed.

The point of the RST_STREAM is to move the stream into closed state. If you look at the [stream state diagram in HTTP/2](http://http2.github.io/http2-spec/#StreamStates) you can see that it has normal TCP semantics: there is no distinction between client and server END_STREAM.

As a client who's stream is still open and knowing that the server has already complete its response, we have two options to advance the stream to closed: send a DATA frame with END_STREAM or send RST_STREAM. Sending END_STREAM would work, but seems more dangerous as it would imply the normal end of the stream. RST_STREAM is just as easy and doesn't convey any meaning that could be misinterpreted.

**Comment by madongfly** [comment]
@ejona86 sorry, I'm still confused.

Since we allow OK comes before client half-close, imagine we have a client stream is open and sees the OK from server, so we send RST_STREAM to the server, the server marks the stream as closed, then what should we do if the client wants to send something more? If we forbid the sending and fail the client, then it's basically equals to "No OK comes before client half close", if we just send out the data anyway and finish the stream successfully, then the client would think the data was received by the server while the server actually can not receive data from a closed stream.

Am I still missing something to understand the problem?

**Comment by ejona86** [comment]
Receiving the Status from the server is the end of the RPC. The client can try to send more, but it will just be thrown away. We _don't fail the client_. Instead, we deliver OK. After we deliver OK we can't deliver any other status.

In no way do we guarantee message delivery. As taken from [Call documentation](https://github.com/grpc/grpc-java/blob/3ddd1d525f840db93cbb54470e1332925cb51d50/core/src/main/java/io/grpc/Call.java#L47):
> No generic method for determining message receipt or providing acknowledgement is provided.
> Applications are expected to utilize normal payload messages for such signals, as a response
> naturally acknowledges its request.

**Comment by nicolasnoble** [comment]
Can one of the admins verify this patch?

**Comment by madongfly** [comment]
Just closed it, I'll send another PR for #300 after discussing it with Eric.

**Pull request closed without merging**
