### PR TITLE
Rename internal.Server to internal.TransportServer

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Searching for Server often brings up two (the internal, and external version).  Rename the internal to not conflict.

### CODE REVIEW

**Comment by ejona86** [comment]
We didn't do this because we also have a `ServerTransport`, which is confusing in its own right.

**Comment by carl-mastrangelo** [comment]
How about InternalServer?

**Comment by ejona86** [comment]
InternalServer SGTM.

**Comment by carl-mastrangelo** [comment]
@ejona86 ptal

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

**Pull request merged**
