### PR TITLE
Use the RoundRobinServerList in the SimpleLoadBalancer.

### PR DESCRIPTION
**Pull request by jhspaybar**

### CODE REVIEW

**Comment by jhspaybar** [comment]
This pull request moves the RoundRobinServerList into the io.grpc.internal package of core.  It also changes the SimpleLoadBalancer to use round robin across all ResolvedServerInfo objects rather than to treat all ResolvedServerInfo as a single EquivalentAddressGroup.  It has also made me want to raise a couple questions, so I'll add them here and can make an issue if that'd be better.

When writing this and making changes, I noticed that a number of tests expected all of the ResolvedServerInfo coming from the NameResolver to be treated as a single EquivalentAddressGroup and that as the first SocketAddress failed the tests were ensuring that the TransportSet was then trying to connect to other addresses.  This seems like reasonable behavior if for example the EquivalentAddressGroup was the IPv4 and IPv6 address rather than *all* addresses coming from the NameResolver.  I'm wondering, should the NameResolver be emitting EquivalentAddressGroups rather than ResolvedServerInfo?  It's not clear to me how I can have a list of 10 different machines that have multiple equivalent IPs for each machine and actually properly load balance them.  Would love to discuss this further.  Thanks

@ejona86 @zhangkun83

**Comment by zhangkun83** [comment]
It does sound reasonable for `NameResolver` to emit `EquivalentAddressGroup` instead of `ResolvedServerInfo`. For DNS, I don't think it has enough information for grouping addresses so it will probably just put all addresses in a single `EquivalentAddressGroup`.

I think we should keep the "pick-first" behavior of `SimpleLoadBalancer`. In a scenario where the client would disconnect after doing a few RPCs, it may prefer to stick to one server even if NameResolver gives multiple, to creating multiple connections. We can probably make it an option between "pick-first" and "round-robin" at the construction of the LoadBalancer.

**Comment by jhspaybar** [comment]
Sounds good, I'll expand on this pull request a bit then and see if I can come up with a reasonable way to modify the interfaces to have 'NameResolver's emit `EquivalentAddressGroup` into the `LoadBalancer`.

What do you think is the best way to get the property into the load balancer to determine if it's doing round robin or first pick?  I could read a system property, but that seems a bit out of the norm for grpc.  Given that first pick is the default load balancer factory, would I be better off just making another factory and allowing clients to simply choose to add it?  If I go this route I suspect there'll be a fair bit of overlap in code between the FirstPickLoadBalancer and the RoundRobinLoadBalancer, should I explore a Forwarding*Call style approach like we have for interceptor help?

**Comment by zhangkun83** [comment]
Currently, the pick-first logic is handled by `TransportSet`, while it doesn't differentiate addresses of the same server vs. different servers. After `NameResolver` begins to emit `EquivalentAddressGroup`, seemingly we will also need a pick-first `LoadBalancer` that does the same thing as `TransportSet` does, including reconnect back-off, which is fairly complicated to implement.

However, I don't find much benefit of repeating the pick-first logic in the LoadBalancer. Maybe we can keep it simple, by concatenating all `EquivalentAddressGroup`s from NameResolver into one, and letting `TransportSet` to pick-first across the flat list of all addresses. This LoadBalancer will be substantially different from RoundRobinLoadBalancer, thus we will make them separate classes. And it will still be the default one, so people who want to use round-robin, could pass a RoundRobinLoadBalancer instead.

I am not sure I want to keep calling this default LoadBalancer `SimpleLoadBalancer`. I hope to use a name that is more descriptive. Any suggestion?

**Comment by zhangkun83** [comment]
This would resolve #1141

**Comment by jhspaybar** [comment]
Okay, I've been busy but I think I'm going to make 2 pull requests here. One will be to change name resolvers to emit an EquivalentAddressGroup.  The other will be to create a RoundRobinLoadBalancer that can be used instead of the SimpleLoadBalancer at creation time. Breaking these apart seems smart to let them progress independently.

**Comment by jhspaybar** [comment]
Closing in favor of https://github.com/grpc/grpc-java/pull/1916

**Pull request closed without merging**
