### PR TITLE
all: fix minor JavaStyle errors found in code sync

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
Are you synced to head?  I fixed some of these in https://github.com/grpc/grpc-java/commit/f5f9ca52c805da56d681e733bee45cb00e5e0001

**Comment by dapengzhang0** [comment]
@carl-mastrangelo, I synced your fix https://github.com/grpc/grpc-java/commit/f5f9ca52c805da56d681e733bee45cb00e5e0001. Here's some additional.

**Comment by carl-mastrangelo** [comment]
Please sync to head and push

**Comment by dapengzhang0** [comment]
@carl-mastrangelo, I was aware of your https://github.com/grpc/grpc-java/commit/f5f9ca52c805da56d681e733bee45cb00e5e0001. Here's all new ones found after the latest MOE sync.

**Comment by carl-mastrangelo** [comment]
@dapengzhang0  LGTM

**Pull request merged**
