### PR TITLE
xds: promote XdsNameResolver2

### PR DESCRIPTION
**Pull request by voidzcy**
Tests look good.

One thing I noticed is 
https://github.com/grpc/grpc-java/blob/cb8b0679add2d389cfd15cd34e11c3577e3de2cb/xds/src/main/java/io/grpc/xds/XdsNameResolver2.java#L243

might be too verbose, every single RPC will print out this log. We may want to delete it or lower its level. But that should be done in a separate PR. This PR only replaces XdsNameResolver with XdsNameResolver2. Diff is misleading.

### CODE REVIEW

**Comment by dapengzhang0** [comment]
> This PR only replaces XdsNameResolver with XdsNameResolver2. Diff is misleading.

Actually you can only make one-line change by modifying `resources/META-INF/services/io.grpc.NameResolverProvider`

**Comment by voidzcy** [comment]
> Actually you can only make one-line change by modifying `resources/META-INF/services/io.grpc.NameResolverProvider`

That would still leave two copies of code, in which the old copy eventually needs to be deleted.

**Comment by dapengzhang0** [comment]
> That would still leave two copies of code, in which the old copy eventually needs to be deleted.

We leave two copies of code until the new resolver is working for at lease one release.

**Comment by dapengzhang0** [comment]
Plus, one-line change is super easy to rollback, even new change is added to the resolver later.

**Comment by voidzcy** [comment]
> Plus, one-line change is super easy to rollback, even new change is added to the resolver later.

We do not need to wait one release. We should delete the unused codepath as quick as possible. Otherwise, if we need to change something in the resolver, we need to change in both, just like the issue #7400 is facing.

**Review by dapengzhang0 — APPROVED** [review]
LGTM

**Pull request merged**
