### PR TITLE
test: bump junit to 4.12

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
Can't be done, as it won't match the internal version.

**Comment by dapengzhang0** [comment]
What is the internal version? I though it is even later than 4.12

**Comment by carl-mastrangelo** [comment]
We are stuck at 4.11 for the indefinite future.

**Comment by dapengzhang0** [comment]
I see. JUNIT_VERSION = "v4_11" is currently used. thanks @carl-mastrangelo

**Pull request closed without merging**
