### PR TITLE
Backport the supporting of ALPN on Android older than 5.0.

### PR DESCRIPTION
**Pull request by madongfly**
@ejona86, please take a look, thanks!

### CODE REVIEW

**Comment by ejona86** [comment]
Did you have to do any manual merging?

**Comment by ejona86** [comment]
There was manual merging due to 2fe279f

@madongfly, from what I can see, it seems like most of the changes of 2fe279f were undone/integrated into 25da649. If that's true, then we should cherry-pick it as well, so that the three commits don't have any manual merging.

**Comment by madongfly** [comment]
@ejona86, I cherry picked the 3 commits and no manual change made.

I also add the release commit.

**Comment by ejona86** [comment]
@madongfly LGTM. However, it would probably be better to wait on the release commit until we actually start making the release binaries. So just commit the first 3 commits.

**Pull request merged**
