### PR TITLE
android: Annotate tests to use Robolectric's LEGACY LooperMode. bump roboletric to 4.3.1, truth to 1.0.1 and sdk to 28.

### PR DESCRIPTION
**Pull request by ran-su**
http://cl/297608217

### CODE REVIEW

**Comment by creamsoup** [comment]
this LooperMode is added in robolectric `4.3.1`.  so, it requires major version bump. since this is testing framework, if all tests are passing after upgrade. i can accept the change.

**Comment by voidzcy** [comment]
> this LooperMode is added in robolectric `4.3.1`. so, it requires major version bump. since this is testing framework, if all tests are passing after upgrade. i can accept the change.

We are already on `4.3.1`.

**Comment by creamsoup** [comment]
i noticed that the truth should be on 1.0.1 too.

**Comment by voidzcy** [comment]
#6775 is created for keeping sync. with main build's dependency versions, we can add this annotation when doing that. We would need a PR for cronet, if it is also needed there.

**Comment by ran-su** [comment]
PTAL

**Pull request merged**
