### PR TITLE
core: fix missing comment for headers param

### PR DESCRIPTION
**Pull request by MaoJianwei**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @MaoJianwei isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by MaoJianwei** [comment]
Hello, I signed the CLA just now :)

**Comment by MaoJianwei** [comment]
It seems not a failure of my code ?

**Comment by ejona86** [comment]
Thanks!

**Pull request merged**
