### PR TITLE
Use system.getProperty() to replace system.getenv() in examples module.

### PR DESCRIPTION
**Pull request by horizonzy**
For-#7697

### CODE REVIEW

**Comment by ejona86** [comment]
I mention in #7697 that it isn't clear what problem you're trying to solve.

**Comment by horizonzy** [comment]
This part I just think use System.getProperties is more easier to use for user, so did it, not to solve some problem


------------------ Original ------------------

**Comment by ejona86** [comment]
For this usage, I don't think system property is any better suited than environment variable. And with the environment variable this same example could exist in multiple languages (if we were so inclined). In "real" code, there's clearer reasons on using one vs the other, but I don't think so here. Although a command line argument may be better than both.

I'm going to close this, since I don't think it changes much for the user.

**Comment by ejona86** [comment]
@horizonzy, fyi, you don't need to create an issue if you are immediately creating a PR. Sometimes it can be useful if you need to document a complex bug. But often just the PR is enough.

**Pull request closed without merging**
