### PR TITLE
netty: bump to 4.1.38

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by viktorklang** [comment]
@carl-mastrangelo Hi Carl,
is there any chance for updating 1.22.2+ to Netty 4.1.36+ (Graal support)?
Or will we have to wait for 1.23.0? (Since grpc-java includes a shaded version of netty it isn't that simple to just override the Netty dependency when building)
Thoughts?

Cheers,
√

**Comment by viktorklang** [comment]
@carl-mastrangelo Through adding Netty 4.1.38 to 1.22.2-SNAPSHOT and publishing locally, I'm seeing an issue that needs to be taken care of—the shade plugin which generates the grpc-netty-shaded.jar needs to be augmented to rewrite the FQCNs and package names in the Graal configuration which is in, for instance: https://github.com/netty/netty/tree/4.1/common/src/main/java/io/netty/util/internal/svm and in https://github.com/netty/netty/blob/4.1/transport/src/main/resources/META-INF/native-image/io.netty/transport/reflection-config.json and in https://github.com/netty/netty/tree/4.1/transport/src/main/resources/META-INF/native-image

**Comment by viktorklang** [comment]
All of the above relates to #5460

**Comment by ejona86** [comment]
@viktorklang, we don't generally upgrade the Netty version in a previous release unless there's a significant reason to, because new Netty versions have a significant amount of risk which is generally inappropriate for a patch release.

You are free to use `grpc-netty` instead of `grpc-netty-shaded` and then select the version of Netty (although we really only support the versions of Netty we select for releases).

**Comment by carl-mastrangelo** [comment]
@viktorklang I'm afraid I'm super unfamiliar with Graal and configuring it.   I'm happy to review a PR if you want to send one.

**Comment by viktorklang** [comment]
@carl-mastrangelo You and me both! :) All I know is that there are some META-INF folders which needs to be search-replace renamed, and some strings within text files under META-INF which needs to be search-replaced. Unfortunately I found no obvious way of doing search-replace with the shadow plugin (and I'm no Groovy/Gradle expert by far) so I am unable to be of much help there. But if someone can get the rename/search-replace machinery working then I can help with what needs replacing. :)

**Comment by viktorklang** [comment]
@ejona86 Unfortunately I cannot switch to grpc-netty since I have a 3rd party which compiles against grpc-netty-shaded :(

**Pull request merged**
