### PR TITLE
Disable parallel with argument for greater ease

### PR DESCRIPTION
**Pull request by ejona86**
@carl-mastrangelo, do you think this works better?

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
Wanna update the other refs around this file too?

**Comment by ejona86** [comment]
I was thinking they were actually fine since they were only uploading a single file, but that's probably a false assumption. I'll update them.

**Comment by ejona86** [comment]
@carl-mastrangelo PTAL

**Comment by carl-mastrangelo** [comment]
@ejona86 LGTM

**Pull request merged**
