### PR TITLE
services: move channelz proto into normalized directory structure

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
I will make other changes in a followup PR

### CODE REVIEW

**Comment by zpencer** [comment]
I think you need to run a build and check in the changes to the generated java classes.

**Comment by carl-mastrangelo** [comment]
I forgot about that.  Done.

**Comment by zpencer** [comment]
Not sure why it can't find the snapshot all of a sudden. Is it missing a "./gradlew install"? I always thought these kokoro jobs started with a blank state so not sure why this is failing now.

**Comment by carl-mastrangelo** [comment]
@zpencer looks like tests pass now

**Pull request merged**
