### PR TITLE
examples: make JSON code more obviously advanced

### LINKED ISSUE #1778: HelloJsonClient is not obviously advanced
The helloworld example is supposed to be the first thing you see. The JSON client example is easily confused as being important for initial users. We need some way to distinguish it and avoid new users looking at it too early.

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #1778

### CODE REVIEW

**Comment by ejona86** [comment]
@carl-mastrangelo this LGTM, but I'm a bit concerned it may not be enough. Maybe move it to a separate package (maybe something like "advanced") like we do for experimental?

**Comment by carl-mastrangelo** [comment]
the examples directory is so sparse right now.  I'd prefer to wait until we have more examples before adding directory depth.

**Comment by ejona86** [comment]
Then how about a package like "json" or "marshalling" or such instead of "helloworld"? Both @hsaliak and I got bit by this.

If we're not going to move it to someplace out-of-the-way, then I'd suggest we delete it instead.

**Comment by carl-mastrangelo** [comment]
Not sure what's to be bitten by.  The behavior of that class isn't surprising or unexpected.  It represents a build time proof that the code compiles.  If people misunderstand the intent of that class, then a javadoc seems like a good enough sign to steer people away.

**Comment by ejona86** [comment]
The problem is that we are adding noise here: https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/helloworld . Hello world is supposed to be the simplest example. But this example isn't really a hello world example. It's more of a json/marshaller example.

I'd be _much_ more okay with RouteGuide being in the same directory as HelloWorld, because it is obvious it is unrelated.

**Comment by hsaliak** [comment]
/cc @LisaFC 
I want to amplify @ejona86's sentiment. We should make the hello world example seem, on the outset, as simple as possible.  

Json/marshaller example goes beyond the hello world and it initially confused me as to its purpose.

**Comment by carl-mastrangelo** [comment]
We could rename JsonHelloWorld to JsonMarshaller, but it still belongs in the examples directory.

**Comment by ejona86** [comment]
I don't think there was disagreement as to whether it should be in the examples. What package would it have?

**Pull request merged**
