### PR TITLE
Update Netty dependency to 4.1CR6.

### PR DESCRIPTION
**Pull request by buchgr**
:monkey_face:

### CODE REVIEW

**Comment by ejona86** [comment]
@buchgr LGTM

**Comment by ejona86** [comment]
:see_no_evil:

**Comment by buchgr** [comment]
thanks! sorry didn't see that CR6 was out already ...

**Comment by ejona86** [comment]
@buchgr, np. You should remember to check the current Netty version every hour, for optimal freshness. :stuck_out_tongue:

The only reason I saw it is because I've subscribed to the GitHub releases Atom feed in my news aggregator. (I still miss Google Reader :cry:)

**Pull request closed without merging**
