### PR TITLE
xds: Allow unspecified listener traffic direction to work with Istio

### PR DESCRIPTION
**Pull request by cfredri4**
Fix for #9157.

Ping @sanjaypujare

### CODE REVIEW

**Comment by sanjaypujare** [comment]
@yashykt @easwars I think C++ and Go don't have the [check](https://github.com/grpc/grpc-java/blob/master/xds/src/main/java/io/grpc/xds/ClientXdsClient.java#L388) so they accept LDS even if the direction is unspecified. Is that correct?

**Review by sanjaypujare — APPROVED** [review]
LGTM

**Comment by easwars** [comment]
> @yashykt @easwars I think C++ and Go don't have the [check](https://github.com/grpc/grpc-java/blob/master/xds/src/main/java/io/grpc/xds/ClientXdsClient.java#L388) so they accept LDS even if the direction is unspecified. Is that correct?

Yes, grpc-go does not have a check for the `TrafficDirection` field.

**Comment by yashykt** [comment]
Core/C++ does not make any check on traffic direction

**Pull request merged**
