### PR TITLE
Add support for cross-compiling for s390x platform

### PR DESCRIPTION
**Pull request by haubenr**
This PR adds s390x binaries to the maven artifacts published for this component. This PR builds on changes that were added with #6441 and #9284

### CODE REVIEW

**Comment by haubenr** [comment]
@ejona86 Can you please take a look at this? Should be pretty straightforward.

**Comment by ejona86** [comment]
Uhh... this isn't the sort of build failure I was expecting:
```
  CXX      google/protobuf/compiler/importer.lo
  CXX      google/protobuf/compiler/parser.lo
  CXX      google/protobuf/descriptor.lo
  CXX      google/protobuf/descriptor.pb.lo
google/protobuf/generated_message_tctable_lite.cc: In static member function 'static const char* google::protobuf::internal::TcParser::MiniParse(google::protobuf::MessageLite*, const char*, google::protobuf::internal::ParseContext*, const google::protobuf::internal::TcParseTableBase*, uint64_t, google::protobuf::internal::TcFieldData)':
google/protobuf/generated_message_tctable_lite.cc:342:1: internal compiler error: output_operand: invalid %-code
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:4514: recipe for target 'google/protobuf/generated_message_tctable_lite.lo' failed
make[2]: *** [google/protobuf/generated_message_tctable_lite.lo] Error 1
```

**Comment by haubenr** [comment]
Thanks for taking a look! I tested the protobuf compilation on two servers - one running Ubuntu 22.04.1 LTS on x86_64 and the other one running Ubuntu 18.04.6 LTS on s390x.

On x86_64, the installed cross-compilation binary for s390x outputs this:

```
$ s390x-linux-gnu-g++ --version
s390x-linux-gnu-g++ (Ubuntu 11.2.0-17ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

On s390x where cross-compilation isn't needed g++ compiler reports this:

```
$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

With this compiler, protobuf doesn't built natively on s390x but fails with the same error message we get from this PR's build run. On the x86_64 server the cross compilation works just fine and the build produces the binary as expected.

I suspect that the compiler package is of importance - it would seem that one needs the latest and greatest version to be able to compile protobuf for s390x, even in a cross compilation scenario. Which Ubuntu version is the PR build server running?

**Comment by haubenr** [comment]
Experimented some more... the key is the compiler *version* - g++-7 is not able to compile the protobuf source code. One must upgrade to g++-11 to succeed. On my s390x server I did this:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update && sudo apt install gcc-11 g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11
sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-11 110
```

After that, the build for protobuf succeeds.

Not sure how to deal with this for the cross-compilation package for Ubuntu... on Ubuntu 22.04.1 LTS it would seem you get a compatible compiler when running `apt-get install g++-s390x-linux-gnu`. On older Ubuntu release this is likely not the case.

**Comment by haubenr** [comment]
I fixed the issue - turns out g++ version 8.x is able to compile protobuf for s390x.

**Comment by haubenr** [comment]
Nope, that didn't work... looks like g++ version 11.x is required for building protobuf for s390x. Unfortunately this compiler package is only available on Ubuntu 22.04 LTS.

**Comment by haubenr** [comment]
@ejona86 Sorry for all the back and forth... I've introduced a somewhat substantial change to the build mechanism by utilizing a dedicated Ubuntu 22.04 LTS Docker container for building the s390x artifacts. This solves the dependency issue for GCC/G++ version 11.x without the need of any modifications to the underlying build server.

If you think this approach makes sense all protobuf-related artifact builds could be handled via this container: arm64, ppc64le, s390x and even x86_64 (in that case it would replace the CentOS-based Docker image).

**Comment by haubenr** [comment]
@ejona86 Could you please take another look? Thanks!

**Comment by dilipgb** [comment]
@ejona86 any update on this?

**Comment by dilipgb** [comment]
@ejona86 I'm looking for s390x support for one of our component and this comes as hard dependency. Please let us know if there are any changes needed before merge. Any input from you will be helpful in speed up our implementation.

**Review by ejona86 — APPROVED** [review]
I'm sorry this has languished. We've got a work item to upgrade the kokoro environment we're using, as I _think_ it is 16.04, and I didn't expect it to draw out like it has. I didn't realize you had swapped to the dockerfile. I think that is the right approach.

I've made one comment, which I can take or leave.

**Review by larry-safran — APPROVED** [review]

**Pull request merged**
