### PR TITLE
Release 1.7.0

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by zpencer** [comment]
General question: Do we always use the latest available protoc available when we do a release?

**Comment by ejona86** [comment]
Before merging this we should make sure that we didn't miss any backports and determine what's happening with the unfixed issues in the [1.7 milestone](https://github.com/grpc/grpc-java/milestone/20) (normally, it's to just move it to 1.8, but we may notice we've mixed something important).

We don't update protobuf on the release branch, unless there is a strong reason to. So if it wasn't updated on master before the branch cut then it's likely to stay slightly old.

**Comment by dapengzhang0** [comment]
@zpencer I think we may try the latest available protoc in master before cutting the branch, but when we do a release/make a tag, just use the same protoc as in the branch.

**Comment by dapengzhang0** [comment]
made a mistake

**Pull request closed without merging**
