### PR TITLE
Upgrading to the latest Netty 4.1 branch.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 can you take a look?

**Comment by buchgr** [comment]
@nmittler are there no test failures / compilation errors? I was expecting at least https://github.com/netty/netty/commit/c91eaace5e5691ae05c0854d29a2524d94166e44 to break some code?

**Comment by nmittler** [comment]
@buchgr oof you're right, my IDE was lying to me :).  Amended the commit.

**Comment by buchgr** [comment]
@nmittler thanks. LGTM.

**Comment by ejona86** [comment]
@nmittler, LGTM

**Comment by nmittler** [comment]
cherry-picked as 11d0094

**Pull request closed without merging**
