### PR TITLE
protobuf: make buffer cache even weaker

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by buchgr** [comment]
Hmm. Interesting. When under memory pressure should we allow the GC to free that object, so that allocating a new one will create even more memory pressure? 😅

**Comment by buchgr** [comment]
LGTM

**Comment by carl-mastrangelo** [comment]
The case I was thinking about was when their application is doing a lot of work after the RPC is parsed.  The application will want that memory back, and presumably not for doing more parsing.

Also, did you have a preferred wording for the escaping comment?  Something that makes it clear that it is okay to reuse buf?

**Comment by buchgr** [comment]
> The case I was thinking about was when their application is doing a lot of work after the RPC is parsed. The application will want that memory back, and presumably not for doing more parsing.

I can think of use cases where we want the memory back and where we don't want the memory back :-). Also, it's kind a GC dependent and thus complex :-). I think either way is fine.

> Also, did you have a preferred wording for the escaping comment? Something that makes it clear that it is okay to reuse buf?

I tried to phrase a sentence for 5 minutes, but I can't. been hacking for 12 hours straight ... my head hurts 😅. I think it's fine to leave as is, or something that says that upon method exit that byte[] will not be referenced from anywhere but the thread local and thus can be re-used :-).

**Comment by carl-mastrangelo** [comment]
Ok, I updated the commit to remove the "escape" part.

Thanks for the review @buchgr

**Pull request merged**
