### PR TITLE
Sync LB proto with grpc-proto

### PR DESCRIPTION
**Pull request by AspirinSJL**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
@AspirinSJL can you update this as well?

**Comment by AspirinSJL** [comment]
Yes, one moment.

**Comment by AspirinSJL** [comment]
Synced.

**Comment by carl-mastrangelo** [comment]
This should have affected some more files.  can you run `./gradlew build` too?

**Comment by AspirinSJL** [comment]
Amended.

**Comment by AspirinSJL** [comment]
Cool, thanks!

**Pull request merged**
