### PR TITLE
api: Early-detect null bytes from Metadata.Marshaller

### PR DESCRIPTION
**Pull request by ejona86**
See #9706

### CODE REVIEW

**Comment by sanjaypujare** [comment]
How about adding the same checks to

- `AsciiKey.toBytes()` line 982
- `TrustedAsciiKey.toBytes()` line 1007

**Review by sanjaypujare — COMMENTED** [review]
Found 2 places where the check can potentially be added

**Comment by ejona86** [comment]
I had seen both of those places and didn't care. The first will already NPE and the second is fairly safe. It would be good to fix the second to avoid needing to consider the case, and I might as well be consistent with the error message for the first.

**Review by sanjaypujare — APPROVED** [review]
LGTM

**Pull request merged**
