### PR TITLE
api: Update docs for idempotent retries

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Review by ejona86 — COMMENTED** [review]
I believe the text is correct as-is. Transparent retries can be made for non-idempotent RPCs. If the RPC is idempotent then there's no question if it is safe to retry.

**Comment by carl-mastrangelo** [comment]
> I believe the text is correct as-is. Transparent retries can be made for non-idempotent RPCs. If the RPC is idempotent then there's no question if it is safe to retry.

It isn't clear from the documentation that retries are enabled for idempotent RPCs.  My usage of gRPC recently has shown that idempotent RPCs are not retried. We don't have a Service Config, either.

It also seems confusing to want retries for non-idempotent RPCs.  What's the use case for wanting that to be the behavior?

**Comment by sanjaypujare** [comment]
> ...
> It isn't clear from the documentation that retries are enabled for idempotent RPCs. My usage of gRPC recently has shown that idempotent RPCs are not retried. We don't have a Service Config, either.
> 
> It also seems confusing to want retries for non-idempotent RPCs. What's the use case for wanting that to be the behavior?

Take a look at this doc https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries and what it says about transparent retries:

"The second and third cases are retried automatically by the gRPC client library, regardless of the retry configuration set by the service owner. We are able to do this because these request have not made it to the server application logic, and thus are always safe to retry."

So even if an RPC is non-idempotent if no attempt has ever reached the server then it is safe to retry. Do you agree?

**Comment by ejona86** [comment]
> My usage of gRPC recently has shown that idempotent RPCs are not retried.

gRPC does not look at all at the type of RPC to determine how to retry it. So your finding is "RPCs are not retried." Which could mean a lot of things, but the easiest is the configuration was wrong.

**Pull request closed without merging**
