### PR TITLE
Update Netty dependency to 4.1.0.CR7

### PR DESCRIPTION
**Pull request by ejona86**
CC @buchgr :smile:

### CODE REVIEW

**Comment by nmittler** [comment]
LGTM

**Comment by buchgr** [comment]
awww damn you Eric! :smile:

**Comment by buchgr** [comment]
LGTM :stuck_out_tongue_closed_eyes:

**Comment by buchgr** [comment]
I shall ask @normanmaurer to release new Netty versions only while you are asleep :laughing:

**Comment by normanmaurer** [comment]
LOL :)

**Comment by ejona86** [comment]
I'm running some tests against the new version. Once they complete I'll merge this (late today or early tomorrow).

**Comment by normanmaurer** [comment]
Woooot!

**Pull request merged**
