### PR TITLE
Adding support for s390x

### PR DESCRIPTION
**Pull request by aditijadhav38**
Adding support for s390x for gRPC-Java.
Please review.

### CODE REVIEW

**Comment by aditijadhav38** [comment]
I signed it

**Comment by aditijadhav38** [comment]
@thelinuxfoundation I signed it.Please check

**Comment by aditijadhav38** [comment]
I signed it

**Comment by sanjaypujare** [comment]
@aditijadhav38 do you still want to pursue this PR? EasyCLA is still not signed.

**Comment by dapengzhang0** [comment]
This feature was merged in another equivalent PR #6241.

**Pull request closed without merging**
