### PR TITLE
compiler: Upgrade from CentOS 7 to AlmaLinux 8

### PR DESCRIPTION
**Pull request by ejona86**
CentOS 7 became end-of-life on July 1st and is no longer working. We now dynamically link against libstdc++, as RHEL 8 doesn't support static linking: https://access.redhat.com/articles/rhel8-abi-compatibility

We now use objdump in check-artifact for all linux architectures. This avoids using a mix of objdump and ldd. ldd shows transitive dependencies, which is less convenient.

### CODE REVIEW

**Review by temawi — APPROVED** [review]

**Comment by fcharlie** [comment]
Is there any alternative? Our Java application build process is specially customized based on CentOS 7. It is almost impossible to upgrade to a newer version (it is also troublesome to upgrade GCC libstdc++). When using protoc-gen-grpc-java, it reports an error that the CXXABI symbol cannot be found. If there is a good alternative, please let me know.

**Comment by ejona86** [comment]
@fcharlie, you tell us if there's an alternative. RHEL/CentOS 7 is dead, so we had to move off. I don't see a way to support the dead OS, and RHEL/AlmaLinux 8 seems to be the live distro with the oldest glibc. Over a medium term I hope to swap our protoc-gen-grpc-java build to Bazel and then make a real statically linked binary (similar to protobuf's protoc), and then we can build on any distro. But you shouldn't hold your breath for that; right now it is just a dream/aspiration.

**Comment by fcharlie** [comment]
> @fcharlie, you tell us if there's an alternative. RHEL/CentOS 7 is dead, so we had to move off. I don't see a way to support the dead OS, and RHEL/AlmaLinux 8 seems to be the live distro with the oldest glibc. Over a medium term I hope to swap our protoc-gen-grpc-java build to Bazel and then make a real statically linked binary (similar to protobuf's protoc), and then we can build on any distro. But you shouldn't hold your breath for that; right now it is just a dream/aspiration.

Is it possible to use Alpine Linux (musl libc & libc++) to statically link protoc and protoc-gen-grpc-java? The benefit of this is that protoc-gen-grpc-java can run normally on most distributions.

**Comment by ejona86** [comment]
Possible, probably, but that wouldn't be a quick change either.

**Pull request merged**
