### PR TITLE
Adding bin to .gitignore for OSX

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 can you take a look? I still get these directories popping up on OSX ... it's annoying :/

**Comment by nicolasnoble** [comment]
Can one of the admins verify this patch?

**Comment by ejona86** [comment]
Who is creating that? What was in it?

I don't think OSX would create such a file automatically, since it isn't hidden.

**Comment by nmittler** [comment]
@ejona86 it seems to be an artifact of the protobuf generators.

**Comment by ejona86** [comment]
That sounds like the bug that needs to be fixed. The generators shouldn't create anything outside of build/

**Comment by nmittler** [comment]
@zhangkun83 any thoughts?

**Comment by zhangkun83** [comment]
I don't see it on my Mac. How do you reproduce it?

**Comment by nmittler** [comment]
@ejona86 @zhangkun83 ok I think this is being generated by Eclipse.  When I clean all projects, these bin directories keep popping back up.  I can add this to an "Eclipse" section ... WDYT?

**Comment by nmittler** [comment]
PTAL, I've moved the `bin` dir to the `Eclipse` section since that seems to be what's generating it.

**Comment by ejona86** [comment]
@nmittler, LGTM

**Comment by nmittler** [comment]
Cherry-picked as 80a9dce

**Pull request closed without merging**
