### PR TITLE
Remove Deprecated newCall method on Channel

### LINKED ISSUE #734: Deprecated Channel.newCall should be deleted
Clients should use the non deprecated sibling newCall.

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #734

### CODE REVIEW

**Comment by ejona86** [comment]
I think we may want to hold off on this, because we haven't done a release that includes CallOptions yet (I think).

**Comment by carl-mastrangelo** [comment]
You mean an internal release?

**Comment by ejona86** [comment]
No, I was meaning external release. I'm still concerned about how painful the upgrade process will be for our users, and having the Deprecated versions of things does help. The previous Deprecated things were in our previous release, so removing them seemed fine.

**Comment by carl-mastrangelo** [comment]
CallOptions is part of 0.8.0 no?  Also, won't the pain of breakage go up as time goes on?  I am worried that the window to clean up things is closing rapidly, and if not done now, will never happen.  Jayant  brought up never doing a major version bump after release, which will likely be reality.

**Comment by ejona86** [comment]
So as I've mentioned we have two options that seem reasonable:
 1. When we release, we say that anything marked deprecated will be removed in the next release. In the same way we say "internal" classes don't have any API guarantee, we say that currently-deprecated classes are going away. As long as we are clear about it, it should be fine.
 2. We have two releases, back-to-back. We have a non-beta release that has Deprecated things and is used for upgrading, and we have beta which is basically just those things removed. Similarly, we could backport some of the API additions to the 0.7.x branch, to allow swapping to the new way of doing things before upgrading to our beta release.

**Comment by carl-mastrangelo** [comment]
Unless there is something I'm missing, it looks like there are two releases left, at most: 0.8.0 and 1.0.0 (beta and GA).  Beta implies forward API stability. 

For option 1, We have run out of releases.  This is the last chance.  

For option 2, that implies that 0.8.0 is not the beta release (meaning 0.9.0 is beta?), but rather alpha v2?  Do any clients expect that alpha software is stable?  Considering that deprecated implies "clear upgrade path available, use that instead", I don't think this kind of breakage is particularly harmful, especially not at this early stage.


Regardless of which option we pick, it seems to be worthwhile to start adding "Added in $version" annotations into our javadocs.

**Comment by carl-mastrangelo** [comment]
This still needs to be done.  What release would you like it attached to?

**Comment by ejona86** [comment]
"The release after 0.8.0" sounds most appropriate. We can go ahead and make that milestone and rename it to the proper version number later.

**Comment by carl-mastrangelo** [comment]
I bumped the issue milestone to 0.9.0. 

PTAL

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

**Pull request merged**
