### PR TITLE
Change OkHttpClientTransport#start to construct a Socket with the hos…

### PR DESCRIPTION
**Pull request by jonathanjlin**
…tname and port if the address is unresolved.

### CODE REVIEW

**Comment by jonathanjlin** [comment]
I signed it!

**Comment by ejona86** [comment]
You didn't configure author before making the commits, so they have your machine name in the email addresses. I can fix that up, if you want.

**Comment by jonathanjlin** [comment]
Sure, if you could fix that up, that would be great.

**Comment by ejona86** [comment]
Merged as e50f671f1d80ec8523b0ca406cababd46a767d43

Thanks!

**Pull request closed without merging**
