### PR TITLE
[okhttp] Use upper layer passed-in resolved address instead of resolv…

### LINKED ISSUE #1215: Okhttp transport should use resolved address.
Currently, OkHttp transport resolves the host name by itself, the underlying implementation tries all the resolved address one by one, until one connected successfully.

We should only connect with the passed-in resolved address, and shutdown the transport if it can not connect, let the load balance channel layer creates a new transport with a new address.

### PR DESCRIPTION
**Pull request by madongfly**
…ing the hostname by itself.

Fixes #1215

@ejona86 @zhangkun83  Please take a look, thanks!

### CODE REVIEW

**Comment by madongfly** [comment]
For the test, it's hard to write a single test to verify this behavior, so I ended up with two separate tests:
1. In the ManagedChannelImplTest, verifies that when the ClientTransport.start() calls listener.transportShutdown(), the retry will use the second resolved address.
2. In the OkHttpClientTransportTest, verifies that calling start() with an address to an unreachable server will trigger listener.transportShutdown().

**Comment by zhangkun83** [comment]
Although the added tests are useful, I don't think they actually verify your change (which seems impossible to achieve).

**Comment by madongfly** [comment]
@zhangkun83, yeah, I couldn't think of a way to test the behavior change, these two tests can pass even without the OkHttpClientTransport changes, but they can provide more confidence when we manually consider the behavior change is correct.

**Comment by zhangkun83** [comment]
LGTM

**Pull request merged**
