### PR TITLE
Adding metadata to Status exceptions.

### LINKED ISSUE #681: Attaching Metadata to error Status responses...
I'm not sure what the "best practice" is for returning application-level error information (would be very useful to understand Google's own internal practice for guidance), but certainly one approach is to attach trailing headers with application error information to error responses. Setting additional headers via thread-local using a server interceptor seems easy enough, but for client-side it seems particularly awkward capturing metadata on a per-call basis using an interceptor. I see examples in MetadataUtils for capturing "last set headers" on a stub or channel but this is only useful for testing and cannot capture on a per-call basis. Other option would be to use the async stub and a thread-local to pass the metadata information along to StreamObserver.onError() but this loses the convenience of using the blocking and future stubs. I'm not sure if the same approach works for a blocking or future stub since the listener may be invoked in a different thread. 

Will the context api once fully integrated make this easy, or would it make sense to have a way to "attach" metadata to a Status object (perhaps this would be desirable anyway for convenience)?

### PR DESCRIPTION
**Pull request by nmittler**
Fixes #681

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
@nmittler, this LGTM, but should we concerned about API stability at all?

**Comment by nmittler** [comment]
@ejona86 are you referring to the new constructors for the exceptions? It's all additive, so I don't think it should be an issue WRT API stability.

**Comment by ejona86** [comment]
Are we worried about maybe needing to tweak it? In other words, should we have `@ExperimentalApi` on it?

**Comment by nmittler** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
@nmittler LGTM

**Comment by nmittler** [comment]
cherry-picked as 951b5a4

**Pull request closed without merging**
