### PR TITLE
xds: Squelch ADS reconnection error logs

### PR DESCRIPTION
**Pull request by ejona86**
Workaround for #8886, as we wait on a real fix. The regular load
balancing disconnections are confusing users and will train users to
start ignoring gRPC warnings. At present, it is better to have no log
than excessively log.

CC @YifeiZhuang, @erikjoh

----

I've not manually tested this and I'd be happy if someone confirmed it cleaned up the 15 minute RPC churn logging with TD.

### CODE REVIEW

**Comment by erikjoh** [comment]
I can help try this fix out.
Does it make sense to check that config is received at least once per stream?
With this approach I'm curious if for example a `PERMISSION_DENIED` issue would be hidden if the client looses IAM access after the first resolve.

**Comment by ejona86** [comment]
> Does it make sense to check that config is received at least once per stream?

To some degree, yes. But I couldn't surgically do it. It'd require a change in ClientXdsClient/AbstractXdsClient and it started impacting things like timers and I saw some code that was suspicious.

> With this approach I'm curious if for example a PERMISSION_DENIED issue would be hidden if the client looses IAM access after the first resolve.

Yes, it would hide it. RPCs won't fail in that case (for a while), so a warning log is essentially the only way to communicate that. That's why this is a workaround and not a real fix.

**Comment by erikjoh** [comment]
Alright, good to know at least!
I agree with:

> At present, it is better to have no log
than excessively log.

and think this workaround is better than leaving it as-is.

**Comment by erikjoh** [comment]
Hmmmm, seems like more might be needed.
On `1.44.0` after ~15 mins there were two of these warnings:

```
Feb 23, 2022 9:37:36 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (xds:///fabric-test)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Closed by server, cause=null}
Feb 23, 2022 9:37:36 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (xds:///fabric-test)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Closed by server, cause=null}
```

On `1.45.0-SNAPSHOT` built from [ejona86:8886-workaround](https://github.com/ejona86/grpc-java/tree/8886-workaround) there's still a warning after ~15 mins (although one less).

```
Feb 23, 2022 10:07:31 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (xds:///fabric-test)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Closed by server, cause=null}
```

Haven't looked closer at the code yet but I'm wondering if the closed LRS stream also might play some part here.

**Comment by ejona86** [comment]
> there's still a warning after ~15 mins

Wat. There are _two_...

Oh! Two because of the Listener and the Route. I missed the one in Route.

**Review by sergiitk — APPROVED** [review]

**Comment by erikjoh** [comment]
The stacktrace agreed!
```
handleErrorInSyncContext:1892, ManagedChannelImpl$NameResolverListener (io.grpc.internal)
access$7700:1736, ManagedChannelImpl$NameResolverListener (io.grpc.internal)
run:1884, ManagedChannelImpl$NameResolverListener$1NameResolverErrorHandler (io.grpc.internal)
drain:95, SynchronizationContext (io.grpc)
execute:127, SynchronizationContext (io.grpc)
onError:917, XdsNameResolver$ResolveState$RouteDiscoveryState (io.grpc.xds)
...
```
Don't have time to test the latest commit today but I'm assuming it should work!

**Pull request merged**
