### PR TITLE
[No need to review] Testing Google auth library 1.6.1 on 1.45.x branch

### PR DESCRIPTION
**Pull request by suztomo**
No need to review. I don't intend to merge this pull request.

### CODE REVIEW

**Comment by suztomo** [comment]
Execution failed for task ':grpc-all:checkUpperBoundDeps'.
> Maven version skew: com.google.code.gson:gson (2.8.9 != 2.9.0) Bad version dependency path: [project ':grpc-all', io.grpc:grpc-core:1.45.5-SNAPSHOT] Run './gradlew :grpc-all:dependencies --configuration runtimeClasspath' to diagnose

**Comment by suztomo** [comment]
```
> Task :grpc-benchmarks:distTar
/home/runner/work/grpc-java/grpc-java/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java:103: warning: [deprecation] ContextUtils in io.opencensus.trace.unsafe has been deprecated

import io.opencensus.trace.unsafe.ContextUtils;
                                 ^
error: warnings found and -Werror specified
/home/runner/work/grpc-java/grpc-java/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java:1564: warning: [deprecation] ContextUtils in io.opencensus.trace.unsafe has been deprecated
> Task :grpc-interop-testing:compileJava
    ctx = ContextUtils.withValue(ctx, clientParentSpan);
          ^
/home/runner/work/grpc-java/grpc-java/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java:1584: warning: [deprecation] ContextUtils in io.opencensus.trace.unsafe has been deprecated
      Span span = ContextUtils.getValue(serverCtx);
                  ^
1 error

3 warnings
> Task :grpc-interop-testing:compileJava FAILED

```

**Comment by ejona86** [comment]
I know the full CI failed, but it got past the part you are interested in. I've also double-checked locally that google-auth 1.6.1 is fine on 1.45.x branch.

**Comment by suztomo** [comment]
The build succeeded.

```
BUILD SUCCESSFUL in 4m 32s
364 actionable tasks: 149 executed, 215 up-to-date
+ pushd examples
~/work/grpc-java/grpc-java/examples ~/work/grpc-java/grpc-java
+ ./gradlew build -x checkUpperBoundDeps -x javadoc -PtargetArch=x86_64 -Pcheckstyle.ignoreFailures=false -PerrorProne=true -PskipAndroid=true -Dorg.gradle.parallel=true

FAILURE: Build failed with an exception.

* What went wrong:
Task 'checkUpperBoundDeps' not found in root project 'examples'.
```


@ejona86 Thank you very much for checking!

**Pull request closed without merging**
