### PR TITLE
remove obsolete truth guava version workaround

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by ejona86** [comment]
We happen to use it only minorly in the classes in testing/ today. But the usages are appropriate and we do use Truth elsewhere. ErrorProne is getting increasingly pushy to use Truth as well.

The reason the dependency matters here is that users will receive the dependency for this library, but none of the others. And we wouldn't want our users to accidentally use a different version of Guava when testing vs running in production.

I'm going to talk with others on the team to figure out our preferred approach.

**Comment by dapengzhang0** [comment]
Tracking issue #5301

**Comment by elharo** [comment]
Where does this stand? Should I close this pull request?

**Comment by ejona86** [comment]
Closing, since we don't want to expose a dependency on truth. Fixing the compileOnly will be tracked by #5301

**Pull request closed without merging**
