### PR TITLE
Bump protobuf to 3.21.1

### LINKED ISSUE #9264: GRPC Uses Outdated Version Of protobuf-java
### What version of gRPC-Java are you using?
1.47.0

It looks like the version of protobuf-java used is outdated. It is version 3.19.2, and there are versions 3.19.4, 3.20.0, 3.20.1, 3.20.0, and 3.20.1 available that dont have vulnerabilities. Would it be possible to upgrade to one of these versions?

### PR DESCRIPTION
**Pull request by ejona86**
Fixes #9264

### CODE REVIEW

**Comment by sergiitk** [comment]
Looks like the build's still broken.

**Comment by ejona86** [comment]
It was a conflict due to Terry's recent Netty upgrade. I had done a push real quick before a meeting hoping Linux would be passing. I know Windows should still be failing due to a build change in Protobuf.

**Comment by sergiitk** [comment]
Restarted java 11 build - it was running out of memory.

**Comment by ejona86** [comment]
https://github.com/protocolbuffers/protobuf/issues/10174 I'm not sure how we'll want to react to the build bug.

**Comment by ejona86** [comment]
@sergiitk, CI is still running, but it seems it is likely working now.

**Review by sergiitk — APPROVED** [review]

**Pull request merged**
