### PR TITLE
Update to Mockito 2

### LINKED ISSUE #5319: Upgrade Mockito dependency to version 2
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
io.grpc:grpc-testing:1.17.1

### What did you expect to see?
To use Mockito version 2.

As of now grpc-java project uses mockito 1.9.X. The last release of 1.9.X is [1.9.10 in 2014](https://github.com/mockito/mockito/releases/tag/v1.10.19).

https://github.com/grpc/grpc-java/blob/ef6b6169f80d14c35775a04daf9f375bd82ce2d4/build.gradle#L236

Would you upgrade the dependency to mockito 2.24.0?
[Mockito upgrade guilde from 1.10 to 2.X](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible-changes-with-110)

## Background

I'm trying to clean up grpc-related conflicting/outdated dependencies. (Example https://github.com/spring-cloud/spring-cloud-sleuth/issues/1186)

### PR DESCRIPTION
**Pull request by TimvdLippe**
This is the public port of cl/238445847

Fixes #5319

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Working on the deprecation warnings as we speak.

**Comment by dapengzhang0** [comment]
@TimvdLippe Thank you for your PR. Please ping me when it's ready for review.

**Comment by dapengzhang0** [comment]
This will resolve #5319

**Comment by TimvdLippe** [comment]
@dapengzhang0 Ready 😄

**Comment by ejona86** [comment]
It looks like this is causing failures during dexing in the android-interop test. I _think_ that one may not be run during presubmit.

https://source.cloud.google.com/results/invocations/dc18ac18-556a-4871-b5ce-78b07f783e9e/log

```
/tmpfs/tmp/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.9.7/8e7d1b599f4943851ffea125fd9780e572727fc0/byte-buddy-agent-1.9.7.jar: D8: Illegal class file: Class module-info is missing a super type.
/tmpfs/tmp/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.9.7/8fea78fea6449e1738b675cb155ce8422661e237/byte-buddy-1.9.7.jar: D8: Illegal class file: Class module-info is missing a super type.
```

**Comment by dapengzhang0** [comment]
Seems need to remove the old Dexmaker dependency and add `org.mockito:mockito-android`

**Comment by TimvdLippe** [comment]
FYI this is the upstream issue: https://github.com/mockito/mockito/issues/1511 It is related to usage of outdated Android tooling. Make sure you are running the latest version of the Android Gradle Plugin.

**Comment by ejona86** [comment]
@TimvdLippe, thanks for the link. That's helpful. So we need to upgrade to com.android.tools.build:gradle:3.3.2. Unfortunately that requires upgrading Gradle to 4.10, which means non-Android is impacted. But since we're on Gradle 4.9 now, it may not be too hard. I'm working on this.

**Comment by dapengzhang0** [comment]
@ejona86 actually I was doing that as well see #5523 #5525

**Pull request merged**
