### PR TITLE
netty: undo commit 6a55e29 as netty's DefaultThreadFactory has been fixed

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by ejona86** [comment]
@buchgr LGTM

**Comment by zhangkun83** [comment]
LGTM

**Comment by buchgr** [comment]
Windows build server seems in trouble

```
* What went wrong:
Execution failed for task ':grpc-core:compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_91 contains a valid JDK installation.
```

**Comment by carl-mastrangelo** [comment]
@buchgr Which netty release was the fix in?    We will need to upgrade it internally as well.

**Comment by buchgr** [comment]
@carl-mastrangelo netty-4.1.0.CR7

**Pull request merged**
