### PR TITLE
Support various JDK versions when choosing the Jetty ALPN version.

### LINKED ISSUE #1497: GRPC tests fail and hang with JDK 1.8.0_73
Making the following change in `build.gradle` gets everything working again:

```
-        def alpnboot_version = '8.1.2.v20141202'
+        def alpnboot_version = '8.1.7.v20160121'
```

However, doing so would probably break the build for developers using an old JDK and for Travis.

Should the [current logic for choosing the ALPN version](https://github.com/grpc/grpc-java/blob/master/build.gradle#L150) accommodate more than one version of Java 8, or is the current approach intentional?

### PR DESCRIPTION
**Pull request by matthild**
This change fixes #1497.

I am totally unfamiliar with Groovy and with Gradle. Probably there is plenty of room for these changes to be more idiomatic.

### CODE REVIEW

**Comment by ejona86** [comment]
okay to test

**Comment by ejona86** [comment]
@matthild, I'm not sure if you noticed, but the logic failed for Travis. I glanced at it and am uncertain why, but it may be an openjdk vs oraclejdk problem. Do note that Travis uses JDK 8; ignore the JDK 7 part at the beginning, we use jdk_switcher.

**Comment by matthild** [comment]
Thanks. I did notice, but haven't had time to fix it yet.

Which version of JDK 8, specifically, does Travis use? And is it an OpenJDK or Oracle JDK?

The use of JDK 8 is really non-obvious in the Travis output -- thanks for clearing that up. I did get as far as downloading & installing the JDK 1.70_76 that the Travis output mentions, but wasn't able to reproduce the problem. I'll try again with the appropriate JDK 8 version once I know what it is.

```
$ java -Xmx32m -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
$ javac -J-Xmx32m -version
javac 1.7.0_76
```

**Comment by ejona86** [comment]
@matthild, no, I don't know what version. Travis-CI isn't that specific [in their docs](https://docs.travis-ci.com/user/ci-environment/#JDK). I'd end up adding a line to before_install in .travis.yml and do a trash-run to see what it reported.

That's most of the reason I didn't comment on this PR earlier, because I wanted to see what the version was. And then I realized I had no time. (Surprise!)

**Comment by ejona86** [comment]
We're going to go with the Jetty ALPN agent instead, in #1760. I think everyone will like it more.

**Comment by matthild** [comment]
Nice! Thanks.

**Pull request closed without merging**
