### PR TITLE
Rename parse and stream to marshal and unmarshal

### LINKED ISSUE #722: Marshaller should use "deserializing" rather than parsing
Javadoc verbiage in the Marshaller should use appropriate negative and positive words.  

Questions raised:
Are parse() and stream() inverses of each other?  (group says yes)
Are serialize and stream inverses of each other?
Should Marshaller use marshal() and unmarshal()?

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #722

### CODE REVIEW

**Comment by zhangkun83** [comment]
Out of my own experience, the first time I the word "marshal", I didn't know what it meant. The fact that `Marshaller` uses "parsing and serialization" in its javadoc indicates that the word "marshal" is not as widely understood as "parse", "serialize" and "deserialize". I would imagine the javadocs of `marshal()` and `unmarshal()` would also need to refer to "serialize" and "deserialize" for users to comprehend. If that's the case, I would just name them as `serialize()` and `deserialize()` instead.

@ejona86 @nmittler @madongfly WDYT?

**Comment by carl-mastrangelo** [comment]
Would you prefer if Marshaller was renamed Serializer?

**Comment by zhangkun83** [comment]
I don't have a strong opinion, but I would keep Marshaller. Serializer seems to have a stronger implication on *it only serializes*, but other people may feel differently.

**Comment by madongfly** [comment]
+1 for `Marshaller`, `Serializer` reminds me the java serialization.

**Comment by ejona86** [comment]
+1 to keeping the name Marshaller. I also agree with @zhangkun83 that we need to use synonyms for "marshal" in the documentation, since many people don't know the word.

How does this fix #722? I thought the main point of #722 was that the JavaDoc is unsymmetric with "parsing and serialization":
> A typed abstraction over message parsing and serialization.

The issue with the method names was then brought up, but fixing the JavaDoc was the part that everyone agreed on.

I'm not sold that there is much of a gain from renaming the methods, or even that the new method names are better than the previous. But I'm not strongly against it.

I do remember that @louiscryan and I discussed the names, in part given that `stream()` returns an `InputStream` and is generally expected to be deferred. That is, it was strange to call a method "marshal" when we would encourage that the marshalling not take place within the method, but instead later when the `InputStream` was read. I do think we felt that the names weren't perfect, but we thought they were "good enough."

**Comment by carl-mastrangelo** [comment]
It seems odd to have a class called Marshaller that lacks a marshal method.  I don't see how the names marshal can be difficult to understand, and at the same time say that Marshaller is desirable.  Aren't these statements at odds with each other?

**Comment by nmittler** [comment]
I definitely agree with @carl-mastrangelo here  ... a `Marshaller` should have methods named `marshal` and `unmarshal`.  Certainly comments may use different terminology, but the method names should be consistent with the class name.

**Comment by ejona86** [comment]
> It seems odd to have a class called Marshaller that lacks a marshal method.

Does InputStream have a stream method? No. But Reader does. Are both of those, "okay?" Yes.

Does java.util.logging.Handler have a handle method? No. But com.sun.net.httpserver.HttpHandler does. Are both of those, "okay?" Yes.

It can be _nice_ to have a method with the same/similar name, but is it "odd" not to? I don't think so. We simply would expect that the methods relate to marshalling, and that is the case here.

And thus, that's why I said: "I'm not sold that there is much of a gain from renaming the methods."

> I don't see how the names marshal can be difficult to understand, and at the same time say that Marshaller is desirable. Aren't these statements at odds with each other?

No, they aren't at odds. Marshaller is an appropriate name for the functionality, but it should probably be defined. The same would be true for channel, call, descriptor, status, transport. Some people have not heard of these terms, or need to know our specific meaning of the term.

I fully expect that some people wouldn't know what a set is (either they are a non-native speaker, didn't go to math class, or wonder what Tennis has to do with it), and behold what its documentation says: "A collection that contains no duplicate elements." The same is true for list: "An ordered collection (also known as a sequence)." It provides both a definition and a rough synonym. And stack: "The Stack class represents a last-in-first-out (LIFO) stack of objects." That is really true for a deque, or a tree, or a bimap/bag, or a dictionary. We use all of these words without thinking and they are good words, but it may be appropriate to help define what it means in case someone doesn't know the word.

**Comment by nmittler** [comment]
Agreed, there are plenty of examples of classes with method names that are inconsistent with the class ... and there are also plenty where they are consistent. The term `marshalling` (or `marshaling` if you're British :)) is pretty ubiquitous however and I think it's worth while to be consistent where we can unless there is a compelling reason not to.  Granted it may be unknown to non-native speakers at first, but so might many other words that we use on a regular basis.  Documentation for the win!

**Comment by carl-mastrangelo** [comment]
The gain here is that it is consistent and predictable.  
- Marshaller has a marshal method
- The inverse of marshal, has a guessable and obvious name: unmarshal

Thingers should be able to thing(), and Fooable() should be able to foo().  It's easy to understand, and you know what you are getting by reading only the name.  

It doesn't matter if Handler doesn't handle().  Just because some other class somewhere else is sloppy with its terminology is no reason to follow its example.  If every method name is special cased because it is *slightly* different than what it does, then we will have an absolutely correct, unnavigable API.

**Comment by ejona86** [comment]
I don't think the \*er convention universally applies; there are things that end in "er" that work better when breaking the rule: Provider, Supplier, Handler, Listener. A less generic example is RateLimiter. I _agree with and like_ the convention, but think it doesn't _have_ to apply here.

This change brings risk. I hope that would be understood. There is a risk to every change.

What would we do with `Metadata.{Ascii,Binary}Marshaller`? They are currently following `Marshaller`'s naming scheme. Do they change to have marshal methods as well? If not, that's odd. If so, we have three different interfaces that only differ by type, which is odd, so we should have a single Marshaller with a generic type. Except then `Metadata.Key.of()` breaks because it is overloaded, and you can't overload based on generics, so we now need to choose new names for the factory methods. We could resolve all that, but what _other_ problems did we not notice and are we sure we would prefer the final result?

The current method names are _reasonable_. Could it be better? Very possibly. But to improve things we would need to change more than just what is included in this PR, which further increases risk. I'm not really willing to take a gamble on this change.

**Comment by nmittler** [comment]
I can't help but feel that the paranoia of risk here seems a little overblown. All we're discussing is changing a couple of method names which are not immediately clear to something that is certainly more clear. Yes, I agree that the other `Marshaller`s should be consistent ... why don't we just update all of them in this PR then? A change this trivial should not be this hard.

**Comment by ejona86** [comment]
Was anyone considering changing `Metadata` before I just now brought it up?

If so, they should have said something, because that is important to understand when reviewing this PR. If not, then that proves my point. If we only made this change and not the change to Metadata, would our API be better? I'd easily claim: no, it would be worse.

**Comment by carl-mastrangelo** [comment]
Metadata should probably be changed too.  What about the following structure:

```
  interface Marshaller<InT, OutT> {
    OutT marshal(InT in);
    InT unmarshal(OutT out);
  }

  StreamMarshaller<M> extends Marshaller<M, InputStream> {
    abstract InputStream stream(M m);
    abstract M parse(InputStream is);
    InputStream marshal(M m) {
      return stream(m); 
    }
    M unmarshal(InputStream is) {
      return parse(is); 
    }
  }
```

This would make it clear that Stream marshaller is intended to work with streams (which stream and parse are inverses), it would still be a marshaller, and it would fit into the MetaData use case.

**Comment by ejona86** [comment]
Meh to a `StreamMarshaller` extending `Marshaller`.

> it would still be a marshaller

But who benefits? Yes, we have this base type, but nobody would use it. Meh.

What happens to AsciiMarshaller vs BinaryMarshaller and Key construction?

**Comment by carl-mastrangelo** [comment]
AsciiMarshaller<M> extends Marshaller<M, String> {
    abstract String toAsciiString(M m);
    abstract M parseAsciiString(InputStream is);
    String marshal(M m) {
      return toAsciiString(m); 
    }
    M unmarshal(String is) {
      return parseAsciiString(is); 
    }
  }

Still Marshals as the name implies, but also has more specific methods.

**Comment by ejona86** [comment]
So the Key constructor would remain unchanged. I simply don't see the benefit, as _nobody_ would use Marshaller at that point; neither our code nor the user's code would use it.

**Comment by carl-mastrangelo** [comment]
You're right, there wouldn't be a point; but didn't you ask what Ascii/Binarymarshaller would look like?   

Just marshal/unmarshal would be my preference.

**Comment by carl-mastrangelo** [comment]
After copious amounts of discussions, it was felt that the method names were fine.  This will be reverted, and trimmed down to just #941

**Pull request closed without merging**
