### PR TITLE
googleapis: Disable xds for google-c2p resolver on Java 8

### PR DESCRIPTION
**Pull request by ejona86**
Java 8 may have a very long life. Since we almost have dropped Java 8
and there's still uncertainty where this code will be needed, disable
the xds path on Java 8 for now. We could still enable Java 8 in the
future, but we should have a plan before doing so.

### CODE REVIEW

**Comment by ejona86** [comment]
We should delay merging this until https://github.com/grpc/grpc/pull/30599 is merged. We will probably find some other places Java 8 is still being used.

**Comment by apolcyn** [comment]
cc @veblush

**Comment by ejona86** [comment]
Ah, yes, I should have CC'ed veblush.

**Comment by veblush** [comment]
@ejona86 Is there a technical requirement to drop Java 8 specifically for this use-case?

**Review by sergiitk — APPROVED** [review]

**Comment by ejona86** [comment]
The reason is "Java 8 may have a very long life." It seems people will be interested in Java 8 at least until 2026 and potentially until 2030.

**Comment by ejona86** [comment]
We will not be doing this.

**Pull request closed without merging**
