### PR TITLE
Sync branch android to head.

### PR DESCRIPTION
**Pull request by madongfly**
@zsurocking

### CODE REVIEW

**Comment by madongfly** [comment]
@ejona86 @zsurocking, just sync, no any additional change, waiting for a LGTM.

**Comment by zsurocking** [comment]
LGTM

**Comment by ejona86** [comment]
Does the android branch still need to be a fork? I seem to remember we cherry-picked some fixes, but if we are syncing to HEAD those should already be included.

**Comment by madongfly** [comment]
This was done per @zsurocking's request, @zsurocking, could you comment on @ejona86's question.

**Comment by ejona86** [comment]
nm... This PR displays differently than I thought it did before. It isn't forked right now, so everything looks fine.

**Pull request merged**
