### PR TITLE
core: Avoid implicit requestConnection in PickFirst

### PR DESCRIPTION
**Pull request by ejona86**
This makes the behavior more clear.

----

Should I also remove the body of Picker.requestConnection?

### CODE REVIEW

**Comment by zhangkun83** [comment]
Yes you can remove the body of Picker.requestConnection?

**Comment by ejona86** [comment]
@zhangkun83, PTAL. Note that there was a bug because of how long ago these changes originated.

**Comment by ejona86** [comment]
Actually. Hold off a sec. In looking to add a test I noticed a test is failing.

**Comment by ejona86** [comment]
PTAL

**Pull request merged**
