### PR TITLE
api: augment CreateSubchannelArgs with custom options

### PR DESCRIPTION
**Pull request by voidzcy**
@zhangkun83 Do we write test for this? Also, do we need a api tracking issue?

### CODE REVIEW

**Comment by zhangkun83** [comment]
Yes, we need to put `@ExperimentalApi("https://github.com/grpc/grpc-java/issues/1771")` on `CreateSubchannelArgs` and the `Builder`, because they are separate pages on javadoc.

**Comment by ejona86** [comment]
LoadBalancer.Key may prove a bit weird, but we'll see where it goes.

**Comment by zhangkun83** [comment]
It's actually `LoadBalancer.CreateSubchannelArgs.Key`. I paid extra attention to it after #5578 :)

**Comment by ejona86** [comment]
Oh, good. I see it now. I just followed the indentation/braces wrong.

**Pull request merged**
