### PR TITLE
netty: Bump netty dep to 4.1.0.Final

### PR DESCRIPTION
**Pull request by ejona86**
Is such a thing even possible? Yes it is.

Note that HTTP/2 in Netty still is not stable, so we remain
version-pinned.

CC @nmittler, @Scottmitch, @normanmaurer. Woooo!!!1

### CODE REVIEW

**Comment by nmittler** [comment]
Ship it!

**Comment by Scottmitch** [comment]
"two more weeks" for 4.1.Final really felt like a long time huh 😉   Thanks for all the support guys!

**Comment by carl-mastrangelo** [comment]
@ejona86 LGTM

**Comment by ejona86** [comment]
@Scottmitch, yeah. It's sort of like how I got back to h2childchannel "next week".

**Comment by normanmaurer** [comment]
LOL :) thanks again for the help

**Pull request merged**
