### PR TITLE
Start 1.0.0 development cycle

### PR DESCRIPTION
**Pull request by ejona86**
CC @dapengzhang0

### CODE REVIEW

**Comment by ejona86** [comment]
Hmm.. I guess I should just instead bump this to 1.0 BECAUSE THERE MUST NOT BE A 0.16. WE WILL NOT DO THAT AGAIN

**Comment by ejona86** [comment]
Swapped to 1.0

**Comment by ejona86** [comment]
Grr... Hold off on reviewing this. It is missing codegen. I forgot I didn't fix things to improve the release process.

**Comment by ejona86** [comment]
Okay. Take 3. This one should build and has codegen update.

**Comment by zhangkun83** [comment]
LGTM

**Pull request merged**
