### PR TITLE
bazel: Use https to download from Maven Central (backport 1.20.x)

### PR DESCRIPTION
**Pull request by virusdave**
This is a moral backport of
https://github.com/grpc/grpc-java/commit/a4299eb6bed3c2f2497f583d0c4620c9f31ec455

### CODE REVIEW

**Comment by virusdave** [comment]
@dapengzhang0 could you take a look at this?  Should be pretty fast, given that it's a back-port of an existing change.

**Comment by virusdave** [comment]
@dapengzhang0 Thanks for merging!  What would it take to get a patch update to this version released?

**Comment by dapengzhang0** [comment]
@virusdave, unfortunately unless the patch is for a security vulnerability, we only make patch for the latest 2 or 3 release.

**Comment by virusdave** [comment]
> @virusdave, unfortunately unless the patch is for a security vulnerability, we only make patch for the latest 2 or 3 release.

Ah, even though due to the maven policy change, without this backport v1.20 is forever unusable now?

**Comment by dapengzhang0** [comment]
Unfortunately, but for bazel you can just reference the commit directly https://github.com/grpc/grpc-java/commit/0f572ae7f36de76112dace93b227eb9d9ed2642c

**Pull request merged**
