### PR TITLE
testing: make all of StreamRecorder threadsafe

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
As seen on a recent jenkins build:

```
java.lang.NullPointerException: t
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
    at io.grpc.Status.fromThrowable(Status.java:405)
    at io.grpc.testing.integration.AbstractInteropTest.deadlineExceededServerStreaming(AbstractInteropTest.java:745)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

Looking into this failure, it look the error is not synchronized like the rest of the class.  Remove any doubt by making it safe.  Additionally, remove the dep on Guava by using AtomicRef instead of Futures.

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
retest this please

**Comment by carl-mastrangelo** [comment]
retest this please

**Comment by carl-mastrangelo** [comment]
retest this please

**Comment by ejona86** [comment]
@carl-mastrangelo, given that master is green and Windows, OS X, and Linux CIs all have Http2OkHttpTest.receivedDataForFinishedStream failing, it seems like it's a problem with this PR.

**Comment by carl-mastrangelo** [comment]
@ejona86 It seems the Stream Observer API wins again.  Apparently, calling onNext() followed by onError()  doesn't actually send the data.  On my machine it works but Jenkins/Travis don't because of the timing between onNext and error.   *sigh*

**Comment by ejona86** [comment]
> Apparently, calling onNext() followed by onError() doesn't actually send the data.

onError becomes cancel(), which clears anything queued. So yeah, it would be racy.

**Comment by carl-mastrangelo** [comment]
@ejona86 PTAL:

I switched the results to be a queue, so that it can be both synchronized upon and provide access to the values.

**Comment by carl-mastrangelo** [comment]
Our use may be threadsafe, but if it is ever going to be used more broadly it will be good to remove any sharp edges.  Before this CL, I don't think it was possible to synchronize reading more than just one message from it.

**Comment by ejona86** [comment]
> if it is ever going to be used more broadly it will be good to remove any sharp edges.

I wouldn't want others to use it. I've been hoping to remove it from testing. It's not a general purpose interface.

> Before this CL, I don't think it was possible to synchronize reading more than just one message from it.

`awaitCompletion()`, then `getValues()`. No races.

**Comment by carl-mastrangelo** [comment]
Right, but you can't wait on one message, then do something, then wait on another message.

**Comment by ejona86** [comment]
> Right, but you can't wait on one message, then do something, then wait on another message.

Which no test was doing, right? I feel like I have a clear understanding of the purpose of this PR.

I'm okay with enhancing our testing utilities for others to use, but it seemed like this PR didn't have that as it's primary goal. And if we're going that route, I'm not sure we should be encouraging `StreamRecorder`.

**Comment by carl-mastrangelo** [comment]
The original intent was:
> Remove any doubt by making it safe.

This class doesn't seem like it would be that bad to support.  The alternative would be people writing their own or using mocks.  I'd rather they use a stream observer designed for testing.  

As long as it is in our repo, why not let it be threadsafe for people who are currently using it?

**Comment by ejona86** [comment]
> I'd rather they use a stream observer designed for testing.

It feels like an internal class to me. It was a quick class to do an immediate need. It's a useful class, but it sort of encourages you to read the implementation.

> why not let it be threadsafe for people who are currently using it

I don't want anyone to use it, I don't want people to think it's a good idea to use it, and I don't want be updating people's code each time we change the API.

**Comment by carl-mastrangelo** [comment]
Would you mind sending a PR to remove it then?  Having unsafe code in our public repo also sends the wrong message.

**Comment by dapengzhang0** [comment]
tracking the original issue at #2687

**Pull request closed without merging**
