### PR TITLE
Remove mimic class io.grpc.internal.MoreThrowables

### PR DESCRIPTION
**Pull request by NickUfer**
The class `io.grpc.internal.MoreThrowables` was added in PR https://github.com/grpc/grpc-java/pull/2751 and should be removed once Guava 20+ was used at runtime.
It basically just mimicked the `com.google.common.base.Throwables#throwIfUnchecked` method and was added because of a rollback to Guava 19 due to incompatibility with other libraries.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @NickUfer isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by NickUfer** [comment]
I signed it

**Comment by ejona86** [comment]
Hmm... @NickUfer, the CLA checker still isn't happy. Might you have signed the CLA with a different email than used for git/github?

**Comment by NickUfer** [comment]
I signed it

**Comment by NickUfer** [comment]
I signed it

**Comment by NickUfer** [comment]
I signed it

**Comment by NickUfer** [comment]
I signed it

**Comment by NickUfer** [comment]
> Hmm... @NickUfer, the CLA checker still isn't happy. Might you have signed the CLA with a different email than used for git/github?

Now I've got it :+1:

**Comment by ejona86** [comment]
@NickUfer, thank you!

**Pull request merged**
