### PR TITLE
 core: always do SRV record lookup in DnsNameResolver

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Instead of failing after a a missing A/AAAA record, this change
makes the resolver keep going and try out SRV records too.  This
is needed for use with ALTS, and is part of the gRPCLB spec.

This change also moved the JNDI code to a separate, reflectively
loaded file.  This makes it easy to exclude the file and not worry
about the missing class references on Android.  Additionally, if
javax.naming might be available on Android, this allows it to be
loaded.  A key side effect of this is that DnsNameResolver is
smaller, and more cleanly tested.

### CODE REVIEW

**Comment by zhangkun83** [comment]
*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 90 at r1](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFKJGQ-8Fhe3qfgrm1t:-LFKJGQ04bddAsl750IT:b-qsyuya) ([raw file](https://github.com/grpc/grpc-java/blob/c77c4bbde79c48bb122459b45e8332d97be8089b/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L90)):*
> ```Java
>   static boolean enableJndi = Boolean.parseBoolean(JNDI_PROPERTY);
> 
>   private static ResourceResolverFactory resourceResolverFactory =
> ```

final?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-java/4565)*

**Comment by zhangkun83** [comment]
*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 197 at r1](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFNrAKJ5Pd-h0hFvFjk:-LFNrAKJ5Pd-h0hFvFjl:bna59km) ([raw file](https://github.com/grpc/grpc-java/blob/c77c4bbde79c48bb122459b45e8332d97be8089b/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L197)):*
> ```Java
>           }
>           if (enableJndi && resourceResolver.get() == null) {
>             resourceResolver.compareAndSet(null, resourceResolverFactory.newResourceResolver());
> ```

newResourceResolver() may throw and it's not caught. An uncaught exception will be logged by the executor at best, but the application will not be notified.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-java/4565)*

**Comment by zhangkun83** [comment]
*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 277 at r1](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFNtL0hChuPR0XzLjpM:-LFNtL0hChuPR0XzLjpN:b-cb5nw5) ([raw file](https://github.com/grpc/grpc-java/blob/c77c4bbde79c48bb122459b45e8332d97be8089b/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L277)):*
> ```Java
> 
>   @VisibleForTesting
>   static final class ResourceResolverFactory {
> ```

You may want to make this an interface, so that you can mock it and test DnsNameResolver's behavior when newResourceResolver() throws and returns null.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-java/4565)*

**Comment by zhangkun83** [comment]
*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 306 at r1](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFP9Vpc38hrHZqziU-z:-LFP9Vpc38hrHZqziU0-:b-pd3i9w) ([raw file](https://github.com/grpc/grpc-java/blob/c77c4bbde79c48bb122459b45e8332d97be8089b/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L306)):*
> ```Java
>         ResourceResolver resourceResolver;
>         try {
>           resourceResolver = jndiCtor.newInstance();
> ```

Do you intend to have two places that call jndiCtor.newInstance()?
It will cause a bit behavioral inconsistency: if newIntance() throws here, newResourceResolver() will return null; if newIntance() throws in newResourceResolver(), it will throw.
Why not delete this one, and make jndiUnavailabilityCause a volatile that is settable from newResourceResolver()?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-java/4565)*

**Comment by carl-mastrangelo** [comment]
@zhangkun83 Since I can't comment on your comments from Github, I'll say "done" to most of them.  

I refactored the Factory as an interface and moved the implementaion to JndiResourceResolverFactory.  This also moves the unavailability Cause to the factory (which makes more sense).

**Comment by zhangkun83** [comment]
Reviewed 1 of 4 files at r1, 2 of 4 files at r2.
Review status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @carl-mastrangelo and @zhangkun83)

---

*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 538 at r1](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFTkoNa8PCGRDA14qsP:-LFTkoNb7z7Kfh4iCgDo:b-npbfd8) ([raw file](https://github.com/grpc/grpc-java/blob/c77c4bbde79c48bb122459b45e8332d97be8089b/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L538)):*
> ```Java
> 
>   /**
>    * RRResolver is a Dns ResourceRecord resolver.
> ```

RRResolver?

---

*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 90 at r2](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFbxyDR584pBjXabB4i:-LFbxyDR584pBjXabB4j:bidx0jr) ([raw file](https://github.com/grpc/grpc-java/blob/ae8da12cf4f8b8aeef0c9baf37da434a24b58fd1/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L90)):*
> ```Java
>   static boolean enableJndi = Boolean.parseBoolean(JNDI_PROPERTY);
> 
>   private static final AtomicReference<ResourceResolverFactory> resourceResolverFactory =
> ```

It doesn't seem resourceResolverFactory is modified anywhere. Why AtomicReference?

---

*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 461 at r2](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFUuFYN2HFLvBEVN0tI:-LFUuFYN2HFLvBEVN0tJ:bsoi17p) ([raw file](https://github.com/grpc/grpc-java/blob/ae8da12cf4f8b8aeef0c9baf37da434a24b58fd1/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L461)):*
> ```Java
>   }
> 
>   interface ResourceResolverFactory {
> ```

Please document the methods, e.g., in what cases they will return null, whether they will throw IllegalStateException.

---

*[core/src/main/java/io/grpc/internal/DnsNameResolver.java, line 493 at r2](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFbzTXd-BuWj_2Ola63:-LFbzTXd-BuWj_2Ola64:butgevw) ([raw file](https://github.com/grpc/grpc-java/blob/ae8da12cf4f8b8aeef0c9baf37da434a24b58fd1/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L493)):*
> ```Java
>   }
> 
>   private ResourceResolver getResourceResolver() {
> ```

@Nullable

---

*[core/src/test/java/io/grpc/internal/DnsNameResolverTest.java, line 164 at r2](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFdMwkrAcJdC5uYIA9J:-LFdMwkrAcJdC5uYIA9K:bmapfak) ([raw file](https://github.com/grpc/grpc-java/blob/ae8da12cf4f8b8aeef0c9baf37da434a24b58fd1/core/src/test/java/io/grpc/internal/DnsNameResolverTest.java#L164)):*
> ```Java
> 
>     DnsNameResolver resolver = newResolver(name, 81);
>     resolver.setAddressResolver(new AddressResolver() {
> ```

This can be done simply using mocks:
when(mockAddressResovler.resolveAddress(anyString()).thenReturn(answer1, answer2);

Then at the end:
verify(mockAddressResovler, times(2)).resolveAddress(anyString());

Ditto for the mocks in other tests.

---

*[core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java, line 103 at r2](https://reviewable.io/reviews/grpc/grpc-java/4565#-LFc-ce3EqYxepG89Lmq:-LFc-ce3EqYxepG89Lmr:b-jznhmg) ([raw file](https://github.com/grpc/grpc-java/blob/ae8da12cf4f8b8aeef0c9baf37da434a24b58fd1/core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java#L103)):*
> ```Java
>     private static final Pattern whitespace = Pattern.compile("\\s+");
> 
>     JndiResourceResolver() {}
> ```

Why is this empty constructor needed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc-java/4565)*

**Comment by carl-mastrangelo** [comment]
re: Comments

> RRResolver?

Done

> It doesn't seem resourceResolverFactory is modified anywhere. Why AtomicReference?

It was going to be settable for testing, but not with the RR setter in place.

>Please document the methods, e.g., in what cases they will return null, whether they will throw IllegalStateException.

Added docs

> @nullable

done

> This can be done simply using mocks:

Done, though I don't think the code is any easier or more maintainable.




> Why is this empty constructor needed?

It makes the constructor non public, which it would otherwise be.

**Comment by zhangkun83** [comment]
> It makes the constructor non public, which it would otherwise be.

I know.. But the class is non public already, what difference does a constructor of the same visibility make?

**Pull request merged**
