### PR TITLE
Synchronize benchmarking protos with grpc/grpc

### PR DESCRIPTION
**Pull request by louiscryan**
First phase in make java capable of being used in the cross-lang benchmarking suite

### CODE REVIEW

**Comment by louiscryan** [comment]
@nmittler

**Comment by ejona86** [comment]
The generated code is supposed to be checked in.

**Comment by nmittler** [comment]
Yeah, check in the generated code then LGTM

**Comment by ejona86** [comment]
AsyncServer.java has weird indendation on a builder.

**Comment by louiscryan** [comment]
All should be fixed now

**Comment by nmittler** [comment]
LGTM

**Comment by ejona86** [comment]
@louiscryan LGTM

**Comment by ejona86** [comment]
@louiscryan, FYI, you're now modifying this old PR.

**Comment by louiscryan** [comment]
yeah, saw that and then closed the PR

**Pull request closed without merging**
