### PR TITLE
Release v1.66.0

### PR DESCRIPTION
**Pull request by kannanjgithub**

### CODE REVIEW

**Comment by kannanjgithub** [comment]
Why it is showing as can't automatically merge - the master branch of my fork has the commits in [this PR](https://github.com/grpc/grpc-java/pull/11424) for reapplying the reverted onResult2 changes but not the release-v1.66.0 branch. Let me know if I should drop those commits to make it auto-mergeable.

**Comment by ejona86** [comment]
The problem is the PR was targeting the wrong branch. I just changed it to the v1.66.x branch ("Edit" at top right, then change the drop-down for the branch on the next line).

**Comment by kannanjgithub** [comment]
> The problem is the PR was targeting the wrong branch. I just changed it to the v1.66.x branch ("Edit" at top right, then change the drop-down for the branch on the next line).

I see, thanks.

**Comment by ejona86** [comment]
Note: The process does not let you create this ahead of time. When you create this, the commits are fixed as we _don't_ rebase back into the branch. So you'll need to either rebase this yourself and fix up the various references (like the tag), or you'll need to delete it all and start over when it is time for the release.

**Comment by kannanjgithub** [comment]
> We should commit `Revert "Start 1.67.0 development cycle (grpc#11416)"` separately nowish, separately from the release process. There's no benefit to keeping the branch broken in that way.

Yes, can you please approve that PR? I was going to merge this PR only after that is merged. Is that what you mean separate from the release process or something else?

**Comment by kannanjgithub** [comment]
> We should commit `Revert "Start 1.67.0 development cycle (grpc#11416)"` separately nowish, separately from the release process. There's no benefit to keeping the branch broken in that way.

Yes, can you please approve that PR? I was going to merge this PR only after that is merged. Is that what you meant by separate from the release process or something else?

**Comment by ejona86** [comment]
> Yes, can you please approve that PR?

I didn't see it. You should have added me as a reviewer.

**Comment by kannanjgithub** [comment]
> Note: The process does not let you create this ahead of time. When you create this, the commits are fixed as we _don't_ rebase back into the branch. So you'll need to either rebase this yourself and fix up the various references (like the tag), or you'll need to delete it all and start over when it is time for the release.

From reading [Tagging the release](https://github.com/grpc/grpc-java/blob/master/RELEASING.md#tagging-the-release) I thought once the PR is approved I could run the commands at step 6 to push the changes. But when you say 'time for the release' it sounds like a later point in time and I should wait to execute the commands in step 6 ?

**Comment by ejona86** [comment]
> From reading [Tagging the release](https://github.com/grpc/grpc-java/blob/master/RELEASING.md#tagging-the-release) I thought once the PR is approved I could run the commands at step 6 to push the changes.

You could, if it were time to make the release. But you've started the entire tagging process early. It's been two days since the branch cut. Wait... the branch cut wasn't done typically either. It's been a week since the cut because it seems you didn't wait for the version bump to be committed before making the branch. That's going to make it more confusing than normal. And it also means there are other backports to be made.

But these release commits are not "merged" into the release branch. They are taken exactly as they are (what you see in your release-v1.66.0 branch _is_ the release), so you would know exactly what would be in the release. But that means it _won't_ include the recent backports.

**Comment by kannanjgithub** [comment]
> The branch cut wasn't done typically either. It's been a week since the cut because it seems you didn't wait for the version bump to be committed before making the branch. That's going to make it more confusing than normal. And it also means there are other backports to be made.

I haven't understood the backports problem - I thought since step 4 uses the commit previous to the 'Start 1.67.0 development cycle' to create the branch, so the branch (no matter when I create) is cut at this previous commit?
Are you saying in these [steps](https://github.com/grpc/grpc-java/blob/master/RELEASING.md#branching-the-release) branching the release I didn't wait for the step 3 of submission before I created the release branch in step 4? I'm aware there was a problem in the v1.66.0 branch initially since it also included the commit for 'Start 1.67.0 development cycle' but hasn't the revert of that commit moved the branch cut to the commit prior to that?

**Comment by ejona86** [comment]
:-/ #11273 isn't merged yet.

> I thought since step 4 uses the commit previous to the 'Start 1.67.0 development cycle' to create the branch, so the branch (no matter when I create) is cut at this previous commit?

But you did that in your local repo before the PR was merged. And you should have experienced a problem, because the commit wasn't on upstream/master. Maybe it erred and you kept going, and that's how the commit got on the release branch.

It definitely matters what commits you are looking at, because when you merge a PR on github it creates a _new_ commit, and that new commit is the one that the branch should have been based on.

> I'm aware there was a problem in the v1.66.0 branch initially since it also included the commit for 'Start 1.67.0 development cycle' but hasn't the revert of that commit moved the branch cut to the commit prior to that?

The problem is there are two different 'Start 1.67.0 development cycle' commits. They have different parents, so they are different "cut" points. So it isn't just "that commit shouldn't have been on the branch" but the _parent_ of that commit is what we care about. So the branch ended up being cut earlier than it appears from master.

That's _okay_, as long as we know it is happening and can account for it. It just makes it easier to miss commits (one commit had been missed).

**Comment by kannanjgithub** [comment]
Should we necessarily continue with the currently created release branches as we have identified problems in the way they were created? Can we just delete the created branches for v1.66 and starting all over again? That would move the branch cut date to the present date, but is there any particular issue in that?

**Comment by ejona86** [comment]
> Can we just delete the created branches for v1.66 and starting all over again?

Yes, you can. The most important thing is to make sure you delete the v1.66.0 tag in your local repository. We don't want to use the wrong tag for the release.

**Comment by kannanjgithub** [comment]
Ok, about deleting the branch, do I delete the v1.66.x branch upstream with
       git push -d upstream v1.66.x
and recreate it properly with the commit prior to starting the 1.67.0
development cycle.
I have deleted the branch on my fork with "git push -d origin v1.66.x"

**Comment by kannanjgithub** [comment]
I tried it anyway but I get this error

***@***.***:~/grpc-java$ git push -d upstream v1.66.x
remote: error: GH006: Protected branch update failed for refs/heads/v1.66.x.
remote: error: Cannot delete this branch
To https://github.com/grpc/grpc-java.git
 ! [remote rejected]     v1.66.x (protected branch hook declined)
error: failed to push some refs to 'https://github.com/grpc/grpc-java.git'

**Comment by ejona86** [comment]
> Ok, about deleting the branch, do I delete the v1.66.x branch upstream with

No. We'll live with upstream/v1.66.x. We've already fixed it up. The only problem right now is your `release-v1.66.0` branch, locally and in `origin`, along with the `v1.66.0` tag you probably created.

**Pull request closed without merging**
