### PR TITLE
xds: separate client and server side XdsClient implementations

### PR DESCRIPTION
**Pull request by voidzcy**
See go/separate-client-server-xds-client

I think this refactoring is beneficial even if we eventually use a single XdsClient instance running for both client and server side usage at the same time (we could still easily merge `ClientXdsClient` and `ServerXdsClient` easily), as `AbstractXdsClient` layer abstracts away the logic of sending/receiving xDS requests/responses, ADS stream retry, etc from the business logic of handling xDS responses. It significantly simplifies implementations of operations like adding/removing watchers, handling responses, etc.

- Some implementations in the original XdsClientImpl2 are cleaned up:
  - `DiscoveryRequestData` and `DiscoveryResponseData` has little value, as they are just regroupings of `DiscoveryRequest` and `DiscoveryResponse` proto messages (converting `DiscoveryRequest` to `DiscoveryRequestData` just repackages internal fields into a new class and nothing more, same for the other direction conversion). We could just make each field data inside as individual arguments for methods.

  - Updating resource versions for accepted resources and nonces for received messages in the original implementation is messy, which made `AbstractAdsStream.sendXdsRequest()`, `AbstractAdsStream.sendAckRequest()` and `AbstractAdsStream.sendNackRequest()` verbose. Now we are making much cleaner APIs:
    - `AbstractAdsStream.sendDiscoveryRequest(type, resources)`: takes the latest version and nonce from saved values and calls the overloaded `sendDiscoveryRequest`.
    - `AbstractAdsStream.sendDiscoveryRequest(type, version, resources, nonce, errorDetail)` (overloaded): sends an xDS request with the given arguments.
    - `AbstractXdsClient.ackRequest(type, version, nonce)`: ACK with the specific version and nonce as given. This gives better semantics for ACKing a specific xDS response (nonce). The version is used to update the saved value (the memorized last accepted version)
    -   `AbstractXdsClient.nackRequest(type, nonce, errorDetail)`: NACK with the specific nonce as given. This gives better semantics for NACKing a specific xDS response (nonce). It takes the the memorized last accepted version for sending the NACK request.

(As a reminder, version applies to a resource, a resource of type LDS version 2 uniquely represents the resource data; nonce applies to a request/response, a request/response can be uniquely identified by its resource type and nonce).

Some relevant changes made:
- Changed the way how the `LoadReportClient` instance is created. Previously, the `LoadReportClient` instance is created (and started) in the first call of `XdsClient.reportClientStats()`. Now it is created in the constructor of the XdsClient (aka, same lifecycle) and starts load reporting RPC in the first call of `XdsClient.reportClientStats()`. Creating the `LoadReportClient` instance is a cheap operation, the LRS stub is created only when it starts. `LoadReportClient` supports starting/stopping for. multiple times. So there is no problem for `XdsClient.reportClientStats()` and `XdsClient.cancelClientStatsReport()` to be called for multiple times that turns on and off load reporting.

Currently, there are some imperfectness:
- `Node` in `AbstractXdsClient` unfortunately needs to be visible for child classes.
  - `ServerXdsClient` currently has some special hacks to put some node metadata for resource discovery. After that is resolved, `Node` will be `AbstractXdsClient` private.

`ClientXdsClientTest` is ported from `XdsClientImplTest2` and `ServerXdsClientTest` is ported from `XdsClientImplTestForListener`.

/cc

@dapengzhang0 @sanjaypujare

### CODE REVIEW

**Comment by voidzcy** [comment]
This separation may still be not satisfactory, we may need to eliminate the usage of SynchronizationContext completely and use locks instead for the context of sharing XdsClient between channels.

**Comment by sanjaypujare** [comment]
> This separation may still be not satisfactory, we may need to eliminate the usage of SynchronizationContext completely and use locks instead for the context of sharing XdsClient between channels.

Can you add some explanation as to why?

**Comment by voidzcy** [comment]
> > This separation may still be not satisfactory, we may need to eliminate the usage of SynchronizationContext completely and use locks instead for the context of sharing XdsClient between channels.
> 
> Can you add some explanation as to why?

For the client side usage across gRPC channels, the XdsClient needs to be thread-safe for calls entering from both the LB policy side (aka, XdsClient APIs) and the xDS RPC (aka, xDS responses) side. We can't just simply create a SynchronizationContext and execute XdsClient APIs in it, as some APIs must be blocking (e.g., retrieving stats objects). SynchronizationContext serializes things asynchronously. It may also be problematic to mix SynchronizationContext and locks, as tasks running in SynchronizationContext may hold the lock for unnecessarily long time. C-core achieves thread-safety by [purely using locks](https://github.com/grpc/grpc/pull/24200), which is much trickier than simply running everything in a SynchronizationContext.

We may need to duplicate XdsClientImpl for client and server usages, if we are not able to abstract the common part nicely. Server side needs more changes for using an XdsClient that runs asynchronously.

**Comment by sanjaypujare** [comment]
> ...
> We may need to duplicate XdsClientImpl for client and server usages, if we are not able to abstract the common part nicely. Server side needs more changes for using an XdsClient that runs asynchronously.

More changes coming in this PR? Or can it be reviewed now?

**Comment by voidzcy** [comment]
> > ...
> > We may need to duplicate XdsClientImpl for client and server usages, if we are not able to abstract the common part nicely. Server side needs more changes for using an XdsClient that runs asynchronously.
> 
> More changes coming in this PR? Or can it be reviewed now?

Please hold a moment. I am trying to change the way for working with two separate synchronizations (client side is using locks and server side keeps using SynchronizationContext). If that works, I will send it out. If not, we have do duplicate XdsClientImp for client and server.

**Comment by voidzcy** [comment]
This PR provides the idea of separating split codepaths into separate XdsClient classes for client and server side usages. #7533 adds synchronization and API thread-safety to the client usage, which is intended to be used for sharing the XdsClient instance between Channels. Please review #7533 directly for speeding up the process.

**Comment by markdroth** [comment]
Just a couple of quick drive-by comments (I have not looked at the code):

> I am trying to change the way for working with two separate synchronizations (client side is using locks and server side keeps using SynchronizationContext).

Does Java use a separate SynchronizationContext for each server?  If so, it seems like you'll need the same synchronization approach on the server as on the client, since we ultimately want the XdsClient to be shared between all clients and all servers.

> This PR provides the idea of separating split codepaths into separate XdsClient classes for client and server side usages.

Note that Sanjay's current code for the server-side integration is temporary.  In the long term, we want to use the same listener-watcher API on both the client and server, so there should not be any server-specific APIs.

**Comment by voidzcy** [comment]
> Just a couple of quick drive-by comments (I have not looked at the code):
> 
> > I am trying to change the way for working with two separate synchronizations (client side is using locks and server side keeps using SynchronizationContext).
> 
> Does Java use a separate SynchronizationContext for each server? If so, it seems like you'll need the same synchronization approach on the server as on the client, since we ultimately want the XdsClient to be shared between all clients and all servers.
> 
> > This PR provides the idea of separating split codepaths into separate XdsClient classes for client and server side usages.
> 
> Note that Sanjay's current code for the server-side integration is temporary. In the long term, we want to use the same listener-watcher API on both the client and server, so there should not be any server-specific APIs.

Yeah, I am aware how it should eventually work. Our existing problem is Sanjay's code is too diverged from what we have implemented for the client's usage (e.g., it only support a single watcher; it doesn't have remove watcher API and assume once the watcher is added, it will never be removed; it does not cache any response data as it only support a single watcher; it is using wildcard mode for Listener subscription; everything runs in the SynchronizationContext created by the server, etc). So although his code is currently put together inside the XdsClient implementation, it actually runs in a separate codepath that has some fields used in common. Still a lot needs to be done for server side's code to catch up what's being supported on the client side's usage. We are putting the split codepath into separate classes for now, so client and server are creating different XdsClients (different implementations but sharing the common part, i.e., ADS stream's logic). This code separation is mainly for maintainability purposes due to the different development stages that client and server's implementations are currently at. Once Sanjay's code works more aligned to how the client side's implementation is doing, it can be easily combined back to make a single XdsClient instance work for both client and server at the same time.

**Pull request closed without merging**
