### PR TITLE
Enhance java-code-generator, supply option param to create stub.

### PR DESCRIPTION
**Pull request by horizonzy**

### CODE REVIEW

**Comment by dapengzhang0** [comment]
What's the reason you want to adde this feature? In most cases, it can be achieved using current generated stub and methods in [`AbstractStub`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html).

**Comment by horizonzy** [comment]
> What's the reason you want to adde this feature? In most cases, it can be achieved using current generated stub and methods in [`AbstractStub`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html).

image

getStub with option directly, make it more convenient.

**Comment by dapengzhang0** [comment]
> getStub with option directly, make it more convenient.

For that usecase, you can have 

```java
stub = HelloServiceGrpc.newBlockingStub(channel).withDeadlineAfter(3000L, MILLISECONDS);
```

Adding more generated code will increase the size of a lot of application binaries using gRPC.

**Comment by horizonzy** [comment]
Thanks for your suggestion.

**Pull request closed without merging**
