### PR TITLE
Added google.api.http options to health.proto

### LINKED ISSUE #4356: Increment rest endpoint for health.proto
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Using gRPC 1.9.0

### What did you expect to see?
If it were possible to implement the health.proto service as REST interface too, it would minimize the duplication and generation of protofiles when using together with the repository of gRPC-gateway( https://github.com/grpc-ecosystem/grpc-gateway).

### PR DESCRIPTION
**Pull request by iaguera**
- Added go lang package.
  - http informations on health proto file.

Closes #4356

### CODE REVIEW

**Comment by ejona86** [comment]
As mentioned in #4356, even once this is ready for Java there will need to be coordination with other languages. Given the dependency troubles we've had in the past, I expect some difficulty. Most of the trouble is there's just so many languages involved.

**Comment by ejona86** [comment]
FYI: I shouldn't really look at the changes until the CLA is signed.

**Comment by carl-mastrangelo** [comment]
Also FYI: https://github.com/googleapis/api-common-protos/pull/1

**Comment by zpencer** [comment]
Hi @iaguera friendly ping on updates to this PR. Note there is still a need to coordinate with other languages and submit the same changes to the grpc/grpc-proto repo, which we keep the most updated copy of the protos.

**Comment by dapengzhang0** [comment]
@iaguera Thank you for your PR. However, we should close this one because from now on any changes to services proto files should be done in https://github.com/grpc/grpc-proto first.

**Pull request closed without merging**
