### PR TITLE
Improve emulated linux aarch64 tests, without protoc artifact build

### PR DESCRIPTION
**Pull request by jtattermusch**
Same as https://github.com/grpc/grpc-java/pull/8096 but excludes the controversial parts (protoc artifact build).

Based on my testing, the tests are currently flaky, so it would be better to first merge it and start running it continuously to asses the situation.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@ejona86

**Comment by jtattermusch** [comment]
Example of test failures I'm getting:

https://source.cloud.google.com/results/invocations/40e2d7cd-7cf1-464c-b453-ea02da9a31d5/log

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
Those failures look like a different TLS provider is being used (seemingly Conscrypt instead of netty-tcnative). It looks like we are using the uberjar of netty-tcnative, which contains aarch64, so I don't know why that would be. Fine to kick down the road for the moment.

**Comment by jtattermusch** [comment]
Sg, can you merge? I don't have the merge button.

**Pull request merged**
