### PR TITLE
xds: Implement ignore_resource_deletion server feature

### PR DESCRIPTION
**Pull request by erikjoh**
As defined in the [A53](https://github.com/grpc/proposal/blob/master/A53-xds-ignore-resource-deletion.md#proposal) proposal.

### CODE REVIEW

**Comment by erikjoh** [comment]
This should only be missing some tests.

**Comment by erikjoh** [comment]
@sergiitk I heard that you may have started on this already. If so feel free to close this PR!

**Comment by sergiitk** [comment]
Oh, wow you're ahead of me. I'll take a look at what can be salvaged.

**Comment by sergiitk** [comment]
We're not that far off: https://github.com/grpc/grpc-java/compare/master...sergiitk:grpc-java:xds-ignore_resource_deletion

I also need to implement the tests, but I was going to do the tests prior to the main impl (TDD).

**Comment by erikjoh** [comment]
Nice!
I've only done a manual test of this implementation so it's possible I'm missing some edge case.
I'll close this then and also thanks for working on this feature! 😃

**Comment by sergiitk** [comment]
Superseded by https://github.com/grpc/grpc-java/pull/9339.

**Pull request closed without merging**
