### PR TITLE
buildscripts: Add bootstrap generator to cron job that runs nightly

### PR DESCRIPTION
**Pull request by zasweq**

### CODE REVIEW

**Review by ejona86 — APPROVED** [review]
Is this safe to merge?

**Comment by zasweq** [comment]
Let's wait until a manual run passes.

**Comment by sergiitk** [comment]
- [ ] [grpc/java/master/branch/xds_k8s_lb](https://source.cloud.google.com/results/invocations/facdaa3e-039d-43be-b2bc-5472a7c46696)

**Comment by zasweq** [comment]
Woohoo!

**Pull request merged**
