### PR TITLE
xds: only check authority not host for xds name resolver

### PR DESCRIPTION
**Pull request by dapengzhang0**
Our backend address used in the demo env on GCP does not have a valid host value, all we need seems a valid authority.

### CODE REVIEW

**Comment by voidzcy** [comment]
Should we only make this change to `xds_demo` branch?

**Comment by dapengzhang0** [comment]
Is host required in any xds/envoy spec? Javadoc https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getHost() says `getHost()` reuturns "null if the host is undefined".

**Comment by voidzcy** [comment]
> Is host required in any xds/envoy spec? Javadoc https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getHost() says `getHost()` reuturns "null if the host is undefined".

According to [[RFC3986], Section 3.2](https://tools.ietf.org/html/rfc3986#section-3.2), `host` is a (required) subcomponent of `authority`.
> authority   = [ userinfo "@" ] host [ ":" port ]

So I believe [these two checks](https://github.com/grpc/grpc-java/blob/master/xds/src/main/java/io/grpc/xds/XdsNameResolver.java#L72-L75) are necessary.

**Comment by dapengzhang0** [comment]
Seems LDS need to match host, so host is actually needed.

**Pull request closed without merging**
