### PR TITLE
Avoid flushing the stream after writing a message in case the server returns a single response

### LINKED ISSUE #4884: Avoid unnecessary flushes for unary responses
We currently optimize flushes for unary requests on client-side, by delaying flushing until the end of the RPC. When looking at the code, I realized [it doesn't appear we're doing that for server-side](https://github.com/grpc/grpc-java/blob/60a0b0c/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L140).

Using wireshare with the interop client/server with empty_unary, we can see a single packet for the request but three packets for the response:
too many server flushes

We should optimize the response flow so that all three frames are sent with a single flush.

### PR DESCRIPTION
**Pull request by amirhadadi**
Resolves #4884

### CODE REVIEW

**Comment by ejona86** [comment]
Have you confirmed whether this makes a difference with a packet dump?

Digging into the code, it seems this could improve things, but only because we already have this optimization later on in the write path:
https://github.com/grpc/grpc-java/blob/428b541114adb6c9830fbe877cc922533a6cb4d5/core/src/main/java/io/grpc/internal/AbstractServerStream.java#L109-L111

**Comment by ejona86** [comment]
Yeah, I think this just may work. This was what I thought was the hard part! But the plumbing in the transport already has a solution!

Delaying the flush for the initial response should be relatively easy and similar to client-side. We just need to use `false` instead of `true` for the flush argument here:
https://github.com/grpc/grpc-java/blob/428b541114adb6c9830fbe877cc922533a6cb4d5/netty/src/main/java/io/grpc/netty/NettyServerStream.java#L99-L103

(That's fine as a separate PR)

**Comment by amirhadadi** [comment]
> Have you confirmed whether this makes a difference with a packet dump?

It seems to create the same number of packets. Maybe if the message body + trailers were aggregated into a single netty object before flushing it would make it a single packet? I don't have enough Netty know how to tell.
However, it does eliminate one flush and ends up with a single system call for writing out the data instead of 2.

> Digging into the code, it seems this could improve things, but only because we already have this optimization later on in the write path:

From what I gather, this optimization is not applicable. The call to `stream.flush()` ends up calling `commitToSink(false, true)`, so flush is performed.

**Comment by amirhadadi** [comment]
> Delaying the flush for the initial response should be relatively easy and similar to client-side. We just need to use false instead of true for the flush argument here:

Would that require the `serverSendsOneMessage` check?

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
> Would that require the serverSendsOneMessage check?

Yes, it would.

> If it does, I guess we need to change this argument to false and move the decision whether to flush over here?

I thought we'd just do it in io.grpc.netty, not in the ServerCall. But I see now, NettyServerStream doesn't have access to the MethodDescriptor like NettyClientStream does. That's because it is determined later, after the call starts. We could either pass the method descriptor down into the server stream using a new method, or plumb the decision down in writeHeaders(). It makes sense to me to pass the flush decision as an argument to writeHeaders(). (That'd differ from client-side, but really, we could do the same thing on client-side and it wouldn't be bad.)

**Review by YifeiZhuang — APPROVED** [review]

**Pull request merged**
