### PR TITLE
Modified netty-shaded resources to enable successful compilation into a native image.

### LINKED ISSUE #10601: grpc-netty-shaded cannot be successfully compiled under GraalVM
### What version of gRPC-Java are you using?
grpc-netty-shaded-1.58.0

### What is your environment?

+ operating system: Both Ubuntu 11.3.0 and Windows 10
+ jdk: GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22)

### What did you expect to see?
successfully compiled under GraalVM

### What did you see instead?
compiled failed under GraalVM

### Steps to reproduce the bug
1. clone the repo https://github.com/zenghu1chen/graalvm-grpc and execute `cd graalvm-grpc`
2. execute `mvn clean -Pnative native:compile`

My project has been recently trying to use GraalVM. Due to the use of the grpc-netty-shaded package, the compilation has been unable to pass. I only recently found out about this issue.
My current temporary solution is to delete the `META-INF/native-image` folder. It seems to work fine, but I'm not sure if it's appropriate.

### PR DESCRIPTION
**Pull request by zenghu1chen**
This modification will delete all configuration files under the META-INF/native-image/io.netty folder. During testing, these configuration files will prevent successful compilation of the native image.
Fixes #10601

### CODE REVIEW

**Comment by sanjaypujare** [comment]
tip: @zenghu1chen pls don't name your source branch `master` .  Normally it is named to reflect the work being done. The problem with `master` is that it conflicts with origin/master or upstream/master in case someone fetches your repo to review it

**Comment by sanjaypujare** [comment]
@zenghu1chen couple of points: did you look at the original issue https://github.com/grpc/grpc-java/issues/7540 because of which @dzou made a change in https://github.com/grpc/grpc-java/pull/8258 ? Will your change reintroduce issue #7540?

**Review by sanjaypujare — CHANGES_REQUESTED** [review]
Need to ensure this does not reintroduce the issue https://github.com/grpc/grpc-java/issues/7540 . Would like @dzou to review this PR

**Comment by zenghu1chen** [comment]
> tip: @zenghu1chen pls don't name your source branch `master` . Normally it is named to reflect the work being done. The problem with `master` is that it conflicts with origin/master or upstream/master in case someone fetches your repo to review it


Sorry, I haven't submitted many PRs, does this mean it's better to open a new PR?

**Comment by zenghu1chen** [comment]
> @zenghu1chen couple of points: did you look at the original issue #7540 because of which @dzou made a change in #8258 ? Will your change reintroduce issue #7540? Also it looks like with your changes the class `NettyResourceTransformer` is effectively a no-op. Is it then the same as removing it and removing the reference to it in `transform` on line 92?

@sanjaypujare  By default, the shadow project will copy all configuration files, and if there is no `transform`, the native-image related configuration will still exist and affect the compilation.

**Comment by sanjaypujare** [comment]
> ...
> Sorry, I haven't submitted many PRs, does this mean it's better to open a new PR?

It's okay for now.

**Comment by sanjaypujare** [comment]
> > @zenghu1chen couple of points: did you look at the original issue #7540 because of which @dzou made a change in 
> 
> @sanjaypujare By default, the shadow project will copy all configuration files, and if there is no `transform`, the native-image related configuration will still exist and affect the compilation.

But looking at the comment https://github.com/grpc/grpc-java/issues/7540#issue-725879917 which says:

 I.e. native-image.properties and reflection-config.json in the screenshot.

Inside these config files, the library writers reference Netty package classes, and it would be very useful if these classes could also have their packages renamed during the shading process.
...
...
These files and settings are used by Oracle's [GraalVM compiler](https://www.graalvm.org/reference-manual/native-image/) to assist in the ahead-of-time compilation process. The original library writers added it in so that it would work with native image building.
----------------------------------
With your change, all of the config files - json and properties files under ` META-INF/native-image/io.grpc.netty.shaded.io.netty/` are gone directly undoing what #8258 did. So this is definitely breaking that.

**Comment by zenghu1chen** [comment]
> > > @zenghu1chen couple of points: did you look at the original issue #7540 because of which @dzou made a change in
> > 
> > 
> > @sanjaypujare By default, the shadow project will copy all configuration files, and if there is no `transform`, the native-image related configuration will still exist and affect the compilation.
> 
> But looking at the comment [#7540 (comment)](https://github.com/grpc/grpc-java/issues/7540#issue-725879917) which says:
> 
> i.e. native-image.properties and reflection-config.json in the screenshot.
> 
> Inside these config files, the library writers reference Netty package classes, and it would be very useful if these classes could also have their packages renamed during the shading process. ... ... These files and settings are used by Oracle's [GraalVM compiler](https://www.graalvm.org/reference-manual/native-image/) to assist in the ahead-of-time compilation process. The original library writers added it in so that it would work with native image building.
> 
> With your change, all of the config files - json and properties files under ` META-INF/native-image/io.grpc.netty.shaded.io.netty/` are gone; directly undoing what #8258 did. So this is definitely breaking that.

Yes, my modification will break the previous changes. However, I also tried introducing the netty-all library (the native-image configuration from grpc-netty-shaded was copied from here), and it was able to compile successfully. It's possible that some code in grpc-netty is causing the issue. I'm not very familiar with grpc-netty, so I haven't been able to pinpoint the exact reason. Of course, it would be more reliable to have the previous PR committer review it.

@dzou Do you currently use the grpc-netty-shaded package for native-image compilation? I found that simply importing this library causes compilation failure, resulting in my project not being able to compile properly. My current solution is to delete all native-image configuration files. Would you like to help review this PR?

**Comment by ejona86** [comment]
Closing, since this is definitely the wrong approach. https://github.com/grpc/grpc-java/issues/10601#issuecomment-1887352315 may have found what is really going on.

**Pull request closed without merging**
