### PR TITLE
core: remove unused, non-public INTEGER_MARSHALLER

### PR DESCRIPTION
**Pull request by devinrsmith**

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
@devinrsmith motivation?

**Comment by devinrsmith** [comment]
Well, I assume this was originally meant to be a public field. Same as `ASCII_STRING_MARSHALLER`. Furthermore, `INTEGER_MARSHALLER` isn't actually used anywhere (except for tests). So I think it makes sense to either expose it, or get rid of it.

**Comment by carl-mastrangelo** [comment]
@devinrsmith get rid of it would be my preference.  It was used at one point, but it's pretty inefficient.    

We generally avoid making things public if possible.

**Comment by carl-mastrangelo** [comment]
ok to test

**Comment by devinrsmith** [comment]
Not familiar w/ nature of build system, but `io.grpc.internal.ManagedChannelImplTest.orphanedChannelsAreLogged` error in build seems unrelated on first glance.

**Comment by ericgribkoff** [comment]
Yes, it's a flaky test (just filed https://github.com/grpc/grpc-java/issues/3534) and should be unrelated to this PR.

Jenkins: retest this please

**Comment by carl-mastrangelo** [comment]
@devinrsmith thanks for the PR!

**Pull request merged**
