### PR TITLE
Cleaning up closing for Netty client/server.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 this is a follow up to c8c478ef81b46d41ed22ac461d005764e32aeaac  that addresses both the client and server side.

**Comment by nicolasnoble** [comment]
Can one of the admins verify this patch?

**Comment by ejona86** [comment]
It looks like the most important change is updating Netty, but it looks like it should be updating to 4ae8bdc instead. Am I wrong in saying that most of changes in gRPC is just removing duplicate logic?

**Comment by nmittler** [comment]
@ejona86 let's take care of #384 first ... then we don't have to update Netty here.

**Comment by nmittler** [comment]
@ejona86 PTAL ... netty update was already cherry-picked in #384.

**Comment by nmittler** [comment]
@ejona86 to answer your question ... yes, this PR is really just removing duplicate logic.  Same as you had done to the client side.

**Comment by ejona86** [comment]
@nmittler, LGTM

**Comment by nmittler** [comment]
cherry-picked as a45e0a4

**Pull request closed without merging**
