### PR TITLE
Bump jmh version

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
I *think* this is the right dependency.  The non-human output is no longer a csv, but a pretty printed thing:

```
Benchmark                         (direct)  (transport)    Mode     Cnt       Score      Error  Units
TransportBenchmark.unaryCall1024      true    INPROCESS  sample  167108    1940.559 ±   71.075  ns/op
TransportBenchmark.unaryCall1024      true        NETTY  sample   53661  186022.724 ±  831.145  ns/op
TransportBenchmark.unaryCall1024      true  NETTY_LOCAL  sample   70103  142373.016 ± 1289.851  ns/op
TransportBenchmark.unaryCall1024      true       OKHTTP  sample   60197  165787.647 ±  837.417  ns/op
TransportBenchmark.unaryCall1024     false    INPROCESS  sample  134951   18513.425 ±   90.265  ns/op
TransportBenchmark.unaryCall1024     false        NETTY  sample   39650  251823.552 ± 1213.486  ns/op
TransportBenchmark.unaryCall1024     false  NETTY_LOCAL  sample   53622  186167.566 ± 1767.848  ns/op
TransportBenchmark.unaryCall1024     false       OKHTTP  sample   46003  217035.062 ± 1127.454  ns/op
```

### CODE REVIEW

**Comment by nmittler** [comment]
LGTM

**Comment by ejona86** [comment]
Could you file a bug against https://github.com/melix/jmh-gradle-plugin to point out their README doesn't have the right dependency (and differs from https://plugins.gradle.org/plugin/me.champeau.gradle.jmh). It seems like it is likely a bug.

**Comment by ejona86** [comment]
LGTM

**Comment by carl-mastrangelo** [comment]
Done here: https://github.com/melix/jmh-gradle-plugin/issues/70

**Pull request merged**
