### PR TITLE
xds: Envoy proto sync to 2024-07-06

### PR DESCRIPTION
**Pull request by sergiitk**
`envoyproxy/envoy`: Sync protos to the latest imported version https://github.com/envoyproxy/envoy/commit/ab911ac2ff971f805ec822ad4d4ff6b42a61cc7c (commit 2024-07-06, cl/651956889).

Should be a noop, just a routine xDS proto update to make upcoming RLQS-related imports simpler.

### CODE REVIEW

**Comment by ejona86** [comment]
Update repositories.bzl as well.

**Comment by sergiitk** [comment]
Thanks - this was the first step. I think I should've made it a draft to be clear.

**Comment by sergiitk** [comment]
@ejona86 - updated repositories.bzl.  Few questions:
1. Is there anything I need to do in MODULE.bazel? 
2. Is the CI bazel builds cover everything we want now (including user' side), or do I run any additional checks?

**Comment by ejona86** [comment]
> Is there anything I need to do in MODULE.bazel?

No. This specific dependency is still pulled from the old way, even with MODULE.bazel. So there's nothing extra in this specific case.

> Is the CI bazel builds cover everything we want now (including user' side), or do I run any additional checks?

Yeah, you should be good to go.

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
