### PR TITLE
Bump Guava to 19.0

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
There isn't a strong reason to to bump this, but it's good to stay up to date.  There are minor bug fixes, but I don't believe they affect us at all.

### CODE REVIEW

**Comment by ejona86** [comment]
It would probably be good to verify that the v1 client libraries work with Guava 19 before we bump our version. I think they're on Guava 17 right now.

**Comment by carl-mastrangelo** [comment]
How do I check?

**Comment by ejona86** [comment]
You can build https://github.com/google/google-http-java-client/, https://github.com/google/google-oauth-java-client/, and https://github.com/google/google-api-java-client/ after bumping the Guava version in their pom.xml. You will need to point it to guava instead of guava-jdk5, and that's "okay" for this exercise.

I _think_ the builds aren't too annoying now that it is using the protoc plugin. Although I think the api client requires having an ANDROID_HOME configured. If it becomes too annoying, I can do it.

**Comment by carl-mastrangelo** [comment]
I checked the second and third repos, replaced all refs to guava-jdk5 with the regular guava, and ran `mvn package` in them.  Both of these worked.

The first one worked a little, but complained 
```
[ERROR] Failed to execute goal on project google-api-client-android: Could not resolve dependencies for project com.google.api-client:google-api-client-android:jar:1.22.0-SNAPSHOT: Could not find artifact com.google.android.google-play-services:google-play-services:jar:1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :google-api-client-android
```

**Comment by carl-mastrangelo** [comment]
@ejona86 I checked with the first package after I got android working, and mvn package worked as well. I believe all three packages worked with the later version.

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

**Pull request merged**
