### PR TITLE
examples: Updated the deleted reference attachHeaders to newAttachHeadersInterceptor in HeaderClientInterceptor for header example

### PR DESCRIPTION
**Pull request by vinodhabib**
Updated the deleted reference attachHeaders to newAttachHeadersInterceptor in HeaderClientInterceptor for header example

Fixes https://github.com/grpc/grpc-java/issues/11693

### CODE REVIEW

**Review by shivaspeaks — COMMENTED** [review]
Is there any replacement for this deprecated method? Or is it totally removed?

This is what I found from the PR that removed the deprecated attachHeaders, `Use {@code stub.withInterceptors(newAttachHeadersInterceptor(...))} instea`
image

CC: @kannanjgithub

**Comment by vinodhabib** [comment]
> #11693

@shivaspeaks As per my understanding this deprecated method is totally 

> Is there any replacement for this deprecated method? Or is it totally removed?
> 
> This is what I found from the PR that removed the deprecated attachHeaders, `Use {@code stub.withInterceptors(newAttachHeadersInterceptor(...))} instea` image
> 
> CC: @kannanjgithub

@shivaspeaks As per my understanding it looks like these deprecated methods are completely removed so this ticket is raised recently with the scope of removing the deleted reference by label issue as docs. 
also can see notes from Sanjay in the PR (https://github.com/grpc/grpc-java/pull/10443) as **have made sure there is no internal usage of these methods**

I hope we are good here, please confirm.

**Comment by ejona86** [comment]
The reference should be updated to `newAttachHeadersInterceptor()`

**Comment by vinodhabib** [comment]
> The reference should be updated to `newAttachHeadersInterceptor()`

@ejona86 updated the reference to newAttachHeadersInterceptor

**Review by ejona86 — APPROVED** [review]

**Review by shivaspeaks — APPROVED** [review]

**Pull request merged**
