### PR TITLE
Updating the server1 cert so that it can be used with Go.

### PR DESCRIPTION
**Pull request by jboeuf**
The encoding of the issuer field in this cert is now a PRINTABLESTRING
as opposed to UTF8STRING in the previous server1.pem which was causing
the Go issue.

- https://github.com/grpc/grpc/pull/4096
- https://github.com/grpc/grpc-go/pull/442

Sorry I should have done this java PR and have it approved before
submitting the grpc-go and grpc PRs.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Friendly ping. It would be good to unbreak interop tests that are currently failing because of this.

**Comment by carl-mastrangelo** [comment]
@jboeuf LGTM

**Comment by ejona86** [comment]
@jboeuf LGTM

**Comment by ejona86** [comment]
@jboeuf. I'll merge this in and push it.

**Comment by jboeuf** [comment]
Thanks much! And sorry again for breaking the interop tests...

**Pull request merged**
