### PR TITLE
dep: bump netty to 4.1.69.Final and tcnative to 2.0.44.Final

### PR DESCRIPTION
**Pull request by ran-su**

### CODE REVIEW

**Comment by dapengzhang0** [comment]
The issue should be fixed in Netty 4.1.71.Final. Let's wait for that release.

**Comment by sergiitk** [comment]
Temporary re-opening this to build artifacts for related investigation.

**Comment by sergiitk** [comment]
For some reason, build artifacts were not saved. Closing this to try from my branch #8815 8815

**Comment by sanjaypujare** [comment]
> For some reason, build artifacts were not saved. Closing this to try from my branch #8815

You mean the test reports? You may need the changes I made in https://github.com/grpc/grpc-java/pull/8813/files#diff-a515351cde89a1974efa33a43ab0012a052e0f14deff85710f296934e81cabdbR18 and https://github.com/grpc/grpc-java/pull/8813/files#diff-79ced7352cff631f4849c3a808ab5c28f76a38c8ce8bc0f8f018168e5b79d96bR11

**Comment by sergiitk** [comment]
Yes, this. I thought we already had it at least for linux_artifacts.

**Comment by sanjaypujare** [comment]
> Yes, this. I thought we already had it at least for linux_artifacts.

@dapengzhang0 made this change https://github.com/grpc/grpc-java/pull/8801 recently for linux tests. However the artifacts are accessed differently.

**Pull request closed without merging**
