### PR TITLE
Revert "Draft of Android specific Channe builder"

### PR DESCRIPTION
**Pull request by louiscryan**
This reverts commit d6dc790f05c90ffba2c7a4356121ae4d586e467e.

Fix for #959

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
FYI, if you feel comfortable bumping the min gradle version to 2.4 or 2.5, you may not need to revert this.  (or if possible, selectively pick the dependency based on the current gradle version).

**Comment by ejona86** [comment]
@louiscryan, even though we don't know if we want to go down this road, LGTM :)

**Comment by ejona86** [comment]
@louiscryan, we want to go ahead and pull the trigger on this?

**Comment by louiscryan** [comment]
Yup

-louis (from phone)

**Comment by louiscryan** [comment]
Committed

**Comment by ejona86** [comment]
It was cherrypicked as 540b4d3

**Pull request closed without merging**
