### PR TITLE
Avoid NettyServerBuilder in security documentation

### PR DESCRIPTION
**Pull request by ejona86**
The more generic ServerBuilder is all that is necessary.

### CODE REVIEW

**Comment by nmittler** [comment]
LGTM

**Comment by ejona86** [comment]
@nmittler, PTAL, I noticed the following paragraph no longer worked because the example wasn't using SslContext

**Comment by nmittler** [comment]
LGTM

**Comment by ejona86** [comment]
Committed as a4a8438

**Pull request closed without merging**
