### PR TITLE
Fix build failure due to unused import.

### PR DESCRIPTION
**Pull request by buchgr**
I recommend a merge commit over a cherry pick :smile:

### CODE REVIEW

**Comment by nmittler** [comment]
LGTM ... feel free to incorporate whichever way you'd prefer :)

**Comment by buchgr** [comment]
I don't have commit access :cry:

**Comment by nmittler** [comment]
You should now have write access ... want to give it a try?

**Comment by ejona86** [comment]
I just went ahead and merged it. @buchgr, you can try out your write access on #1202

**Comment by buchgr** [comment]
@nmittler @ejona86 thanks. have access now :-).

**Pull request merged**
