### PR TITLE
Cut 1.2.0

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
2 commits, as always

### CODE REVIEW

**Comment by zhangkun83** [comment]
Since 1.2 is still weeks away, we should keep the current versions, and only bump it when we tag 1.2.0.

**Comment by carl-mastrangelo** [comment]
Normally I agree, but I think that is for master, which is what people see when they clone the repo or visit the front page at github.  I was planning on bumping the recommended version numbers on master once 1.2.0 is on maven central.

**Comment by carl-mastrangelo** [comment]
@zhangkun83 PTAL

**Comment by ejona86** [comment]
I thought we make the README changes in a separate commit, so it can be "forward ported" to master.

**Pull request merged**
