### PR TITLE
xds: fix XdsLoadStatsStoreTest.recordingDroppedRequests flaky NPE

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by dapengzhang0** [comment]
NPE observed:

https://travis-ci.org/grpc/grpc-java/jobs/534946338

```
> Task :grpc-xds:test
io.grpc.xds.XdsLoadStatsStoreTest > recordingDroppedRequests FAILED
    java.lang.NullPointerException
        at io.grpc.xds.XdsLoadStatsStoreTest.recordingDroppedRequests(XdsLoadStatsStoreTest.java:266)
47 tests completed, 1 failed
> Task :grpc-xds:test FAILED
```

**Comment by voidzcy** [comment]
@dapengzhang0 
What's happening here? Why using random numbers leads to flakiness? There are some other tests that involve random numbers.

**Comment by dapengzhang0** [comment]
Because 0 is a possible return value of `nextInt()` which leads to NPE.
>Why using random numbers leads to flakiness?

**Comment by voidzcy** [comment]
> Because 0 is a possible return value of `nextInt()` which leads to NPE.
> 
> > Why using random numbers leads to flakiness?

Alright. Then it will be fine for other places.

**Pull request merged**
