### PR TITLE
Making test certs more shareable

### PR DESCRIPTION
**Pull request by nmittler**
To use the test certs a module has to depend on the grpc-interop-testing module, which doesn't really make sense.  I'm moving the certs to the grpc-testing module, which is meant to be a sort of testing common area for all of our modules.

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 PTAL ... this is in part to help with development of the Jetty test (in the Netty module).

**Comment by nmittler** [comment]
@ejona86 now that 0.7.0 has been released, I'd like to get this in ... can you take a look?

**Comment by ejona86** [comment]
@nmittler LGTM

**Comment by nmittler** [comment]
cherry-picked as f770ffb

**Pull request closed without merging**
