### PR TITLE
Correct sha1 for common-protos

### LINKED ISSUE #3802: SHA-1 failure for proto-google-common-protos-1.0.0.jar
Platform: Ubuntu 14.04
Bazel version: 0.8.0

If I run the Bazel build with:

```
git clone https://github.com/grpc/grpc-java
cd grpc-java
bazel build //...
```

I get:

```
ERROR: <snip>/grpc-java/examples/BUILD.bazel:53:1:
  no such package '@com_google_api_grpc_proto_google_common_protos//jar':
  Downloaded file at <snip>/external/com_google_api_grpc_proto_google_common_protos/com/google/api/grpc/proto-google-common-protos/1.0.0/proto-google-common-protos-1.0.0.jar
  has SHA-1 of 86f070507e28b930e50d218ee5b6788ef0dd05e6, does not match expected SHA-1
  (de4e859c3530f7e9f854e40b0a8b7074d95e3aff) and referenced by '//examples:examples'
ERROR: Analysis of target '//examples:examples' failed; build aborted:
  no such package '@com_google_api_grpc_proto_google_common_protos//jar':
  Downloaded file at <snip>/external/com_google_api_grpc_proto_google_common_protos/com/google/api/grpc/proto-google-common-protos/1.0.0/proto-google-common-protos-1.0.0.jar
  has SHA-1 of 86f070507e28b930e50d218ee5b6788ef0dd05e6, does not match expected SHA-1
  (de4e859c3530f7e9f854e40b0a8b7074d95e3aff)
INFO: Elapsed time: 6.185s
FAILED: Build did NOT complete successfully (53 packages loaded)
```

It can be fixed by updating the SHA-1 in repositories.bzl.

### PR DESCRIPTION
**Pull request by drigz**
Fixes #3802.

### CODE REVIEW

**Comment by carl-mastrangelo** [comment]
ok to test

**Comment by ejona86** [comment]
I didn't notice the PR earlier, otherwise I wouldn't have included it in #3814!

**Comment by carl-mastrangelo** [comment]
@drigz Thanks!

**Comment by ejona86** [comment]
Removed bug label because the bug hadn't been released.

**Pull request merged**
