### PR TITLE
Replaced outdated exclusion comments

### PR DESCRIPTION
**Pull request by suztomo**
Followup of https://github.com/grpc/grpc-java/pull/6488#discussion_r354459784. These comments on exclusions with specific versions are hard to maintain.

### CODE REVIEW

**Comment by suztomo** [comment]
@creamsoup Would you check this too?

**Comment by suztomo** [comment]
??? https://source.cloud.google.com/results/invocations/3ad5cb7c-c2d8-49e4-82ce-5db7dde4c2b6/log
```
> Task :grpc-interop-testing:test

io.grpc.testing.integration.NettyFlowControlTest > largeBdp FAILED
    java.lang.AssertionError: Window was 688124 expecting 314570
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.grpc.testing.integration.NettyFlowControlTest.doTest(NettyFlowControlTest.java:154)
        at io.grpc.testing.integration.NettyFlowControlTest.largeBdp(NettyFlowControlTest.java:106)
```

**Comment by creamsoup** [comment]
that's a known flaky test, i logged this in the [existing issue](https://github.com/grpc/grpc-java/issues/2297).

**Comment by suztomo** [comment]
Okay. Thanks. Then it's ready for merge.

**Comment by creamsoup** [comment]
kokoro is extra flaky today, as soon as all the required checks are finished. i'll merge it.

**Comment by creamsoup** [comment]
merged! thanks again @suztomo

**Comment by suztomo** [comment]
Thank you.

**Pull request merged**
