### PR TITLE
inprocess: mark all classes final

### PR DESCRIPTION
**Pull request by carl-mastrangelo**

### CODE REVIEW

**Comment by rmichela** [comment]
I'm curious...why? Is there an explicit need to prevent extension of the inprocess classes? What's the harm? Why block future use cases just because you can't envision them right now?

Requiring someone to ask to remove finality stifles innovation.

**Comment by carl-mastrangelo** [comment]
@rmichela See Effective Java Item 17: "Design and document for inheritance or else prohibit it".  Also Item 16: Favor composition over inheritance


Adding final is future proofing; easy to remove but hard to add.  These classes weren't designed for inheritance, so they should be final.   If you would like to propose how one could extend these, I don't think there would be pushback to remove it.

**Comment by carl-mastrangelo** [comment]
@rmichela Also: do you have code extending these?  If so, what's the use case?

**Comment by rmichela** [comment]
I took another look at the `InProcess*` classes. I see why this change was made.

I've had bad experiences in the past with frameworks being too rigidly locked down to the set of approved use cases, making unenvisioned usage impossible. (:cough: Microsoft)

**Comment by ejona86** [comment]
@rmichela, lacking final _strongly_ limits what changes are backward-compatible. We are _strongly_ devoted to API stability, so we want public classes `final` "by default" to reduce accidents.

I am a user that has done quite interesting things to classes that weren't marked as final, so I know some of the benefit. But I also see how it makes it basically impossible to extend later unless you prepared and were _very_ thorough ahead-of-time (like marking certain methods final).

Anyway, must of the final classes seem to be pretty useless for most people to extend, so it's not been a concern. Other cases like the stubs... are more nuanced.

**Pull request merged**
