### PR TITLE
interop-testing: fix tests on Android

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Updates #5832

cc: @ejona86

### CODE REVIEW

**Comment by dapengzhang0** [comment]
Did you try to use `android.support.test.rule.DisableOnAndroidDebug` instead of `DisableOnDebug` directly? I wonder if that works.

**Comment by carl-mastrangelo** [comment]
@dapengzhang0 can we even pull in that dependency?

**Comment by dapengzhang0** [comment]
That would be as painful as the deps of `android.annotation.SuppressLint` that I added [before](https://github.com/grpc/grpc-java/commit/b7dd92e7bb3fbc476a186177aee39230440238bd).

>can we even pull in that dependency?

I checked the source code of `DisableOnAndroidDebug`, seems it will not work for non-android.

**Comment by carl-mastrangelo** [comment]
@dapengzhang0 I don't really debug on Android.  I think it's okay for the timeout to fallback to how it works now.

**Comment by dapengzhang0** [comment]
LGTM

**Pull request merged**
