### PR TITLE
Support setting ALPN for Android older than 5.0, OkHttp(2.3+) impleme…

### LINKED ISSUE #520: Add ALPN setting path for Android older than 5.0
OkHttp only support setting ALPN on Android 5.0+ since 2.3

### PR DESCRIPTION
**Pull request by madongfly**
…ntation only support such function for Android 5.0+.

Manually tested with the test App: https://github.com/madongfly/grpc-android-test.

Fixes #520 

@ejona86

### CODE REVIEW

**Comment by ejona86** [comment]
Can you please provide more description as to what is different about this code and what was being done previously.

Does this support using jetty_alpn?

**Comment by madongfly** [comment]
Since OkHttp 2.3, the Platform#configureTlsExtensions method only call the reflected method to set ALPN for Android 5.0+, while OkHttp 2.2 and earlier would do it for Android 2.3+ (versions older than 4.4 can be succeed by installing the security provider).

This change basically doing the things that OkHttp2.2's Android platform did, it only overrides the functions of the Android platform, has nothing to do with jetty_alpn.

**Comment by ejona86** [comment]
@madongfly, I hear what you are saying about configureTlsExtensions, but I'm trying to understand what the actual important lines changed are.  If I was to look at a diff of OkHttp and this code, what important things would stand out? Just the static block with the Class.forName? Something else?

**Comment by madongfly** [comment]
@ejona86 
The static Class.forName was already there, OkHttpProtocolNegotiator was renamed from SelectedProtocolQuerier.java, with adding the configureTlsExtensions implementation and updating getSelectedProtocol.

I felt it should not be named as a "Querier" anymore, so I moved the negotiation code from OkHttpTlsUpgrader.java into it and named it as a "Negotiator".

**Comment by ejona86** [comment]
@madongfly LGTM

**Pull request merged**
