### PR TITLE
Always checking MAX_CONCURRENT_STREAMS in

### PR DESCRIPTION
**Pull request by nmittler**
BufferingHttp2ConnectionEncoder.

Currently we don't check this setting when handling a streamClosed()
event. If the setting has lowered prior to this event, the stream
creation could fail.

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 @buchgr can you take a look?

**Comment by nicolasnoble** [comment]
Can one of the admins verify this patch?

**Comment by ejona86** [comment]
@nmittler, LGTM

**Comment by buchgr** [comment]
@nmittler LGTM

**Comment by nmittler** [comment]
cherry-picked as 7f73189

**Pull request closed without merging**
